// Code generated by MockGen. DO NOT EDIT.
// Source: aggregator_app.go
//
// Generated by this command:
//
//	mockgen -source=aggregator_app.go -destination=mocks/aggregator_app.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	big "math/big"
	entity "middleware-offchain/internal/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockethClient is a mock of ethClient interface.
type MockethClient struct {
	ctrl     *gomock.Controller
	recorder *MockethClientMockRecorder
	isgomock struct{}
}

// MockethClientMockRecorder is the mock recorder for MockethClient.
type MockethClientMockRecorder struct {
	mock *MockethClient
}

// NewMockethClient creates a new mock instance.
func NewMockethClient(ctrl *gomock.Controller) *MockethClient {
	mock := &MockethClient{ctrl: ctrl}
	mock.recorder = &MockethClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockethClient) EXPECT() *MockethClientMockRecorder {
	return m.recorder
}

// GetQuorumThreshold mocks base method.
func (m *MockethClient) GetQuorumThreshold(ctx context.Context, timestamp *big.Int, keyTag uint8) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuorumThreshold", ctx, timestamp, keyTag)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuorumThreshold indicates an expected call of GetQuorumThreshold.
func (mr *MockethClientMockRecorder) GetQuorumThreshold(ctx, timestamp, keyTag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuorumThreshold", reflect.TypeOf((*MockethClient)(nil).GetQuorumThreshold), ctx, timestamp, keyTag)
}

// MockvalsetDeriver is a mock of valsetDeriver interface.
type MockvalsetDeriver struct {
	ctrl     *gomock.Controller
	recorder *MockvalsetDeriverMockRecorder
	isgomock struct{}
}

// MockvalsetDeriverMockRecorder is the mock recorder for MockvalsetDeriver.
type MockvalsetDeriverMockRecorder struct {
	mock *MockvalsetDeriver
}

// NewMockvalsetDeriver creates a new mock instance.
func NewMockvalsetDeriver(ctrl *gomock.Controller) *MockvalsetDeriver {
	mock := &MockvalsetDeriver{ctrl: ctrl}
	mock.recorder = &MockvalsetDeriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvalsetDeriver) EXPECT() *MockvalsetDeriverMockRecorder {
	return m.recorder
}

// GetValidatorSet mocks base method.
func (m *MockvalsetDeriver) GetValidatorSet(ctx context.Context, timestamp *big.Int) (entity.ValidatorSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidatorSet", ctx, timestamp)
	ret0, _ := ret[0].(entity.ValidatorSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidatorSet indicates an expected call of GetValidatorSet.
func (mr *MockvalsetDeriverMockRecorder) GetValidatorSet(ctx, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidatorSet", reflect.TypeOf((*MockvalsetDeriver)(nil).GetValidatorSet), ctx, timestamp)
}

// Mockp2pClient is a mock of p2pClient interface.
type Mockp2pClient struct {
	ctrl     *gomock.Controller
	recorder *Mockp2pClientMockRecorder
	isgomock struct{}
}

// Mockp2pClientMockRecorder is the mock recorder for Mockp2pClient.
type Mockp2pClientMockRecorder struct {
	mock *Mockp2pClient
}

// NewMockp2pClient creates a new mock instance.
func NewMockp2pClient(ctrl *gomock.Controller) *Mockp2pClient {
	mock := &Mockp2pClient{ctrl: ctrl}
	mock.recorder = &Mockp2pClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockp2pClient) EXPECT() *Mockp2pClientMockRecorder {
	return m.recorder
}

// BroadcastSignatureAggregatedMessage mocks base method.
func (m *Mockp2pClient) BroadcastSignatureAggregatedMessage(ctx context.Context, msg entity.SignaturesAggregatedMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BroadcastSignatureAggregatedMessage", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// BroadcastSignatureAggregatedMessage indicates an expected call of BroadcastSignatureAggregatedMessage.
func (mr *Mockp2pClientMockRecorder) BroadcastSignatureAggregatedMessage(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastSignatureAggregatedMessage", reflect.TypeOf((*Mockp2pClient)(nil).BroadcastSignatureAggregatedMessage), ctx, msg)
}

// SetSignatureHashMessageHandler mocks base method.
func (m *Mockp2pClient) SetSignatureHashMessageHandler(mh func(context.Context, entity.P2PSignatureHashMessage) error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSignatureHashMessageHandler", mh)
}

// SetSignatureHashMessageHandler indicates an expected call of SetSignatureHashMessageHandler.
func (mr *Mockp2pClientMockRecorder) SetSignatureHashMessageHandler(mh any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSignatureHashMessageHandler", reflect.TypeOf((*Mockp2pClient)(nil).SetSignatureHashMessageHandler), mh)
}
