// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/symbioticfi/relay/symbiotic/client/evm (interfaces: IEvmClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/evm_client.go -package=mocks github.com/symbioticfi/relay/symbiotic/client/evm IEvmClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	big "math/big"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	entity "github.com/symbioticfi/relay/symbiotic/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockIEvmClient is a mock of IEvmClient interface.
type MockIEvmClient struct {
	ctrl     *gomock.Controller
	recorder *MockIEvmClientMockRecorder
	isgomock struct{}
}

// MockIEvmClientMockRecorder is the mock recorder for MockIEvmClient.
type MockIEvmClientMockRecorder struct {
	mock *MockIEvmClient
}

// NewMockIEvmClient creates a new mock instance.
func NewMockIEvmClient(ctrl *gomock.Controller) *MockIEvmClient {
	mock := &MockIEvmClient{ctrl: ctrl}
	mock.recorder = &MockIEvmClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEvmClient) EXPECT() *MockIEvmClientMockRecorder {
	return m.recorder
}

// CommitValsetHeader mocks base method.
func (m *MockIEvmClient) CommitValsetHeader(ctx context.Context, addr entity.CrossChainAddress, header entity.ValidatorSetHeader, extraData []entity.ExtraData, proof []byte) (entity.TxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitValsetHeader", ctx, addr, header, extraData, proof)
	ret0, _ := ret[0].(entity.TxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitValsetHeader indicates an expected call of CommitValsetHeader.
func (mr *MockIEvmClientMockRecorder) CommitValsetHeader(ctx, addr, header, extraData, proof any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitValsetHeader", reflect.TypeOf((*MockIEvmClient)(nil).CommitValsetHeader), ctx, addr, header, extraData, proof)
}

// GetCaptureTimestampFromValsetHeaderAt mocks base method.
func (m *MockIEvmClient) GetCaptureTimestampFromValsetHeaderAt(ctx context.Context, addr entity.CrossChainAddress, epoch entity.Epoch) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCaptureTimestampFromValsetHeaderAt", ctx, addr, epoch)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCaptureTimestampFromValsetHeaderAt indicates an expected call of GetCaptureTimestampFromValsetHeaderAt.
func (mr *MockIEvmClientMockRecorder) GetCaptureTimestampFromValsetHeaderAt(ctx, addr, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCaptureTimestampFromValsetHeaderAt", reflect.TypeOf((*MockIEvmClient)(nil).GetCaptureTimestampFromValsetHeaderAt), ctx, addr, epoch)
}

// GetChains mocks base method.
func (m *MockIEvmClient) GetChains() []uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChains")
	ret0, _ := ret[0].([]uint64)
	return ret0
}

// GetChains indicates an expected call of GetChains.
func (mr *MockIEvmClientMockRecorder) GetChains() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChains", reflect.TypeOf((*MockIEvmClient)(nil).GetChains))
}

// GetConfig mocks base method.
func (m *MockIEvmClient) GetConfig(ctx context.Context, timestamp entity.Timestamp, epoch entity.Epoch) (entity.NetworkConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", ctx, timestamp, epoch)
	ret0, _ := ret[0].(entity.NetworkConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockIEvmClientMockRecorder) GetConfig(ctx, timestamp, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockIEvmClient)(nil).GetConfig), ctx, timestamp, epoch)
}

// GetCurrentEpoch mocks base method.
func (m *MockIEvmClient) GetCurrentEpoch(ctx context.Context) (entity.Epoch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentEpoch", ctx)
	ret0, _ := ret[0].(entity.Epoch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentEpoch indicates an expected call of GetCurrentEpoch.
func (mr *MockIEvmClientMockRecorder) GetCurrentEpoch(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentEpoch", reflect.TypeOf((*MockIEvmClient)(nil).GetCurrentEpoch), ctx)
}

// GetCurrentEpochDuration mocks base method.
func (m *MockIEvmClient) GetCurrentEpochDuration(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentEpochDuration", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentEpochDuration indicates an expected call of GetCurrentEpochDuration.
func (mr *MockIEvmClientMockRecorder) GetCurrentEpochDuration(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentEpochDuration", reflect.TypeOf((*MockIEvmClient)(nil).GetCurrentEpochDuration), ctx)
}

// GetEip712Domain mocks base method.
func (m *MockIEvmClient) GetEip712Domain(ctx context.Context, addr entity.CrossChainAddress) (entity.Eip712Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEip712Domain", ctx, addr)
	ret0, _ := ret[0].(entity.Eip712Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEip712Domain indicates an expected call of GetEip712Domain.
func (mr *MockIEvmClientMockRecorder) GetEip712Domain(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEip712Domain", reflect.TypeOf((*MockIEvmClient)(nil).GetEip712Domain), ctx, addr)
}

// GetEpochDuration mocks base method.
func (m *MockIEvmClient) GetEpochDuration(ctx context.Context, epoch entity.Epoch) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpochDuration", ctx, epoch)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEpochDuration indicates an expected call of GetEpochDuration.
func (mr *MockIEvmClientMockRecorder) GetEpochDuration(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpochDuration", reflect.TypeOf((*MockIEvmClient)(nil).GetEpochDuration), ctx, epoch)
}

// GetEpochStart mocks base method.
func (m *MockIEvmClient) GetEpochStart(ctx context.Context, epoch entity.Epoch) (entity.Timestamp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpochStart", ctx, epoch)
	ret0, _ := ret[0].(entity.Timestamp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEpochStart indicates an expected call of GetEpochStart.
func (mr *MockIEvmClientMockRecorder) GetEpochStart(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpochStart", reflect.TypeOf((*MockIEvmClient)(nil).GetEpochStart), ctx, epoch)
}

// GetHeaderHash mocks base method.
func (m *MockIEvmClient) GetHeaderHash(ctx context.Context, addr entity.CrossChainAddress) (common.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeaderHash", ctx, addr)
	ret0, _ := ret[0].(common.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeaderHash indicates an expected call of GetHeaderHash.
func (mr *MockIEvmClientMockRecorder) GetHeaderHash(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeaderHash", reflect.TypeOf((*MockIEvmClient)(nil).GetHeaderHash), ctx, addr)
}

// GetHeaderHashAt mocks base method.
func (m *MockIEvmClient) GetHeaderHashAt(ctx context.Context, addr entity.CrossChainAddress, epoch entity.Epoch) (common.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeaderHashAt", ctx, addr, epoch)
	ret0, _ := ret[0].(common.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeaderHashAt indicates an expected call of GetHeaderHashAt.
func (mr *MockIEvmClientMockRecorder) GetHeaderHashAt(ctx, addr, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeaderHashAt", reflect.TypeOf((*MockIEvmClient)(nil).GetHeaderHashAt), ctx, addr, epoch)
}

// GetKeys mocks base method.
func (m *MockIEvmClient) GetKeys(ctx context.Context, address entity.CrossChainAddress, timestamp entity.Timestamp) ([]entity.OperatorWithKeys, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeys", ctx, address, timestamp)
	ret0, _ := ret[0].([]entity.OperatorWithKeys)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeys indicates an expected call of GetKeys.
func (mr *MockIEvmClientMockRecorder) GetKeys(ctx, address, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeys", reflect.TypeOf((*MockIEvmClient)(nil).GetKeys), ctx, address, timestamp)
}

// GetLastCommittedHeaderEpoch mocks base method.
func (m *MockIEvmClient) GetLastCommittedHeaderEpoch(ctx context.Context, addr entity.CrossChainAddress) (entity.Epoch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastCommittedHeaderEpoch", ctx, addr)
	ret0, _ := ret[0].(entity.Epoch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastCommittedHeaderEpoch indicates an expected call of GetLastCommittedHeaderEpoch.
func (mr *MockIEvmClientMockRecorder) GetLastCommittedHeaderEpoch(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastCommittedHeaderEpoch", reflect.TypeOf((*MockIEvmClient)(nil).GetLastCommittedHeaderEpoch), ctx, addr)
}

// GetNetworkAddress mocks base method.
func (m *MockIEvmClient) GetNetworkAddress(ctx context.Context) (common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkAddress", ctx)
	ret0, _ := ret[0].(common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkAddress indicates an expected call of GetNetworkAddress.
func (mr *MockIEvmClientMockRecorder) GetNetworkAddress(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkAddress", reflect.TypeOf((*MockIEvmClient)(nil).GetNetworkAddress), ctx)
}

// GetOperatorNonce mocks base method.
func (m *MockIEvmClient) GetOperatorNonce(ctx context.Context, votingPowerProvider entity.CrossChainAddress, operator common.Address) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperatorNonce", ctx, votingPowerProvider, operator)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOperatorNonce indicates an expected call of GetOperatorNonce.
func (mr *MockIEvmClientMockRecorder) GetOperatorNonce(ctx, votingPowerProvider, operator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperatorNonce", reflect.TypeOf((*MockIEvmClient)(nil).GetOperatorNonce), ctx, votingPowerProvider, operator)
}

// GetSubnetwork mocks base method.
func (m *MockIEvmClient) GetSubnetwork(ctx context.Context) (common.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubnetwork", ctx)
	ret0, _ := ret[0].(common.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubnetwork indicates an expected call of GetSubnetwork.
func (mr *MockIEvmClientMockRecorder) GetSubnetwork(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubnetwork", reflect.TypeOf((*MockIEvmClient)(nil).GetSubnetwork), ctx)
}

// GetValSetHeader mocks base method.
func (m *MockIEvmClient) GetValSetHeader(ctx context.Context, addr entity.CrossChainAddress) (entity.ValidatorSetHeader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValSetHeader", ctx, addr)
	ret0, _ := ret[0].(entity.ValidatorSetHeader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValSetHeader indicates an expected call of GetValSetHeader.
func (mr *MockIEvmClientMockRecorder) GetValSetHeader(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValSetHeader", reflect.TypeOf((*MockIEvmClient)(nil).GetValSetHeader), ctx, addr)
}

// GetValSetHeaderAt mocks base method.
func (m *MockIEvmClient) GetValSetHeaderAt(ctx context.Context, addr entity.CrossChainAddress, epoch entity.Epoch) (entity.ValidatorSetHeader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValSetHeaderAt", ctx, addr, epoch)
	ret0, _ := ret[0].(entity.ValidatorSetHeader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValSetHeaderAt indicates an expected call of GetValSetHeaderAt.
func (mr *MockIEvmClientMockRecorder) GetValSetHeaderAt(ctx, addr, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValSetHeaderAt", reflect.TypeOf((*MockIEvmClient)(nil).GetValSetHeaderAt), ctx, addr, epoch)
}

// GetVotingPowerProviderEip712Domain mocks base method.
func (m *MockIEvmClient) GetVotingPowerProviderEip712Domain(ctx context.Context, addr entity.CrossChainAddress) (entity.Eip712Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVotingPowerProviderEip712Domain", ctx, addr)
	ret0, _ := ret[0].(entity.Eip712Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVotingPowerProviderEip712Domain indicates an expected call of GetVotingPowerProviderEip712Domain.
func (mr *MockIEvmClientMockRecorder) GetVotingPowerProviderEip712Domain(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVotingPowerProviderEip712Domain", reflect.TypeOf((*MockIEvmClient)(nil).GetVotingPowerProviderEip712Domain), ctx, addr)
}

// GetVotingPowers mocks base method.
func (m *MockIEvmClient) GetVotingPowers(ctx context.Context, address entity.CrossChainAddress, timestamp entity.Timestamp) ([]entity.OperatorVotingPower, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVotingPowers", ctx, address, timestamp)
	ret0, _ := ret[0].([]entity.OperatorVotingPower)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVotingPowers indicates an expected call of GetVotingPowers.
func (mr *MockIEvmClientMockRecorder) GetVotingPowers(ctx, address, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVotingPowers", reflect.TypeOf((*MockIEvmClient)(nil).GetVotingPowers), ctx, address, timestamp)
}

// InvalidateOldSignatures mocks base method.
func (m *MockIEvmClient) InvalidateOldSignatures(ctx context.Context, addr entity.CrossChainAddress) (entity.TxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateOldSignatures", ctx, addr)
	ret0, _ := ret[0].(entity.TxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InvalidateOldSignatures indicates an expected call of InvalidateOldSignatures.
func (mr *MockIEvmClientMockRecorder) InvalidateOldSignatures(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateOldSignatures", reflect.TypeOf((*MockIEvmClient)(nil).InvalidateOldSignatures), ctx, addr)
}

// IsValsetHeaderCommittedAt mocks base method.
func (m *MockIEvmClient) IsValsetHeaderCommittedAt(ctx context.Context, addr entity.CrossChainAddress, epoch entity.Epoch) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValsetHeaderCommittedAt", ctx, addr, epoch)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsValsetHeaderCommittedAt indicates an expected call of IsValsetHeaderCommittedAt.
func (mr *MockIEvmClientMockRecorder) IsValsetHeaderCommittedAt(ctx, addr, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValsetHeaderCommittedAt", reflect.TypeOf((*MockIEvmClient)(nil).IsValsetHeaderCommittedAt), ctx, addr, epoch)
}

// IsValsetHeaderCommittedAtEpochs mocks base method.
func (m *MockIEvmClient) IsValsetHeaderCommittedAtEpochs(ctx context.Context, addr entity.CrossChainAddress, epochs []entity.Epoch) ([]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValsetHeaderCommittedAtEpochs", ctx, addr, epochs)
	ret0, _ := ret[0].([]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsValsetHeaderCommittedAtEpochs indicates an expected call of IsValsetHeaderCommittedAtEpochs.
func (mr *MockIEvmClientMockRecorder) IsValsetHeaderCommittedAtEpochs(ctx, addr, epochs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValsetHeaderCommittedAtEpochs", reflect.TypeOf((*MockIEvmClient)(nil).IsValsetHeaderCommittedAtEpochs), ctx, addr, epochs)
}

// RegisterKey mocks base method.
func (m *MockIEvmClient) RegisterKey(ctx context.Context, addr entity.CrossChainAddress, keyTag entity.KeyTag, key entity.CompactPublicKey, signature entity.RawSignature, extraData []byte) (entity.TxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterKey", ctx, addr, keyTag, key, signature, extraData)
	ret0, _ := ret[0].(entity.TxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterKey indicates an expected call of RegisterKey.
func (mr *MockIEvmClientMockRecorder) RegisterKey(ctx, addr, keyTag, key, signature, extraData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterKey", reflect.TypeOf((*MockIEvmClient)(nil).RegisterKey), ctx, addr, keyTag, key, signature, extraData)
}

// RegisterOperator mocks base method.
func (m *MockIEvmClient) RegisterOperator(ctx context.Context, addr entity.CrossChainAddress) (entity.TxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterOperator", ctx, addr)
	ret0, _ := ret[0].(entity.TxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterOperator indicates an expected call of RegisterOperator.
func (mr *MockIEvmClientMockRecorder) RegisterOperator(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterOperator", reflect.TypeOf((*MockIEvmClient)(nil).RegisterOperator), ctx, addr)
}

// RegisterOperatorVotingPowerProvider mocks base method.
func (m *MockIEvmClient) RegisterOperatorVotingPowerProvider(ctx context.Context, addr entity.CrossChainAddress) (entity.TxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterOperatorVotingPowerProvider", ctx, addr)
	ret0, _ := ret[0].(entity.TxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterOperatorVotingPowerProvider indicates an expected call of RegisterOperatorVotingPowerProvider.
func (mr *MockIEvmClientMockRecorder) RegisterOperatorVotingPowerProvider(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterOperatorVotingPowerProvider", reflect.TypeOf((*MockIEvmClient)(nil).RegisterOperatorVotingPowerProvider), ctx, addr)
}

// SetGenesis mocks base method.
func (m *MockIEvmClient) SetGenesis(ctx context.Context, addr entity.CrossChainAddress, header entity.ValidatorSetHeader, extraData []entity.ExtraData) (entity.TxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGenesis", ctx, addr, header, extraData)
	ret0, _ := ret[0].(entity.TxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetGenesis indicates an expected call of SetGenesis.
func (mr *MockIEvmClientMockRecorder) SetGenesis(ctx, addr, header, extraData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGenesis", reflect.TypeOf((*MockIEvmClient)(nil).SetGenesis), ctx, addr, header, extraData)
}

// UnregisterOperatorVotingPowerProvider mocks base method.
func (m *MockIEvmClient) UnregisterOperatorVotingPowerProvider(ctx context.Context, addr entity.CrossChainAddress) (entity.TxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnregisterOperatorVotingPowerProvider", ctx, addr)
	ret0, _ := ret[0].(entity.TxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnregisterOperatorVotingPowerProvider indicates an expected call of UnregisterOperatorVotingPowerProvider.
func (mr *MockIEvmClientMockRecorder) UnregisterOperatorVotingPowerProvider(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterOperatorVotingPowerProvider", reflect.TypeOf((*MockIEvmClient)(nil).UnregisterOperatorVotingPowerProvider), ctx, addr)
}

// VerifyQuorumSig mocks base method.
func (m *MockIEvmClient) VerifyQuorumSig(ctx context.Context, addr entity.CrossChainAddress, epoch entity.Epoch, message []byte, keyTag entity.KeyTag, threshold *big.Int, proof []byte) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyQuorumSig", ctx, addr, epoch, message, keyTag, threshold, proof)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyQuorumSig indicates an expected call of VerifyQuorumSig.
func (mr *MockIEvmClientMockRecorder) VerifyQuorumSig(ctx, addr, epoch, message, keyTag, threshold, proof any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyQuorumSig", reflect.TypeOf((*MockIEvmClient)(nil).VerifyQuorumSig), ctx, addr, epoch, message, keyTag, threshold, proof)
}
