// Code generated by MockGen. DO NOT EDIT.
// Source: aggregator_app.go
//
// Generated by this command:
//
//	mockgen -source=aggregator_app.go -destination=mocks/aggregator_app.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entity "middleware-offchain/core/entity"
	reflect "reflect"
	time "time"

	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// Mockrepository is a mock of repository interface.
type Mockrepository struct {
	ctrl     *gomock.Controller
	recorder *MockrepositoryMockRecorder
	isgomock struct{}
}

// MockrepositoryMockRecorder is the mock recorder for Mockrepository.
type MockrepositoryMockRecorder struct {
	mock *Mockrepository
}

// NewMockrepository creates a new mock instance.
func NewMockrepository(ctrl *gomock.Controller) *Mockrepository {
	mock := &Mockrepository{ctrl: ctrl}
	mock.recorder = &MockrepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepository) EXPECT() *MockrepositoryMockRecorder {
	return m.recorder
}

// GetAllSignatures mocks base method.
func (m *Mockrepository) GetAllSignatures(ctx context.Context, reqHash common.Hash) ([]entity.SignatureExtended, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSignatures", ctx, reqHash)
	ret0, _ := ret[0].([]entity.SignatureExtended)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSignatures indicates an expected call of GetAllSignatures.
func (mr *MockrepositoryMockRecorder) GetAllSignatures(ctx, reqHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSignatures", reflect.TypeOf((*Mockrepository)(nil).GetAllSignatures), ctx, reqHash)
}

// GetConfigByEpoch mocks base method.
func (m *Mockrepository) GetConfigByEpoch(ctx context.Context, epoch uint64) (entity.NetworkConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigByEpoch", ctx, epoch)
	ret0, _ := ret[0].(entity.NetworkConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigByEpoch indicates an expected call of GetConfigByEpoch.
func (mr *MockrepositoryMockRecorder) GetConfigByEpoch(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigByEpoch", reflect.TypeOf((*Mockrepository)(nil).GetConfigByEpoch), ctx, epoch)
}

// GetValidatorSetByEpoch mocks base method.
func (m *Mockrepository) GetValidatorSetByEpoch(ctx context.Context, epoch uint64) (entity.ValidatorSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidatorSetByEpoch", ctx, epoch)
	ret0, _ := ret[0].(entity.ValidatorSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidatorSetByEpoch indicates an expected call of GetValidatorSetByEpoch.
func (mr *MockrepositoryMockRecorder) GetValidatorSetByEpoch(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidatorSetByEpoch", reflect.TypeOf((*Mockrepository)(nil).GetValidatorSetByEpoch), ctx, epoch)
}

// SaveSignature mocks base method.
func (m *Mockrepository) SaveSignature(ctx context.Context, reqHash common.Hash, key []byte, sig entity.SignatureExtended) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSignature", ctx, reqHash, key, sig)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSignature indicates an expected call of SaveSignature.
func (mr *MockrepositoryMockRecorder) SaveSignature(ctx, reqHash, key, sig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSignature", reflect.TypeOf((*Mockrepository)(nil).SaveSignature), ctx, reqHash, key, sig)
}

// Mockp2pClient is a mock of p2pClient interface.
type Mockp2pClient struct {
	ctrl     *gomock.Controller
	recorder *Mockp2pClientMockRecorder
	isgomock struct{}
}

// Mockp2pClientMockRecorder is the mock recorder for Mockp2pClient.
type Mockp2pClientMockRecorder struct {
	mock *Mockp2pClient
}

// NewMockp2pClient creates a new mock instance.
func NewMockp2pClient(ctrl *gomock.Controller) *Mockp2pClient {
	mock := &Mockp2pClient{ctrl: ctrl}
	mock.recorder = &Mockp2pClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockp2pClient) EXPECT() *Mockp2pClientMockRecorder {
	return m.recorder
}

// BroadcastSignatureAggregatedMessage mocks base method.
func (m *Mockp2pClient) BroadcastSignatureAggregatedMessage(ctx context.Context, msg entity.AggregatedSignatureMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BroadcastSignatureAggregatedMessage", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// BroadcastSignatureAggregatedMessage indicates an expected call of BroadcastSignatureAggregatedMessage.
func (mr *Mockp2pClientMockRecorder) BroadcastSignatureAggregatedMessage(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastSignatureAggregatedMessage", reflect.TypeOf((*Mockp2pClient)(nil).BroadcastSignatureAggregatedMessage), ctx, msg)
}

// Mockaggregator is a mock of aggregator interface.
type Mockaggregator struct {
	ctrl     *gomock.Controller
	recorder *MockaggregatorMockRecorder
	isgomock struct{}
}

// MockaggregatorMockRecorder is the mock recorder for Mockaggregator.
type MockaggregatorMockRecorder struct {
	mock *Mockaggregator
}

// NewMockaggregator creates a new mock instance.
func NewMockaggregator(ctrl *gomock.Controller) *Mockaggregator {
	mock := &Mockaggregator{ctrl: ctrl}
	mock.recorder = &MockaggregatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockaggregator) EXPECT() *MockaggregatorMockRecorder {
	return m.recorder
}

// Aggregate mocks base method.
func (m *Mockaggregator) Aggregate(valset entity.ValidatorSet, keyTag entity.KeyTag, verificationType entity.VerificationType, messageHash []byte, signatures []entity.SignatureExtended) (entity.AggregationProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Aggregate", valset, keyTag, verificationType, messageHash, signatures)
	ret0, _ := ret[0].(entity.AggregationProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Aggregate indicates an expected call of Aggregate.
func (mr *MockaggregatorMockRecorder) Aggregate(valset, keyTag, verificationType, messageHash, signatures any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Aggregate", reflect.TypeOf((*Mockaggregator)(nil).Aggregate), valset, keyTag, verificationType, messageHash, signatures)
}

// Mockmetrics is a mock of metrics interface.
type Mockmetrics struct {
	ctrl     *gomock.Controller
	recorder *MockmetricsMockRecorder
	isgomock struct{}
}

// MockmetricsMockRecorder is the mock recorder for Mockmetrics.
type MockmetricsMockRecorder struct {
	mock *Mockmetrics
}

// NewMockmetrics creates a new mock instance.
func NewMockmetrics(ctrl *gomock.Controller) *Mockmetrics {
	mock := &Mockmetrics{ctrl: ctrl}
	mock.recorder = &MockmetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockmetrics) EXPECT() *MockmetricsMockRecorder {
	return m.recorder
}

// ObserveAppAggregateDuration mocks base method.
func (m *Mockmetrics) ObserveAppAggregateDuration(d time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveAppAggregateDuration", d)
}

// ObserveAppAggregateDuration indicates an expected call of ObserveAppAggregateDuration.
func (mr *MockmetricsMockRecorder) ObserveAppAggregateDuration(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveAppAggregateDuration", reflect.TypeOf((*Mockmetrics)(nil).ObserveAppAggregateDuration), d)
}

// ObserveOnlyAggregateDuration mocks base method.
func (m *Mockmetrics) ObserveOnlyAggregateDuration(d time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveOnlyAggregateDuration", d)
}

// ObserveOnlyAggregateDuration indicates an expected call of ObserveOnlyAggregateDuration.
func (mr *MockmetricsMockRecorder) ObserveOnlyAggregateDuration(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveOnlyAggregateDuration", reflect.TypeOf((*Mockmetrics)(nil).ObserveOnlyAggregateDuration), d)
}
