// Code generated by MockGen. DO NOT EDIT.
// Source: aggregator_app.go
//
// Generated by this command:
//
//	mockgen -source=aggregator_app.go -destination=mocks/aggregator_app.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entity "middleware-offchain/core/entity"
	entity0 "middleware-offchain/internal/entity"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// Mockrepository is a mock of repository interface.
type Mockrepository struct {
	ctrl     *gomock.Controller
	recorder *MockrepositoryMockRecorder
	isgomock struct{}
}

// MockrepositoryMockRecorder is the mock recorder for Mockrepository.
type MockrepositoryMockRecorder struct {
	mock *Mockrepository
}

// NewMockrepository creates a new mock instance.
func NewMockrepository(ctrl *gomock.Controller) *Mockrepository {
	mock := &Mockrepository{ctrl: ctrl}
	mock.recorder = &MockrepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepository) EXPECT() *MockrepositoryMockRecorder {
	return m.recorder
}

// GetAllSignatures mocks base method.
func (m *Mockrepository) GetAllSignatures(ctx context.Context, reqHash common.Hash) ([]entity.Signature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSignatures", ctx, reqHash)
	ret0, _ := ret[0].([]entity.Signature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSignatures indicates an expected call of GetAllSignatures.
func (mr *MockrepositoryMockRecorder) GetAllSignatures(ctx, reqHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSignatures", reflect.TypeOf((*Mockrepository)(nil).GetAllSignatures), ctx, reqHash)
}

// GetConfigByEpoch mocks base method.
func (m *Mockrepository) GetConfigByEpoch(ctx context.Context, epoch uint64) (entity.NetworkConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigByEpoch", ctx, epoch)
	ret0, _ := ret[0].(entity.NetworkConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigByEpoch indicates an expected call of GetConfigByEpoch.
func (mr *MockrepositoryMockRecorder) GetConfigByEpoch(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigByEpoch", reflect.TypeOf((*Mockrepository)(nil).GetConfigByEpoch), ctx, epoch)
}

// GetValsetByEpoch mocks base method.
func (m *Mockrepository) GetValsetByEpoch(ctx context.Context, epoch uint64) (entity.ValidatorSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValsetByEpoch", ctx, epoch)
	ret0, _ := ret[0].(entity.ValidatorSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValsetByEpoch indicates an expected call of GetValsetByEpoch.
func (mr *MockrepositoryMockRecorder) GetValsetByEpoch(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValsetByEpoch", reflect.TypeOf((*Mockrepository)(nil).GetValsetByEpoch), ctx, epoch)
}

// SaveSignature mocks base method.
func (m *Mockrepository) SaveSignature(ctx context.Context, reqHash common.Hash, key []byte, sig entity.Signature) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSignature", ctx, reqHash, key, sig)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSignature indicates an expected call of SaveSignature.
func (mr *MockrepositoryMockRecorder) SaveSignature(ctx, reqHash, key, sig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSignature", reflect.TypeOf((*Mockrepository)(nil).SaveSignature), ctx, reqHash, key, sig)
}

// Mockp2pClient is a mock of p2pClient interface.
type Mockp2pClient struct {
	ctrl     *gomock.Controller
	recorder *Mockp2pClientMockRecorder
	isgomock struct{}
}

// Mockp2pClientMockRecorder is the mock recorder for Mockp2pClient.
type Mockp2pClientMockRecorder struct {
	mock *Mockp2pClient
}

// NewMockp2pClient creates a new mock instance.
func NewMockp2pClient(ctrl *gomock.Controller) *Mockp2pClient {
	mock := &Mockp2pClient{ctrl: ctrl}
	mock.recorder = &Mockp2pClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockp2pClient) EXPECT() *Mockp2pClientMockRecorder {
	return m.recorder
}

// BroadcastSignatureAggregatedMessage mocks base method.
func (m *Mockp2pClient) BroadcastSignatureAggregatedMessage(ctx context.Context, msg entity.AggregatedSignatureMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BroadcastSignatureAggregatedMessage", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// BroadcastSignatureAggregatedMessage indicates an expected call of BroadcastSignatureAggregatedMessage.
func (mr *Mockp2pClientMockRecorder) BroadcastSignatureAggregatedMessage(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastSignatureAggregatedMessage", reflect.TypeOf((*Mockp2pClient)(nil).BroadcastSignatureAggregatedMessage), ctx, msg)
}

// SetSignatureHashMessageHandler mocks base method.
func (m *Mockp2pClient) SetSignatureHashMessageHandler(mh func(context.Context, entity0.SenderInfo, entity.SignatureMessage) error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSignatureHashMessageHandler", mh)
}

// SetSignatureHashMessageHandler indicates an expected call of SetSignatureHashMessageHandler.
func (mr *Mockp2pClientMockRecorder) SetSignatureHashMessageHandler(mh any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSignatureHashMessageHandler", reflect.TypeOf((*Mockp2pClient)(nil).SetSignatureHashMessageHandler), mh)
}

// Mockaggregator is a mock of aggregator interface.
type Mockaggregator struct {
	ctrl     *gomock.Controller
	recorder *MockaggregatorMockRecorder
	isgomock struct{}
}

// MockaggregatorMockRecorder is the mock recorder for Mockaggregator.
type MockaggregatorMockRecorder struct {
	mock *Mockaggregator
}

// NewMockaggregator creates a new mock instance.
func NewMockaggregator(ctrl *gomock.Controller) *Mockaggregator {
	mock := &Mockaggregator{ctrl: ctrl}
	mock.recorder = &MockaggregatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockaggregator) EXPECT() *MockaggregatorMockRecorder {
	return m.recorder
}

// Aggregate mocks base method.
func (m *Mockaggregator) Aggregate(valset entity.ValidatorSet, keyTag entity.KeyTag, verificationType entity.VerificationType, messageHash []byte, signatures []entity.Signature) (entity.AggregationProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Aggregate", valset, keyTag, verificationType, messageHash, signatures)
	ret0, _ := ret[0].(entity.AggregationProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Aggregate indicates an expected call of Aggregate.
func (mr *MockaggregatorMockRecorder) Aggregate(valset, keyTag, verificationType, messageHash, signatures any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Aggregate", reflect.TypeOf((*Mockaggregator)(nil).Aggregate), valset, keyTag, verificationType, messageHash, signatures)
}

// Mockverifier is a mock of verifier interface.
type Mockverifier struct {
	ctrl     *gomock.Controller
	recorder *MockverifierMockRecorder
	isgomock struct{}
}

// MockverifierMockRecorder is the mock recorder for Mockverifier.
type MockverifierMockRecorder struct {
	mock *Mockverifier
}

// NewMockverifier creates a new mock instance.
func NewMockverifier(ctrl *gomock.Controller) *Mockverifier {
	mock := &Mockverifier{ctrl: ctrl}
	mock.recorder = &MockverifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockverifier) EXPECT() *MockverifierMockRecorder {
	return m.recorder
}

// Verify mocks base method.
func (m *Mockverifier) Verify(keyTag entity.KeyTag, signature entity.Signature) ([]byte, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", keyTag, signature)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Verify indicates an expected call of Verify.
func (mr *MockverifierMockRecorder) Verify(keyTag, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*Mockverifier)(nil).Verify), keyTag, signature)
}
