// Code generated by MockGen. DO NOT EDIT.
// Source: valset_deriver.go
//
// Generated by this command:
//
//	mockgen -source=valset_deriver.go -destination=mocks/deriver.go -package=mocks -mock_names=evmClient=MockEvmClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	entity "github.com/symbioticfi/relay/symbiotic/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockEvmClient is a mock of evmClient interface.
type MockEvmClient struct {
	ctrl     *gomock.Controller
	recorder *MockEvmClientMockRecorder
	isgomock struct{}
}

// MockEvmClientMockRecorder is the mock recorder for MockEvmClient.
type MockEvmClientMockRecorder struct {
	mock *MockEvmClient
}

// NewMockEvmClient creates a new mock instance.
func NewMockEvmClient(ctrl *gomock.Controller) *MockEvmClient {
	mock := &MockEvmClient{ctrl: ctrl}
	mock.recorder = &MockEvmClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEvmClient) EXPECT() *MockEvmClientMockRecorder {
	return m.recorder
}

// GetConfig mocks base method.
func (m *MockEvmClient) GetConfig(ctx context.Context, timestamp entity.Timestamp, epoch entity.Epoch) (entity.NetworkConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", ctx, timestamp, epoch)
	ret0, _ := ret[0].(entity.NetworkConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockEvmClientMockRecorder) GetConfig(ctx, timestamp, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockEvmClient)(nil).GetConfig), ctx, timestamp, epoch)
}

// GetCurrentEpoch mocks base method.
func (m *MockEvmClient) GetCurrentEpoch(ctx context.Context) (entity.Epoch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentEpoch", ctx)
	ret0, _ := ret[0].(entity.Epoch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentEpoch indicates an expected call of GetCurrentEpoch.
func (mr *MockEvmClientMockRecorder) GetCurrentEpoch(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentEpoch", reflect.TypeOf((*MockEvmClient)(nil).GetCurrentEpoch), ctx)
}

// GetEip712Domain mocks base method.
func (m *MockEvmClient) GetEip712Domain(ctx context.Context, addr entity.CrossChainAddress) (entity.Eip712Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEip712Domain", ctx, addr)
	ret0, _ := ret[0].(entity.Eip712Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEip712Domain indicates an expected call of GetEip712Domain.
func (mr *MockEvmClientMockRecorder) GetEip712Domain(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEip712Domain", reflect.TypeOf((*MockEvmClient)(nil).GetEip712Domain), ctx, addr)
}

// GetEpochStart mocks base method.
func (m *MockEvmClient) GetEpochStart(ctx context.Context, epoch entity.Epoch) (entity.Timestamp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpochStart", ctx, epoch)
	ret0, _ := ret[0].(entity.Timestamp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEpochStart indicates an expected call of GetEpochStart.
func (mr *MockEvmClientMockRecorder) GetEpochStart(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpochStart", reflect.TypeOf((*MockEvmClient)(nil).GetEpochStart), ctx, epoch)
}

// GetHeaderHash mocks base method.
func (m *MockEvmClient) GetHeaderHash(ctx context.Context, addr entity.CrossChainAddress) (common.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeaderHash", ctx, addr)
	ret0, _ := ret[0].(common.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeaderHash indicates an expected call of GetHeaderHash.
func (mr *MockEvmClientMockRecorder) GetHeaderHash(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeaderHash", reflect.TypeOf((*MockEvmClient)(nil).GetHeaderHash), ctx, addr)
}

// GetHeaderHashAt mocks base method.
func (m *MockEvmClient) GetHeaderHashAt(ctx context.Context, addr entity.CrossChainAddress, epoch entity.Epoch) (common.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeaderHashAt", ctx, addr, epoch)
	ret0, _ := ret[0].(common.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeaderHashAt indicates an expected call of GetHeaderHashAt.
func (mr *MockEvmClientMockRecorder) GetHeaderHashAt(ctx, addr, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeaderHashAt", reflect.TypeOf((*MockEvmClient)(nil).GetHeaderHashAt), ctx, addr, epoch)
}

// GetKeys mocks base method.
func (m *MockEvmClient) GetKeys(ctx context.Context, address entity.CrossChainAddress, timestamp entity.Timestamp) ([]entity.OperatorWithKeys, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeys", ctx, address, timestamp)
	ret0, _ := ret[0].([]entity.OperatorWithKeys)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeys indicates an expected call of GetKeys.
func (mr *MockEvmClientMockRecorder) GetKeys(ctx, address, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeys", reflect.TypeOf((*MockEvmClient)(nil).GetKeys), ctx, address, timestamp)
}

// GetLastCommittedHeaderEpoch mocks base method.
func (m *MockEvmClient) GetLastCommittedHeaderEpoch(ctx context.Context, addr entity.CrossChainAddress, opts ...entity.EVMOption) (entity.Epoch, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, addr}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLastCommittedHeaderEpoch", varargs...)
	ret0, _ := ret[0].(entity.Epoch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastCommittedHeaderEpoch indicates an expected call of GetLastCommittedHeaderEpoch.
func (mr *MockEvmClientMockRecorder) GetLastCommittedHeaderEpoch(ctx, addr any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, addr}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastCommittedHeaderEpoch", reflect.TypeOf((*MockEvmClient)(nil).GetLastCommittedHeaderEpoch), varargs...)
}

// GetNetworkAddress mocks base method.
func (m *MockEvmClient) GetNetworkAddress(ctx context.Context) (common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkAddress", ctx)
	ret0, _ := ret[0].(common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkAddress indicates an expected call of GetNetworkAddress.
func (mr *MockEvmClientMockRecorder) GetNetworkAddress(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkAddress", reflect.TypeOf((*MockEvmClient)(nil).GetNetworkAddress), ctx)
}

// GetOperators mocks base method.
func (m *MockEvmClient) GetOperators(ctx context.Context, address entity.CrossChainAddress, timestamp entity.Timestamp) ([]common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperators", ctx, address, timestamp)
	ret0, _ := ret[0].([]common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOperators indicates an expected call of GetOperators.
func (mr *MockEvmClientMockRecorder) GetOperators(ctx, address, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperators", reflect.TypeOf((*MockEvmClient)(nil).GetOperators), ctx, address, timestamp)
}

// GetSubnetwork mocks base method.
func (m *MockEvmClient) GetSubnetwork(ctx context.Context) (common.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubnetwork", ctx)
	ret0, _ := ret[0].(common.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubnetwork indicates an expected call of GetSubnetwork.
func (mr *MockEvmClientMockRecorder) GetSubnetwork(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubnetwork", reflect.TypeOf((*MockEvmClient)(nil).GetSubnetwork), ctx)
}

// GetVotingPowers mocks base method.
func (m *MockEvmClient) GetVotingPowers(ctx context.Context, address entity.CrossChainAddress, timestamp entity.Timestamp) ([]entity.OperatorVotingPower, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVotingPowers", ctx, address, timestamp)
	ret0, _ := ret[0].([]entity.OperatorVotingPower)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVotingPowers indicates an expected call of GetVotingPowers.
func (mr *MockEvmClientMockRecorder) GetVotingPowers(ctx, address, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVotingPowers", reflect.TypeOf((*MockEvmClient)(nil).GetVotingPowers), ctx, address, timestamp)
}

// IsValsetHeaderCommittedAt mocks base method.
func (m *MockEvmClient) IsValsetHeaderCommittedAt(ctx context.Context, addr entity.CrossChainAddress, epoch entity.Epoch, opts ...entity.EVMOption) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, addr, epoch}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IsValsetHeaderCommittedAt", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsValsetHeaderCommittedAt indicates an expected call of IsValsetHeaderCommittedAt.
func (mr *MockEvmClientMockRecorder) IsValsetHeaderCommittedAt(ctx, addr, epoch any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, addr, epoch}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValsetHeaderCommittedAt", reflect.TypeOf((*MockEvmClient)(nil).IsValsetHeaderCommittedAt), varargs...)
}

// MockexternalVotingPowerClient is a mock of externalVotingPowerClient interface.
type MockexternalVotingPowerClient struct {
	ctrl     *gomock.Controller
	recorder *MockexternalVotingPowerClientMockRecorder
	isgomock struct{}
}

// MockexternalVotingPowerClientMockRecorder is the mock recorder for MockexternalVotingPowerClient.
type MockexternalVotingPowerClientMockRecorder struct {
	mock *MockexternalVotingPowerClient
}

// NewMockexternalVotingPowerClient creates a new mock instance.
func NewMockexternalVotingPowerClient(ctrl *gomock.Controller) *MockexternalVotingPowerClient {
	mock := &MockexternalVotingPowerClient{ctrl: ctrl}
	mock.recorder = &MockexternalVotingPowerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockexternalVotingPowerClient) EXPECT() *MockexternalVotingPowerClientMockRecorder {
	return m.recorder
}

// GetVotingPowers mocks base method.
func (m *MockexternalVotingPowerClient) GetVotingPowers(ctx context.Context, address entity.CrossChainAddress, timestamp entity.Timestamp) ([]entity.OperatorVotingPower, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVotingPowers", ctx, address, timestamp)
	ret0, _ := ret[0].([]entity.OperatorVotingPower)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVotingPowers indicates an expected call of GetVotingPowers.
func (mr *MockexternalVotingPowerClientMockRecorder) GetVotingPowers(ctx, address, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVotingPowers", reflect.TypeOf((*MockexternalVotingPowerClient)(nil).GetVotingPowers), ctx, address, timestamp)
}
