// Code generated by MockGen. DO NOT EDIT.
// Source: signature_processor.go
//
// Generated by this command:
//
//	mockgen -source=signature_processor.go -destination=mocks/signature_processor.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	entity "github.com/symbioticfi/relay/core/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// DoUpdateInTx mocks base method.
func (m *MockRepository) DoUpdateInTx(ctx context.Context, f func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoUpdateInTx", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// DoUpdateInTx indicates an expected call of DoUpdateInTx.
func (mr *MockRepositoryMockRecorder) DoUpdateInTx(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoUpdateInTx", reflect.TypeOf((*MockRepository)(nil).DoUpdateInTx), ctx, f)
}

// GetSignatureMap mocks base method.
func (m *MockRepository) GetSignatureMap(ctx context.Context, reqHash common.Hash) (entity.SignatureMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSignatureMap", ctx, reqHash)
	ret0, _ := ret[0].(entity.SignatureMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSignatureMap indicates an expected call of GetSignatureMap.
func (mr *MockRepositoryMockRecorder) GetSignatureMap(ctx, reqHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSignatureMap", reflect.TypeOf((*MockRepository)(nil).GetSignatureMap), ctx, reqHash)
}

// SaveSignature mocks base method.
func (m *MockRepository) SaveSignature(ctx context.Context, reqHash common.Hash, key entity.RawPublicKey, sig entity.SignatureExtended) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSignature", ctx, reqHash, key, sig)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSignature indicates an expected call of SaveSignature.
func (mr *MockRepositoryMockRecorder) SaveSignature(ctx, reqHash, key, sig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSignature", reflect.TypeOf((*MockRepository)(nil).SaveSignature), ctx, reqHash, key, sig)
}

// SaveSignatureRequest mocks base method.
func (m *MockRepository) SaveSignatureRequest(ctx context.Context, req entity.SignatureRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSignatureRequest", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSignatureRequest indicates an expected call of SaveSignatureRequest.
func (mr *MockRepositoryMockRecorder) SaveSignatureRequest(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSignatureRequest", reflect.TypeOf((*MockRepository)(nil).SaveSignatureRequest), ctx, req)
}

// UpdateSignatureMap mocks base method.
func (m *MockRepository) UpdateSignatureMap(ctx context.Context, vm entity.SignatureMap) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSignatureMap", ctx, vm)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSignatureMap indicates an expected call of UpdateSignatureMap.
func (mr *MockRepositoryMockRecorder) UpdateSignatureMap(ctx, vm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSignatureMap", reflect.TypeOf((*MockRepository)(nil).UpdateSignatureMap), ctx, vm)
}

// MockSignatureProcessor is a mock of SignatureProcessor interface.
type MockSignatureProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockSignatureProcessorMockRecorder
	isgomock struct{}
}

// MockSignatureProcessorMockRecorder is the mock recorder for MockSignatureProcessor.
type MockSignatureProcessorMockRecorder struct {
	mock *MockSignatureProcessor
}

// NewMockSignatureProcessor creates a new mock instance.
func NewMockSignatureProcessor(ctrl *gomock.Controller) *MockSignatureProcessor {
	mock := &MockSignatureProcessor{ctrl: ctrl}
	mock.recorder = &MockSignatureProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignatureProcessor) EXPECT() *MockSignatureProcessorMockRecorder {
	return m.recorder
}

// ProcessSignature mocks base method.
func (m *MockSignatureProcessor) ProcessSignature(ctx context.Context, param entity.SaveSignatureParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessSignature", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessSignature indicates an expected call of ProcessSignature.
func (mr *MockSignatureProcessorMockRecorder) ProcessSignature(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessSignature", reflect.TypeOf((*MockSignatureProcessor)(nil).ProcessSignature), ctx, param)
}
