// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/badger.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Validator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      []byte                 `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	VotingPower   string                 `protobuf:"bytes,2,opt,name=voting_power,json=votingPower,proto3" json:"voting_power,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	ActiveIndex   uint32                 `protobuf:"varint,4,opt,name=active_index,json=activeIndex,proto3" json:"active_index,omitempty"`
	Keys          []*ValidatorKey        `protobuf:"bytes,5,rep,name=keys,proto3" json:"keys,omitempty"`
	Vaults        []*ValidatorVault      `protobuf:"bytes,6,rep,name=vaults,proto3" json:"vaults,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Validator) Reset() {
	*x = Validator{}
	mi := &file_v1_badger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Validator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validator) ProtoMessage() {}

func (x *Validator) ProtoReflect() protoreflect.Message {
	mi := &file_v1_badger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validator.ProtoReflect.Descriptor instead.
func (*Validator) Descriptor() ([]byte, []int) {
	return file_v1_badger_proto_rawDescGZIP(), []int{0}
}

func (x *Validator) GetOperator() []byte {
	if x != nil {
		return x.Operator
	}
	return nil
}

func (x *Validator) GetVotingPower() string {
	if x != nil {
		return x.VotingPower
	}
	return ""
}

func (x *Validator) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Validator) GetActiveIndex() uint32 {
	if x != nil {
		return x.ActiveIndex
	}
	return 0
}

func (x *Validator) GetKeys() []*ValidatorKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *Validator) GetVaults() []*ValidatorVault {
	if x != nil {
		return x.Vaults
	}
	return nil
}

type ValidatorKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           uint32                 `protobuf:"varint,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatorKey) Reset() {
	*x = ValidatorKey{}
	mi := &file_v1_badger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorKey) ProtoMessage() {}

func (x *ValidatorKey) ProtoReflect() protoreflect.Message {
	mi := &file_v1_badger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorKey.ProtoReflect.Descriptor instead.
func (*ValidatorKey) Descriptor() ([]byte, []int) {
	return file_v1_badger_proto_rawDescGZIP(), []int{1}
}

func (x *ValidatorKey) GetTag() uint32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *ValidatorKey) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ValidatorVault struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       uint64                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Vault         []byte                 `protobuf:"bytes,2,opt,name=vault,proto3" json:"vault,omitempty"`
	VotingPower   string                 `protobuf:"bytes,3,opt,name=voting_power,json=votingPower,proto3" json:"voting_power,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatorVault) Reset() {
	*x = ValidatorVault{}
	mi := &file_v1_badger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorVault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorVault) ProtoMessage() {}

func (x *ValidatorVault) ProtoReflect() protoreflect.Message {
	mi := &file_v1_badger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorVault.ProtoReflect.Descriptor instead.
func (*ValidatorVault) Descriptor() ([]byte, []int) {
	return file_v1_badger_proto_rawDescGZIP(), []int{2}
}

func (x *ValidatorVault) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *ValidatorVault) GetVault() []byte {
	if x != nil {
		return x.Vault
	}
	return nil
}

func (x *ValidatorVault) GetVotingPower() string {
	if x != nil {
		return x.VotingPower
	}
	return ""
}

type ValidatorSetHeader struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Version            uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	RequiredKeyTag     uint32                 `protobuf:"varint,2,opt,name=required_key_tag,json=requiredKeyTag,proto3" json:"required_key_tag,omitempty"`
	Epoch              uint64                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	CaptureTimestamp   uint64                 `protobuf:"varint,4,opt,name=capture_timestamp,json=captureTimestamp,proto3" json:"capture_timestamp,omitempty"`
	QuorumThreshold    string                 `protobuf:"bytes,5,opt,name=quorum_threshold,json=quorumThreshold,proto3" json:"quorum_threshold,omitempty"`
	TotalVotingPower   string                 `protobuf:"bytes,6,opt,name=total_voting_power,json=totalVotingPower,proto3" json:"total_voting_power,omitempty"`
	ValidatorsSszMroot []byte                 `protobuf:"bytes,7,opt,name=validators_ssz_mroot,json=validatorsSszMroot,proto3" json:"validators_ssz_mroot,omitempty"`
	AggregatorIndices  []byte                 `protobuf:"bytes,8,opt,name=aggregator_indices,json=aggregatorIndices,proto3" json:"aggregator_indices,omitempty"`
	CommitterIndices   []byte                 `protobuf:"bytes,9,opt,name=committer_indices,json=committerIndices,proto3" json:"committer_indices,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ValidatorSetHeader) Reset() {
	*x = ValidatorSetHeader{}
	mi := &file_v1_badger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorSetHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorSetHeader) ProtoMessage() {}

func (x *ValidatorSetHeader) ProtoReflect() protoreflect.Message {
	mi := &file_v1_badger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorSetHeader.ProtoReflect.Descriptor instead.
func (*ValidatorSetHeader) Descriptor() ([]byte, []int) {
	return file_v1_badger_proto_rawDescGZIP(), []int{3}
}

func (x *ValidatorSetHeader) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ValidatorSetHeader) GetRequiredKeyTag() uint32 {
	if x != nil {
		return x.RequiredKeyTag
	}
	return 0
}

func (x *ValidatorSetHeader) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ValidatorSetHeader) GetCaptureTimestamp() uint64 {
	if x != nil {
		return x.CaptureTimestamp
	}
	return 0
}

func (x *ValidatorSetHeader) GetQuorumThreshold() string {
	if x != nil {
		return x.QuorumThreshold
	}
	return ""
}

func (x *ValidatorSetHeader) GetTotalVotingPower() string {
	if x != nil {
		return x.TotalVotingPower
	}
	return ""
}

func (x *ValidatorSetHeader) GetValidatorsSszMroot() []byte {
	if x != nil {
		return x.ValidatorsSszMroot
	}
	return nil
}

func (x *ValidatorSetHeader) GetAggregatorIndices() []byte {
	if x != nil {
		return x.AggregatorIndices
	}
	return nil
}

func (x *ValidatorSetHeader) GetCommitterIndices() []byte {
	if x != nil {
		return x.CommitterIndices
	}
	return nil
}

type ValidatorSetMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      []byte                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Epoch          uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	ExtraData      []*ExtraData           `protobuf:"bytes,3,rep,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	CommitmentData []byte                 `protobuf:"bytes,4,opt,name=commitment_data,json=commitmentData,proto3" json:"commitment_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidatorSetMetadata) Reset() {
	*x = ValidatorSetMetadata{}
	mi := &file_v1_badger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorSetMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorSetMetadata) ProtoMessage() {}

func (x *ValidatorSetMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_v1_badger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorSetMetadata.ProtoReflect.Descriptor instead.
func (*ValidatorSetMetadata) Descriptor() ([]byte, []int) {
	return file_v1_badger_proto_rawDescGZIP(), []int{4}
}

func (x *ValidatorSetMetadata) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *ValidatorSetMetadata) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ValidatorSetMetadata) GetExtraData() []*ExtraData {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

func (x *ValidatorSetMetadata) GetCommitmentData() []byte {
	if x != nil {
		return x.CommitmentData
	}
	return nil
}

type ExtraData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtraData) Reset() {
	*x = ExtraData{}
	mi := &file_v1_badger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtraData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtraData) ProtoMessage() {}

func (x *ExtraData) ProtoReflect() protoreflect.Message {
	mi := &file_v1_badger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtraData.ProtoReflect.Descriptor instead.
func (*ExtraData) Descriptor() ([]byte, []int) {
	return file_v1_badger_proto_rawDescGZIP(), []int{5}
}

func (x *ExtraData) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ExtraData) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type AggregationProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageHash   []byte                 `protobuf:"bytes,1,opt,name=message_hash,json=messageHash,proto3" json:"message_hash,omitempty"`
	KeyTag        uint32                 `protobuf:"varint,2,opt,name=key_tag,json=keyTag,proto3" json:"key_tag,omitempty"`
	Epoch         uint64                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Proof         []byte                 `protobuf:"bytes,4,opt,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregationProof) Reset() {
	*x = AggregationProof{}
	mi := &file_v1_badger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregationProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregationProof) ProtoMessage() {}

func (x *AggregationProof) ProtoReflect() protoreflect.Message {
	mi := &file_v1_badger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregationProof.ProtoReflect.Descriptor instead.
func (*AggregationProof) Descriptor() ([]byte, []int) {
	return file_v1_badger_proto_rawDescGZIP(), []int{6}
}

func (x *AggregationProof) GetMessageHash() []byte {
	if x != nil {
		return x.MessageHash
	}
	return nil
}

func (x *AggregationProof) GetKeyTag() uint32 {
	if x != nil {
		return x.KeyTag
	}
	return 0
}

func (x *AggregationProof) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *AggregationProof) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

type Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageHash   []byte                 `protobuf:"bytes,1,opt,name=message_hash,json=messageHash,proto3" json:"message_hash,omitempty"`
	KeyTag        uint32                 `protobuf:"varint,2,opt,name=key_tag,json=keyTag,proto3" json:"key_tag,omitempty"`
	Epoch         uint64                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_v1_badger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_v1_badger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_v1_badger_proto_rawDescGZIP(), []int{7}
}

func (x *Signature) GetMessageHash() []byte {
	if x != nil {
		return x.MessageHash
	}
	return nil
}

func (x *Signature) GetKeyTag() uint32 {
	if x != nil {
		return x.KeyTag
	}
	return 0
}

func (x *Signature) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Signature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Signature) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type SignatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyTag        uint32                 `protobuf:"varint,1,opt,name=key_tag,json=keyTag,proto3" json:"key_tag,omitempty"`
	RequiredEpoch uint64                 `protobuf:"varint,2,opt,name=required_epoch,json=requiredEpoch,proto3" json:"required_epoch,omitempty"`
	Message       []byte                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignatureRequest) Reset() {
	*x = SignatureRequest{}
	mi := &file_v1_badger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureRequest) ProtoMessage() {}

func (x *SignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_badger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureRequest.ProtoReflect.Descriptor instead.
func (*SignatureRequest) Descriptor() ([]byte, []int) {
	return file_v1_badger_proto_rawDescGZIP(), []int{8}
}

func (x *SignatureRequest) GetKeyTag() uint32 {
	if x != nil {
		return x.KeyTag
	}
	return 0
}

func (x *SignatureRequest) GetRequiredEpoch() uint64 {
	if x != nil {
		return x.RequiredEpoch
	}
	return 0
}

func (x *SignatureRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type SignatureMap struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	RequestId              []byte                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Epoch                  uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	SignedValidatorsBitmap []byte                 `protobuf:"bytes,3,opt,name=signed_validators_bitmap,json=signedValidatorsBitmap,proto3" json:"signed_validators_bitmap,omitempty"`
	CurrentVotingPower     string                 `protobuf:"bytes,4,opt,name=current_voting_power,json=currentVotingPower,proto3" json:"current_voting_power,omitempty"`
	TotalValidators        uint32                 `protobuf:"varint,5,opt,name=total_validators,json=totalValidators,proto3" json:"total_validators,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SignatureMap) Reset() {
	*x = SignatureMap{}
	mi := &file_v1_badger_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureMap) ProtoMessage() {}

func (x *SignatureMap) ProtoReflect() protoreflect.Message {
	mi := &file_v1_badger_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureMap.ProtoReflect.Descriptor instead.
func (*SignatureMap) Descriptor() ([]byte, []int) {
	return file_v1_badger_proto_rawDescGZIP(), []int{9}
}

func (x *SignatureMap) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *SignatureMap) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *SignatureMap) GetSignedValidatorsBitmap() []byte {
	if x != nil {
		return x.SignedValidatorsBitmap
	}
	return nil
}

func (x *SignatureMap) GetCurrentVotingPower() string {
	if x != nil {
		return x.CurrentVotingPower
	}
	return ""
}

func (x *SignatureMap) GetTotalValidators() uint32 {
	if x != nil {
		return x.TotalValidators
	}
	return 0
}

type NetworkConfig struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	VotingPowerProviders    []*CrossChainAddress   `protobuf:"bytes,1,rep,name=voting_power_providers,json=votingPowerProviders,proto3" json:"voting_power_providers,omitempty"`
	KeysProvider            *CrossChainAddress     `protobuf:"bytes,2,opt,name=keys_provider,json=keysProvider,proto3" json:"keys_provider,omitempty"`
	Settlements             []*CrossChainAddress   `protobuf:"bytes,3,rep,name=settlements,proto3" json:"settlements,omitempty"`
	VerificationType        uint32                 `protobuf:"varint,4,opt,name=verification_type,json=verificationType,proto3" json:"verification_type,omitempty"`
	MaxVotingPower          string                 `protobuf:"bytes,5,opt,name=max_voting_power,json=maxVotingPower,proto3" json:"max_voting_power,omitempty"`
	MinInclusionVotingPower string                 `protobuf:"bytes,6,opt,name=min_inclusion_voting_power,json=minInclusionVotingPower,proto3" json:"min_inclusion_voting_power,omitempty"`
	MaxValidatorsCount      string                 `protobuf:"bytes,7,opt,name=max_validators_count,json=maxValidatorsCount,proto3" json:"max_validators_count,omitempty"`
	RequiredKeyTags         []uint32               `protobuf:"varint,8,rep,packed,name=required_key_tags,json=requiredKeyTags,proto3" json:"required_key_tags,omitempty"`
	RequiredHeaderKeyTag    uint32                 `protobuf:"varint,9,opt,name=required_header_key_tag,json=requiredHeaderKeyTag,proto3" json:"required_header_key_tag,omitempty"`
	QuorumThresholds        []*QuorumThreshold     `protobuf:"bytes,10,rep,name=quorum_thresholds,json=quorumThresholds,proto3" json:"quorum_thresholds,omitempty"`
	NumCommitters           uint64                 `protobuf:"varint,11,opt,name=num_committers,json=numCommitters,proto3" json:"num_committers,omitempty"`
	NumAggregators          uint64                 `protobuf:"varint,12,opt,name=num_aggregators,json=numAggregators,proto3" json:"num_aggregators,omitempty"`
	CommitterSlotDuration   uint64                 `protobuf:"varint,13,opt,name=committer_slot_duration,json=committerSlotDuration,proto3" json:"committer_slot_duration,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_v1_badger_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_badger_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_v1_badger_proto_rawDescGZIP(), []int{10}
}

func (x *NetworkConfig) GetVotingPowerProviders() []*CrossChainAddress {
	if x != nil {
		return x.VotingPowerProviders
	}
	return nil
}

func (x *NetworkConfig) GetKeysProvider() *CrossChainAddress {
	if x != nil {
		return x.KeysProvider
	}
	return nil
}

func (x *NetworkConfig) GetSettlements() []*CrossChainAddress {
	if x != nil {
		return x.Settlements
	}
	return nil
}

func (x *NetworkConfig) GetVerificationType() uint32 {
	if x != nil {
		return x.VerificationType
	}
	return 0
}

func (x *NetworkConfig) GetMaxVotingPower() string {
	if x != nil {
		return x.MaxVotingPower
	}
	return ""
}

func (x *NetworkConfig) GetMinInclusionVotingPower() string {
	if x != nil {
		return x.MinInclusionVotingPower
	}
	return ""
}

func (x *NetworkConfig) GetMaxValidatorsCount() string {
	if x != nil {
		return x.MaxValidatorsCount
	}
	return ""
}

func (x *NetworkConfig) GetRequiredKeyTags() []uint32 {
	if x != nil {
		return x.RequiredKeyTags
	}
	return nil
}

func (x *NetworkConfig) GetRequiredHeaderKeyTag() uint32 {
	if x != nil {
		return x.RequiredHeaderKeyTag
	}
	return 0
}

func (x *NetworkConfig) GetQuorumThresholds() []*QuorumThreshold {
	if x != nil {
		return x.QuorumThresholds
	}
	return nil
}

func (x *NetworkConfig) GetNumCommitters() uint64 {
	if x != nil {
		return x.NumCommitters
	}
	return 0
}

func (x *NetworkConfig) GetNumAggregators() uint64 {
	if x != nil {
		return x.NumAggregators
	}
	return 0
}

func (x *NetworkConfig) GetCommitterSlotDuration() uint64 {
	if x != nil {
		return x.CommitterSlotDuration
	}
	return 0
}

type CrossChainAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	ChainId       uint64                 `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrossChainAddress) Reset() {
	*x = CrossChainAddress{}
	mi := &file_v1_badger_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossChainAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossChainAddress) ProtoMessage() {}

func (x *CrossChainAddress) ProtoReflect() protoreflect.Message {
	mi := &file_v1_badger_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossChainAddress.ProtoReflect.Descriptor instead.
func (*CrossChainAddress) Descriptor() ([]byte, []int) {
	return file_v1_badger_proto_rawDescGZIP(), []int{11}
}

func (x *CrossChainAddress) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *CrossChainAddress) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

type QuorumThreshold struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	KeyTag          uint32                 `protobuf:"varint,1,opt,name=key_tag,json=keyTag,proto3" json:"key_tag,omitempty"`
	QuorumThreshold string                 `protobuf:"bytes,2,opt,name=quorum_threshold,json=quorumThreshold,proto3" json:"quorum_threshold,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QuorumThreshold) Reset() {
	*x = QuorumThreshold{}
	mi := &file_v1_badger_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuorumThreshold) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumThreshold) ProtoMessage() {}

func (x *QuorumThreshold) ProtoReflect() protoreflect.Message {
	mi := &file_v1_badger_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumThreshold.ProtoReflect.Descriptor instead.
func (*QuorumThreshold) Descriptor() ([]byte, []int) {
	return file_v1_badger_proto_rawDescGZIP(), []int{12}
}

func (x *QuorumThreshold) GetKeyTag() uint32 {
	if x != nil {
		return x.KeyTag
	}
	return 0
}

func (x *QuorumThreshold) GetQuorumThreshold() string {
	if x != nil {
		return x.QuorumThreshold
	}
	return ""
}

var File_v1_badger_proto protoreflect.FileDescriptor

const file_v1_badger_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/badger.proto\x12\tbadger.v1\"\xea\x01\n" +
	"\tValidator\x12\x1a\n" +
	"\boperator\x18\x01 \x01(\fR\boperator\x12!\n" +
	"\fvoting_power\x18\x02 \x01(\tR\vvotingPower\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\x12!\n" +
	"\factive_index\x18\x04 \x01(\rR\vactiveIndex\x12+\n" +
	"\x04keys\x18\x05 \x03(\v2\x17.badger.v1.ValidatorKeyR\x04keys\x121\n" +
	"\x06vaults\x18\x06 \x03(\v2\x19.badger.v1.ValidatorVaultR\x06vaults\":\n" +
	"\fValidatorKey\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\rR\x03tag\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"d\n" +
	"\x0eValidatorVault\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x04R\achainId\x12\x14\n" +
	"\x05vault\x18\x02 \x01(\fR\x05vault\x12!\n" +
	"\fvoting_power\x18\x03 \x01(\tR\vvotingPower\"\x82\x03\n" +
	"\x12ValidatorSetHeader\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12(\n" +
	"\x10required_key_tag\x18\x02 \x01(\rR\x0erequiredKeyTag\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x04R\x05epoch\x12+\n" +
	"\x11capture_timestamp\x18\x04 \x01(\x04R\x10captureTimestamp\x12)\n" +
	"\x10quorum_threshold\x18\x05 \x01(\tR\x0fquorumThreshold\x12,\n" +
	"\x12total_voting_power\x18\x06 \x01(\tR\x10totalVotingPower\x120\n" +
	"\x14validators_ssz_mroot\x18\a \x01(\fR\x12validatorsSszMroot\x12-\n" +
	"\x12aggregator_indices\x18\b \x01(\fR\x11aggregatorIndices\x12+\n" +
	"\x11committer_indices\x18\t \x01(\fR\x10committerIndices\"\xa9\x01\n" +
	"\x14ValidatorSetMetadata\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\fR\trequestId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x123\n" +
	"\n" +
	"extra_data\x18\x03 \x03(\v2\x14.badger.v1.ExtraDataR\textraData\x12'\n" +
	"\x0fcommitment_data\x18\x04 \x01(\fR\x0ecommitmentData\"3\n" +
	"\tExtraData\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"z\n" +
	"\x10AggregationProof\x12!\n" +
	"\fmessage_hash\x18\x01 \x01(\fR\vmessageHash\x12\x17\n" +
	"\akey_tag\x18\x02 \x01(\rR\x06keyTag\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x04R\x05epoch\x12\x14\n" +
	"\x05proof\x18\x04 \x01(\fR\x05proof\"\x9a\x01\n" +
	"\tSignature\x12!\n" +
	"\fmessage_hash\x18\x01 \x01(\fR\vmessageHash\x12\x17\n" +
	"\akey_tag\x18\x02 \x01(\rR\x06keyTag\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x04R\x05epoch\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x05 \x01(\fR\tpublicKey\"l\n" +
	"\x10SignatureRequest\x12\x17\n" +
	"\akey_tag\x18\x01 \x01(\rR\x06keyTag\x12%\n" +
	"\x0erequired_epoch\x18\x02 \x01(\x04R\rrequiredEpoch\x12\x18\n" +
	"\amessage\x18\x03 \x01(\fR\amessage\"\xda\x01\n" +
	"\fSignatureMap\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\fR\trequestId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x128\n" +
	"\x18signed_validators_bitmap\x18\x03 \x01(\fR\x16signedValidatorsBitmap\x120\n" +
	"\x14current_voting_power\x18\x04 \x01(\tR\x12currentVotingPower\x12)\n" +
	"\x10total_validators\x18\x05 \x01(\rR\x0ftotalValidators\"\xe0\x05\n" +
	"\rNetworkConfig\x12R\n" +
	"\x16voting_power_providers\x18\x01 \x03(\v2\x1c.badger.v1.CrossChainAddressR\x14votingPowerProviders\x12A\n" +
	"\rkeys_provider\x18\x02 \x01(\v2\x1c.badger.v1.CrossChainAddressR\fkeysProvider\x12>\n" +
	"\vsettlements\x18\x03 \x03(\v2\x1c.badger.v1.CrossChainAddressR\vsettlements\x12+\n" +
	"\x11verification_type\x18\x04 \x01(\rR\x10verificationType\x12(\n" +
	"\x10max_voting_power\x18\x05 \x01(\tR\x0emaxVotingPower\x12;\n" +
	"\x1amin_inclusion_voting_power\x18\x06 \x01(\tR\x17minInclusionVotingPower\x120\n" +
	"\x14max_validators_count\x18\a \x01(\tR\x12maxValidatorsCount\x12*\n" +
	"\x11required_key_tags\x18\b \x03(\rR\x0frequiredKeyTags\x125\n" +
	"\x17required_header_key_tag\x18\t \x01(\rR\x14requiredHeaderKeyTag\x12G\n" +
	"\x11quorum_thresholds\x18\n" +
	" \x03(\v2\x1a.badger.v1.QuorumThresholdR\x10quorumThresholds\x12%\n" +
	"\x0enum_committers\x18\v \x01(\x04R\rnumCommitters\x12'\n" +
	"\x0fnum_aggregators\x18\f \x01(\x04R\x0enumAggregators\x126\n" +
	"\x17committer_slot_duration\x18\r \x01(\x04R\x15committerSlotDuration\"H\n" +
	"\x11CrossChainAddress\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\x04R\achainId\"U\n" +
	"\x0fQuorumThreshold\x12\x17\n" +
	"\akey_tag\x18\x01 \x01(\rR\x06keyTag\x12)\n" +
	"\x10quorum_threshold\x18\x02 \x01(\tR\x0fquorumThresholdB\xaa\x01\n" +
	"\rcom.badger.v1B\vBadgerProtoP\x01ZGgithub.com/symbioticfi/relay/internal/client/repository/badger/proto/v1\xa2\x02\x03BXX\xaa\x02\tBadger.V1\xca\x02\tBadger\\V1\xe2\x02\x15Badger\\V1\\GPBMetadata\xea\x02\n" +
	"Badger::V1b\x06proto3"

var (
	file_v1_badger_proto_rawDescOnce sync.Once
	file_v1_badger_proto_rawDescData []byte
)

func file_v1_badger_proto_rawDescGZIP() []byte {
	file_v1_badger_proto_rawDescOnce.Do(func() {
		file_v1_badger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_badger_proto_rawDesc), len(file_v1_badger_proto_rawDesc)))
	})
	return file_v1_badger_proto_rawDescData
}

var file_v1_badger_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_v1_badger_proto_goTypes = []any{
	(*Validator)(nil),            // 0: badger.v1.Validator
	(*ValidatorKey)(nil),         // 1: badger.v1.ValidatorKey
	(*ValidatorVault)(nil),       // 2: badger.v1.ValidatorVault
	(*ValidatorSetHeader)(nil),   // 3: badger.v1.ValidatorSetHeader
	(*ValidatorSetMetadata)(nil), // 4: badger.v1.ValidatorSetMetadata
	(*ExtraData)(nil),            // 5: badger.v1.ExtraData
	(*AggregationProof)(nil),     // 6: badger.v1.AggregationProof
	(*Signature)(nil),            // 7: badger.v1.Signature
	(*SignatureRequest)(nil),     // 8: badger.v1.SignatureRequest
	(*SignatureMap)(nil),         // 9: badger.v1.SignatureMap
	(*NetworkConfig)(nil),        // 10: badger.v1.NetworkConfig
	(*CrossChainAddress)(nil),    // 11: badger.v1.CrossChainAddress
	(*QuorumThreshold)(nil),      // 12: badger.v1.QuorumThreshold
}
var file_v1_badger_proto_depIdxs = []int32{
	1,  // 0: badger.v1.Validator.keys:type_name -> badger.v1.ValidatorKey
	2,  // 1: badger.v1.Validator.vaults:type_name -> badger.v1.ValidatorVault
	5,  // 2: badger.v1.ValidatorSetMetadata.extra_data:type_name -> badger.v1.ExtraData
	11, // 3: badger.v1.NetworkConfig.voting_power_providers:type_name -> badger.v1.CrossChainAddress
	11, // 4: badger.v1.NetworkConfig.keys_provider:type_name -> badger.v1.CrossChainAddress
	11, // 5: badger.v1.NetworkConfig.settlements:type_name -> badger.v1.CrossChainAddress
	12, // 6: badger.v1.NetworkConfig.quorum_thresholds:type_name -> badger.v1.QuorumThreshold
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_v1_badger_proto_init() }
func file_v1_badger_proto_init() {
	if File_v1_badger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_badger_proto_rawDesc), len(file_v1_badger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_badger_proto_goTypes,
		DependencyIndexes: file_v1_badger_proto_depIdxs,
		MessageInfos:      file_v1_badger_proto_msgTypes,
	}.Build()
	File_v1_badger_proto = out.File
	file_v1_badger_proto_goTypes = nil
	file_v1_badger_proto_depIdxs = nil
}
