// Code generated by MockGen. DO NOT EDIT.
// Source: app.go
//
// Generated by this command:
//
//	mockgen -source=app.go -destination=mocks/app_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	entity "github.com/symbioticfi/relay/internal/entity"
	entity0 "github.com/symbioticfi/relay/symbiotic/entity"
	gomock "go.uber.org/mock/gomock"
)

// Mocksigner is a mock of signer interface.
type Mocksigner struct {
	ctrl     *gomock.Controller
	recorder *MocksignerMockRecorder
	isgomock struct{}
}

// MocksignerMockRecorder is the mock recorder for Mocksigner.
type MocksignerMockRecorder struct {
	mock *Mocksigner
}

// NewMocksigner creates a new mock instance.
func NewMocksigner(ctrl *gomock.Controller) *Mocksigner {
	mock := &Mocksigner{ctrl: ctrl}
	mock.recorder = &MocksignerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksigner) EXPECT() *MocksignerMockRecorder {
	return m.recorder
}

// RequestSignature mocks base method.
func (m *Mocksigner) RequestSignature(ctx context.Context, req entity0.SignatureRequest) (common.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestSignature", ctx, req)
	ret0, _ := ret[0].(common.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestSignature indicates an expected call of RequestSignature.
func (mr *MocksignerMockRecorder) RequestSignature(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestSignature", reflect.TypeOf((*Mocksigner)(nil).RequestSignature), ctx, req)
}

// Mockrepo is a mock of repo interface.
type Mockrepo struct {
	ctrl     *gomock.Controller
	recorder *MockrepoMockRecorder
	isgomock struct{}
}

// MockrepoMockRecorder is the mock recorder for Mockrepo.
type MockrepoMockRecorder struct {
	mock *Mockrepo
}

// NewMockrepo creates a new mock instance.
func NewMockrepo(ctrl *gomock.Controller) *Mockrepo {
	mock := &Mockrepo{ctrl: ctrl}
	mock.recorder = &MockrepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepo) EXPECT() *MockrepoMockRecorder {
	return m.recorder
}

// GetAggregationProof mocks base method.
func (m *Mockrepo) GetAggregationProof(ctx context.Context, requestID common.Hash) (entity0.AggregationProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAggregationProof", ctx, requestID)
	ret0, _ := ret[0].(entity0.AggregationProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAggregationProof indicates an expected call of GetAggregationProof.
func (mr *MockrepoMockRecorder) GetAggregationProof(ctx, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAggregationProof", reflect.TypeOf((*Mockrepo)(nil).GetAggregationProof), ctx, requestID)
}

// GetAggregationProofsByEpoch mocks base method.
func (m *Mockrepo) GetAggregationProofsByEpoch(ctx context.Context, epoch entity0.Epoch) ([]entity0.AggregationProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAggregationProofsByEpoch", ctx, epoch)
	ret0, _ := ret[0].([]entity0.AggregationProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAggregationProofsByEpoch indicates an expected call of GetAggregationProofsByEpoch.
func (mr *MockrepoMockRecorder) GetAggregationProofsByEpoch(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAggregationProofsByEpoch", reflect.TypeOf((*Mockrepo)(nil).GetAggregationProofsByEpoch), ctx, epoch)
}

// GetAggregationProofsStartingFromEpoch mocks base method.
func (m *Mockrepo) GetAggregationProofsStartingFromEpoch(ctx context.Context, epoch entity0.Epoch) ([]entity0.AggregationProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAggregationProofsStartingFromEpoch", ctx, epoch)
	ret0, _ := ret[0].([]entity0.AggregationProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAggregationProofsStartingFromEpoch indicates an expected call of GetAggregationProofsStartingFromEpoch.
func (mr *MockrepoMockRecorder) GetAggregationProofsStartingFromEpoch(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAggregationProofsStartingFromEpoch", reflect.TypeOf((*Mockrepo)(nil).GetAggregationProofsStartingFromEpoch), ctx, epoch)
}

// GetAllSignatures mocks base method.
func (m *Mockrepo) GetAllSignatures(ctx context.Context, requestID common.Hash) ([]entity0.Signature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSignatures", ctx, requestID)
	ret0, _ := ret[0].([]entity0.Signature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSignatures indicates an expected call of GetAllSignatures.
func (mr *MockrepoMockRecorder) GetAllSignatures(ctx, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSignatures", reflect.TypeOf((*Mockrepo)(nil).GetAllSignatures), ctx, requestID)
}

// GetLatestValidatorSetEpoch mocks base method.
func (m *Mockrepo) GetLatestValidatorSetEpoch(arg0 context.Context) (entity0.Epoch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestValidatorSetEpoch", arg0)
	ret0, _ := ret[0].(entity0.Epoch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestValidatorSetEpoch indicates an expected call of GetLatestValidatorSetEpoch.
func (mr *MockrepoMockRecorder) GetLatestValidatorSetEpoch(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestValidatorSetEpoch", reflect.TypeOf((*Mockrepo)(nil).GetLatestValidatorSetEpoch), arg0)
}

// GetLatestValidatorSetHeader mocks base method.
func (m *Mockrepo) GetLatestValidatorSetHeader(arg0 context.Context) (entity0.ValidatorSetHeader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestValidatorSetHeader", arg0)
	ret0, _ := ret[0].(entity0.ValidatorSetHeader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestValidatorSetHeader indicates an expected call of GetLatestValidatorSetHeader.
func (mr *MockrepoMockRecorder) GetLatestValidatorSetHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestValidatorSetHeader", reflect.TypeOf((*Mockrepo)(nil).GetLatestValidatorSetHeader), arg0)
}

// GetSignatureRequest mocks base method.
func (m *Mockrepo) GetSignatureRequest(ctx context.Context, requestID common.Hash) (entity0.SignatureRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSignatureRequest", ctx, requestID)
	ret0, _ := ret[0].(entity0.SignatureRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSignatureRequest indicates an expected call of GetSignatureRequest.
func (mr *MockrepoMockRecorder) GetSignatureRequest(ctx, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSignatureRequest", reflect.TypeOf((*Mockrepo)(nil).GetSignatureRequest), ctx, requestID)
}

// GetSignatureRequestIDsByEpoch mocks base method.
func (m *Mockrepo) GetSignatureRequestIDsByEpoch(ctx context.Context, epoch entity0.Epoch) ([]common.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSignatureRequestIDsByEpoch", ctx, epoch)
	ret0, _ := ret[0].([]common.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSignatureRequestIDsByEpoch indicates an expected call of GetSignatureRequestIDsByEpoch.
func (mr *MockrepoMockRecorder) GetSignatureRequestIDsByEpoch(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSignatureRequestIDsByEpoch", reflect.TypeOf((*Mockrepo)(nil).GetSignatureRequestIDsByEpoch), ctx, epoch)
}

// GetSignatureRequestsWithIDByEpoch mocks base method.
func (m *Mockrepo) GetSignatureRequestsWithIDByEpoch(ctx context.Context, epoch entity0.Epoch) ([]entity.SignatureRequestWithID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSignatureRequestsWithIDByEpoch", ctx, epoch)
	ret0, _ := ret[0].([]entity.SignatureRequestWithID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSignatureRequestsWithIDByEpoch indicates an expected call of GetSignatureRequestsWithIDByEpoch.
func (mr *MockrepoMockRecorder) GetSignatureRequestsWithIDByEpoch(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSignatureRequestsWithIDByEpoch", reflect.TypeOf((*Mockrepo)(nil).GetSignatureRequestsWithIDByEpoch), ctx, epoch)
}

// GetSignaturesByEpoch mocks base method.
func (m *Mockrepo) GetSignaturesByEpoch(ctx context.Context, epoch entity0.Epoch) ([]entity0.Signature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSignaturesByEpoch", ctx, epoch)
	ret0, _ := ret[0].([]entity0.Signature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSignaturesByEpoch indicates an expected call of GetSignaturesByEpoch.
func (mr *MockrepoMockRecorder) GetSignaturesByEpoch(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSignaturesByEpoch", reflect.TypeOf((*Mockrepo)(nil).GetSignaturesByEpoch), ctx, epoch)
}

// GetSignaturesStartingFromEpoch mocks base method.
func (m *Mockrepo) GetSignaturesStartingFromEpoch(ctx context.Context, epoch entity0.Epoch) ([]entity0.Signature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSignaturesStartingFromEpoch", ctx, epoch)
	ret0, _ := ret[0].([]entity0.Signature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSignaturesStartingFromEpoch indicates an expected call of GetSignaturesStartingFromEpoch.
func (mr *MockrepoMockRecorder) GetSignaturesStartingFromEpoch(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSignaturesStartingFromEpoch", reflect.TypeOf((*Mockrepo)(nil).GetSignaturesStartingFromEpoch), ctx, epoch)
}

// GetValidatorSetByEpoch mocks base method.
func (m *Mockrepo) GetValidatorSetByEpoch(arg0 context.Context, epoch entity0.Epoch) (entity0.ValidatorSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidatorSetByEpoch", arg0, epoch)
	ret0, _ := ret[0].(entity0.ValidatorSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidatorSetByEpoch indicates an expected call of GetValidatorSetByEpoch.
func (mr *MockrepoMockRecorder) GetValidatorSetByEpoch(arg0, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidatorSetByEpoch", reflect.TypeOf((*Mockrepo)(nil).GetValidatorSetByEpoch), arg0, epoch)
}

// GetValidatorSetMetadata mocks base method.
func (m *Mockrepo) GetValidatorSetMetadata(ctx context.Context, epoch entity0.Epoch) (entity0.ValidatorSetMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidatorSetMetadata", ctx, epoch)
	ret0, _ := ret[0].(entity0.ValidatorSetMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidatorSetMetadata indicates an expected call of GetValidatorSetMetadata.
func (mr *MockrepoMockRecorder) GetValidatorSetMetadata(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidatorSetMetadata", reflect.TypeOf((*Mockrepo)(nil).GetValidatorSetMetadata), ctx, epoch)
}

// GetValidatorSetsStartingFromEpoch mocks base method.
func (m *Mockrepo) GetValidatorSetsStartingFromEpoch(ctx context.Context, epoch entity0.Epoch) ([]entity0.ValidatorSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidatorSetsStartingFromEpoch", ctx, epoch)
	ret0, _ := ret[0].([]entity0.ValidatorSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidatorSetsStartingFromEpoch indicates an expected call of GetValidatorSetsStartingFromEpoch.
func (mr *MockrepoMockRecorder) GetValidatorSetsStartingFromEpoch(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidatorSetsStartingFromEpoch", reflect.TypeOf((*Mockrepo)(nil).GetValidatorSetsStartingFromEpoch), ctx, epoch)
}

// MockevmClient is a mock of evmClient interface.
type MockevmClient struct {
	ctrl     *gomock.Controller
	recorder *MockevmClientMockRecorder
	isgomock struct{}
}

// MockevmClientMockRecorder is the mock recorder for MockevmClient.
type MockevmClientMockRecorder struct {
	mock *MockevmClient
}

// NewMockevmClient creates a new mock instance.
func NewMockevmClient(ctrl *gomock.Controller) *MockevmClient {
	mock := &MockevmClient{ctrl: ctrl}
	mock.recorder = &MockevmClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockevmClient) EXPECT() *MockevmClientMockRecorder {
	return m.recorder
}

// GetConfig mocks base method.
func (m *MockevmClient) GetConfig(ctx context.Context, timestamp entity0.Timestamp, epoch entity0.Epoch) (entity0.NetworkConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", ctx, timestamp, epoch)
	ret0, _ := ret[0].(entity0.NetworkConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockevmClientMockRecorder) GetConfig(ctx, timestamp, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockevmClient)(nil).GetConfig), ctx, timestamp, epoch)
}

// GetCurrentEpoch mocks base method.
func (m *MockevmClient) GetCurrentEpoch(ctx context.Context) (entity0.Epoch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentEpoch", ctx)
	ret0, _ := ret[0].(entity0.Epoch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentEpoch indicates an expected call of GetCurrentEpoch.
func (mr *MockevmClientMockRecorder) GetCurrentEpoch(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentEpoch", reflect.TypeOf((*MockevmClient)(nil).GetCurrentEpoch), ctx)
}

// GetEpochStart mocks base method.
func (m *MockevmClient) GetEpochStart(ctx context.Context, epoch entity0.Epoch) (entity0.Timestamp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpochStart", ctx, epoch)
	ret0, _ := ret[0].(entity0.Timestamp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEpochStart indicates an expected call of GetEpochStart.
func (mr *MockevmClientMockRecorder) GetEpochStart(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpochStart", reflect.TypeOf((*MockevmClient)(nil).GetEpochStart), ctx, epoch)
}

// GetLastCommittedHeaderEpoch mocks base method.
func (m *MockevmClient) GetLastCommittedHeaderEpoch(ctx context.Context, addr entity0.CrossChainAddress, opts ...entity.EVMOption) (entity0.Epoch, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, addr}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLastCommittedHeaderEpoch", varargs...)
	ret0, _ := ret[0].(entity0.Epoch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastCommittedHeaderEpoch indicates an expected call of GetLastCommittedHeaderEpoch.
func (mr *MockevmClientMockRecorder) GetLastCommittedHeaderEpoch(ctx, addr any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, addr}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastCommittedHeaderEpoch", reflect.TypeOf((*MockevmClient)(nil).GetLastCommittedHeaderEpoch), varargs...)
}

// Mockaggregator is a mock of aggregator interface.
type Mockaggregator struct {
	ctrl     *gomock.Controller
	recorder *MockaggregatorMockRecorder
	isgomock struct{}
}

// MockaggregatorMockRecorder is the mock recorder for Mockaggregator.
type MockaggregatorMockRecorder struct {
	mock *Mockaggregator
}

// NewMockaggregator creates a new mock instance.
func NewMockaggregator(ctrl *gomock.Controller) *Mockaggregator {
	mock := &Mockaggregator{ctrl: ctrl}
	mock.recorder = &MockaggregatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockaggregator) EXPECT() *MockaggregatorMockRecorder {
	return m.recorder
}

// GetAggregationStatus mocks base method.
func (m *Mockaggregator) GetAggregationStatus(ctx context.Context, requestID common.Hash) (entity0.AggregationStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAggregationStatus", ctx, requestID)
	ret0, _ := ret[0].(entity0.AggregationStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAggregationStatus indicates an expected call of GetAggregationStatus.
func (mr *MockaggregatorMockRecorder) GetAggregationStatus(ctx, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAggregationStatus", reflect.TypeOf((*Mockaggregator)(nil).GetAggregationStatus), ctx, requestID)
}

// Mockderiver is a mock of deriver interface.
type Mockderiver struct {
	ctrl     *gomock.Controller
	recorder *MockderiverMockRecorder
	isgomock struct{}
}

// MockderiverMockRecorder is the mock recorder for Mockderiver.
type MockderiverMockRecorder struct {
	mock *Mockderiver
}

// NewMockderiver creates a new mock instance.
func NewMockderiver(ctrl *gomock.Controller) *Mockderiver {
	mock := &Mockderiver{ctrl: ctrl}
	mock.recorder = &MockderiverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockderiver) EXPECT() *MockderiverMockRecorder {
	return m.recorder
}

// GetValidatorSet mocks base method.
func (m *Mockderiver) GetValidatorSet(ctx context.Context, epoch entity0.Epoch, config entity0.NetworkConfig) (entity0.ValidatorSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidatorSet", ctx, epoch, config)
	ret0, _ := ret[0].(entity0.ValidatorSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidatorSet indicates an expected call of GetValidatorSet.
func (mr *MockderiverMockRecorder) GetValidatorSet(ctx, epoch, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidatorSet", reflect.TypeOf((*Mockderiver)(nil).GetValidatorSet), ctx, epoch, config)
}

// MockkeyProvider is a mock of keyProvider interface.
type MockkeyProvider struct {
	ctrl     *gomock.Controller
	recorder *MockkeyProviderMockRecorder
	isgomock struct{}
}

// MockkeyProviderMockRecorder is the mock recorder for MockkeyProvider.
type MockkeyProviderMockRecorder struct {
	mock *MockkeyProvider
}

// NewMockkeyProvider creates a new mock instance.
func NewMockkeyProvider(ctrl *gomock.Controller) *MockkeyProvider {
	mock := &MockkeyProvider{ctrl: ctrl}
	mock.recorder = &MockkeyProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockkeyProvider) EXPECT() *MockkeyProviderMockRecorder {
	return m.recorder
}

// GetOnchainKeyFromCache mocks base method.
func (m *MockkeyProvider) GetOnchainKeyFromCache(keyTag entity0.KeyTag) (entity0.CompactPublicKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOnchainKeyFromCache", keyTag)
	ret0, _ := ret[0].(entity0.CompactPublicKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOnchainKeyFromCache indicates an expected call of GetOnchainKeyFromCache.
func (mr *MockkeyProviderMockRecorder) GetOnchainKeyFromCache(keyTag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOnchainKeyFromCache", reflect.TypeOf((*MockkeyProvider)(nil).GetOnchainKeyFromCache), keyTag)
}
