// Code generated by MockGen. DO NOT EDIT.
// Source: app.go
//
// Generated by this command:
//
//	mockgen -source=app.go -destination=mocks/app_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	entity "github.com/symbioticfi/relay/core/entity"
	gomock "go.uber.org/mock/gomock"
)

// Mocksigner is a mock of signer interface.
type Mocksigner struct {
	ctrl     *gomock.Controller
	recorder *MocksignerMockRecorder
	isgomock struct{}
}

// MocksignerMockRecorder is the mock recorder for Mocksigner.
type MocksignerMockRecorder struct {
	mock *Mocksigner
}

// NewMocksigner creates a new mock instance.
func NewMocksigner(ctrl *gomock.Controller) *Mocksigner {
	mock := &Mocksigner{ctrl: ctrl}
	mock.recorder = &MocksignerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksigner) EXPECT() *MocksignerMockRecorder {
	return m.recorder
}

// Sign mocks base method.
func (m *Mocksigner) Sign(ctx context.Context, req entity.SignatureRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sign", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sign indicates an expected call of Sign.
func (mr *MocksignerMockRecorder) Sign(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sign", reflect.TypeOf((*Mocksigner)(nil).Sign), ctx, req)
}

// Mockrepo is a mock of repo interface.
type Mockrepo struct {
	ctrl     *gomock.Controller
	recorder *MockrepoMockRecorder
	isgomock struct{}
}

// MockrepoMockRecorder is the mock recorder for Mockrepo.
type MockrepoMockRecorder struct {
	mock *Mockrepo
}

// NewMockrepo creates a new mock instance.
func NewMockrepo(ctrl *gomock.Controller) *Mockrepo {
	mock := &Mockrepo{ctrl: ctrl}
	mock.recorder = &MockrepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepo) EXPECT() *MockrepoMockRecorder {
	return m.recorder
}

// GetAggregationProof mocks base method.
func (m *Mockrepo) GetAggregationProof(ctx context.Context, reqHash common.Hash) (entity.AggregationProof, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAggregationProof", ctx, reqHash)
	ret0, _ := ret[0].(entity.AggregationProof)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAggregationProof indicates an expected call of GetAggregationProof.
func (mr *MockrepoMockRecorder) GetAggregationProof(ctx, reqHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAggregationProof", reflect.TypeOf((*Mockrepo)(nil).GetAggregationProof), ctx, reqHash)
}

// GetAllSignatures mocks base method.
func (m *Mockrepo) GetAllSignatures(arg0 context.Context, reqHash common.Hash) ([]entity.SignatureExtended, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSignatures", arg0, reqHash)
	ret0, _ := ret[0].([]entity.SignatureExtended)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSignatures indicates an expected call of GetAllSignatures.
func (mr *MockrepoMockRecorder) GetAllSignatures(arg0, reqHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSignatures", reflect.TypeOf((*Mockrepo)(nil).GetAllSignatures), arg0, reqHash)
}

// GetLatestValidatorSetEpoch mocks base method.
func (m *Mockrepo) GetLatestValidatorSetEpoch(arg0 context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestValidatorSetEpoch", arg0)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestValidatorSetEpoch indicates an expected call of GetLatestValidatorSetEpoch.
func (mr *MockrepoMockRecorder) GetLatestValidatorSetEpoch(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestValidatorSetEpoch", reflect.TypeOf((*Mockrepo)(nil).GetLatestValidatorSetEpoch), arg0)
}

// GetLatestValidatorSetHeader mocks base method.
func (m *Mockrepo) GetLatestValidatorSetHeader(arg0 context.Context) (entity.ValidatorSetHeader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestValidatorSetHeader", arg0)
	ret0, _ := ret[0].(entity.ValidatorSetHeader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestValidatorSetHeader indicates an expected call of GetLatestValidatorSetHeader.
func (mr *MockrepoMockRecorder) GetLatestValidatorSetHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestValidatorSetHeader", reflect.TypeOf((*Mockrepo)(nil).GetLatestValidatorSetHeader), arg0)
}

// GetSignatureRequest mocks base method.
func (m *Mockrepo) GetSignatureRequest(arg0 context.Context, reqHash common.Hash) (entity.SignatureRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSignatureRequest", arg0, reqHash)
	ret0, _ := ret[0].(entity.SignatureRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSignatureRequest indicates an expected call of GetSignatureRequest.
func (mr *MockrepoMockRecorder) GetSignatureRequest(arg0, reqHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSignatureRequest", reflect.TypeOf((*Mockrepo)(nil).GetSignatureRequest), arg0, reqHash)
}

// GetValidatorSetByEpoch mocks base method.
func (m *Mockrepo) GetValidatorSetByEpoch(arg0 context.Context, epoch uint64) (entity.ValidatorSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidatorSetByEpoch", arg0, epoch)
	ret0, _ := ret[0].(entity.ValidatorSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidatorSetByEpoch indicates an expected call of GetValidatorSetByEpoch.
func (mr *MockrepoMockRecorder) GetValidatorSetByEpoch(arg0, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidatorSetByEpoch", reflect.TypeOf((*Mockrepo)(nil).GetValidatorSetByEpoch), arg0, epoch)
}

// GetValidatorSetMetadata mocks base method.
func (m *Mockrepo) GetValidatorSetMetadata(ctx context.Context, epoch uint64) ([]entity.ExtraData, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidatorSetMetadata", ctx, epoch)
	ret0, _ := ret[0].([]entity.ExtraData)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetValidatorSetMetadata indicates an expected call of GetValidatorSetMetadata.
func (mr *MockrepoMockRecorder) GetValidatorSetMetadata(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidatorSetMetadata", reflect.TypeOf((*Mockrepo)(nil).GetValidatorSetMetadata), ctx, epoch)
}

// MockevmClient is a mock of evmClient interface.
type MockevmClient struct {
	ctrl     *gomock.Controller
	recorder *MockevmClientMockRecorder
	isgomock struct{}
}

// MockevmClientMockRecorder is the mock recorder for MockevmClient.
type MockevmClientMockRecorder struct {
	mock *MockevmClient
}

// NewMockevmClient creates a new mock instance.
func NewMockevmClient(ctrl *gomock.Controller) *MockevmClient {
	mock := &MockevmClient{ctrl: ctrl}
	mock.recorder = &MockevmClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockevmClient) EXPECT() *MockevmClientMockRecorder {
	return m.recorder
}

// GetConfig mocks base method.
func (m *MockevmClient) GetConfig(ctx context.Context, timestamp uint64) (entity.NetworkConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", ctx, timestamp)
	ret0, _ := ret[0].(entity.NetworkConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockevmClientMockRecorder) GetConfig(ctx, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockevmClient)(nil).GetConfig), ctx, timestamp)
}

// GetCurrentEpoch mocks base method.
func (m *MockevmClient) GetCurrentEpoch(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentEpoch", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentEpoch indicates an expected call of GetCurrentEpoch.
func (mr *MockevmClientMockRecorder) GetCurrentEpoch(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentEpoch", reflect.TypeOf((*MockevmClient)(nil).GetCurrentEpoch), ctx)
}

// GetEpochStart mocks base method.
func (m *MockevmClient) GetEpochStart(ctx context.Context, epoch uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpochStart", ctx, epoch)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEpochStart indicates an expected call of GetEpochStart.
func (mr *MockevmClientMockRecorder) GetEpochStart(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpochStart", reflect.TypeOf((*MockevmClient)(nil).GetEpochStart), ctx, epoch)
}

// GetLastCommittedHeaderEpoch mocks base method.
func (m *MockevmClient) GetLastCommittedHeaderEpoch(ctx context.Context, addr entity.CrossChainAddress) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastCommittedHeaderEpoch", ctx, addr)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastCommittedHeaderEpoch indicates an expected call of GetLastCommittedHeaderEpoch.
func (mr *MockevmClientMockRecorder) GetLastCommittedHeaderEpoch(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastCommittedHeaderEpoch", reflect.TypeOf((*MockevmClient)(nil).GetLastCommittedHeaderEpoch), ctx, addr)
}

// Mockaggregator is a mock of aggregator interface.
type Mockaggregator struct {
	ctrl     *gomock.Controller
	recorder *MockaggregatorMockRecorder
	isgomock struct{}
}

// MockaggregatorMockRecorder is the mock recorder for Mockaggregator.
type MockaggregatorMockRecorder struct {
	mock *Mockaggregator
}

// NewMockaggregator creates a new mock instance.
func NewMockaggregator(ctrl *gomock.Controller) *Mockaggregator {
	mock := &Mockaggregator{ctrl: ctrl}
	mock.recorder = &MockaggregatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockaggregator) EXPECT() *MockaggregatorMockRecorder {
	return m.recorder
}

// GetAggregationStatus mocks base method.
func (m *Mockaggregator) GetAggregationStatus(ctx context.Context, requestHash common.Hash) (entity.AggregationStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAggregationStatus", ctx, requestHash)
	ret0, _ := ret[0].(entity.AggregationStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAggregationStatus indicates an expected call of GetAggregationStatus.
func (mr *MockaggregatorMockRecorder) GetAggregationStatus(ctx, requestHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAggregationStatus", reflect.TypeOf((*Mockaggregator)(nil).GetAggregationStatus), ctx, requestHash)
}

// Mockderiver is a mock of deriver interface.
type Mockderiver struct {
	ctrl     *gomock.Controller
	recorder *MockderiverMockRecorder
	isgomock struct{}
}

// MockderiverMockRecorder is the mock recorder for Mockderiver.
type MockderiverMockRecorder struct {
	mock *Mockderiver
}

// NewMockderiver creates a new mock instance.
func NewMockderiver(ctrl *gomock.Controller) *Mockderiver {
	mock := &Mockderiver{ctrl: ctrl}
	mock.recorder = &MockderiverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockderiver) EXPECT() *MockderiverMockRecorder {
	return m.recorder
}

// GetValidatorSet mocks base method.
func (m *Mockderiver) GetValidatorSet(ctx context.Context, epoch uint64, config entity.NetworkConfig) (entity.ValidatorSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidatorSet", ctx, epoch, config)
	ret0, _ := ret[0].(entity.ValidatorSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidatorSet indicates an expected call of GetValidatorSet.
func (mr *MockderiverMockRecorder) GetValidatorSet(ctx, epoch, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidatorSet", reflect.TypeOf((*Mockderiver)(nil).GetValidatorSet), ctx, epoch, config)
}
