// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/symbioticfi/relay/symbiotic/client/evm (interfaces: IEvmClient,conn,metrics,keyProvider,driverContract,settlementContract,votingPowerProviderContract,votingPowerProviderTransactor,keyRegistryContract,operatorRegistryContract)
//
// Generated by this command:
//
//	mockgen -destination=mocks/eth.go -package=mocks github.com/symbioticfi/relay/symbiotic/client/evm IEvmClient,conn,metrics,keyProvider,driverContract,settlementContract,votingPowerProviderContract,votingPowerProviderTransactor,keyRegistryContract,operatorRegistryContract
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	big "math/big"
	reflect "reflect"
	time "time"

	ethereum "github.com/ethereum/go-ethereum"
	bind "github.com/ethereum/go-ethereum/accounts/abi/bind"
	common "github.com/ethereum/go-ethereum/common"
	types "github.com/ethereum/go-ethereum/core/types"
	gen "github.com/symbioticfi/relay/symbiotic/client/evm/gen"
	entity "github.com/symbioticfi/relay/symbiotic/entity"
	crypto "github.com/symbioticfi/relay/symbiotic/usecase/crypto"
	gomock "go.uber.org/mock/gomock"
)

// MockIEvmClient is a mock of IEvmClient interface.
type MockIEvmClient struct {
	ctrl     *gomock.Controller
	recorder *MockIEvmClientMockRecorder
	isgomock struct{}
}

// MockIEvmClientMockRecorder is the mock recorder for MockIEvmClient.
type MockIEvmClientMockRecorder struct {
	mock *MockIEvmClient
}

// NewMockIEvmClient creates a new mock instance.
func NewMockIEvmClient(ctrl *gomock.Controller) *MockIEvmClient {
	mock := &MockIEvmClient{ctrl: ctrl}
	mock.recorder = &MockIEvmClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEvmClient) EXPECT() *MockIEvmClientMockRecorder {
	return m.recorder
}

// CommitValsetHeader mocks base method.
func (m *MockIEvmClient) CommitValsetHeader(ctx context.Context, addr entity.CrossChainAddress, header entity.ValidatorSetHeader, extraData []entity.ExtraData, proof []byte) (entity.TxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitValsetHeader", ctx, addr, header, extraData, proof)
	ret0, _ := ret[0].(entity.TxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitValsetHeader indicates an expected call of CommitValsetHeader.
func (mr *MockIEvmClientMockRecorder) CommitValsetHeader(ctx, addr, header, extraData, proof any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitValsetHeader", reflect.TypeOf((*MockIEvmClient)(nil).CommitValsetHeader), ctx, addr, header, extraData, proof)
}

// GetCaptureTimestampFromValsetHeaderAt mocks base method.
func (m *MockIEvmClient) GetCaptureTimestampFromValsetHeaderAt(ctx context.Context, addr entity.CrossChainAddress, epoch entity.Epoch) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCaptureTimestampFromValsetHeaderAt", ctx, addr, epoch)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCaptureTimestampFromValsetHeaderAt indicates an expected call of GetCaptureTimestampFromValsetHeaderAt.
func (mr *MockIEvmClientMockRecorder) GetCaptureTimestampFromValsetHeaderAt(ctx, addr, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCaptureTimestampFromValsetHeaderAt", reflect.TypeOf((*MockIEvmClient)(nil).GetCaptureTimestampFromValsetHeaderAt), ctx, addr, epoch)
}

// GetChains mocks base method.
func (m *MockIEvmClient) GetChains() []uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChains")
	ret0, _ := ret[0].([]uint64)
	return ret0
}

// GetChains indicates an expected call of GetChains.
func (mr *MockIEvmClientMockRecorder) GetChains() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChains", reflect.TypeOf((*MockIEvmClient)(nil).GetChains))
}

// GetConfig mocks base method.
func (m *MockIEvmClient) GetConfig(ctx context.Context, timestamp entity.Timestamp, epoch entity.Epoch) (entity.NetworkConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", ctx, timestamp, epoch)
	ret0, _ := ret[0].(entity.NetworkConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockIEvmClientMockRecorder) GetConfig(ctx, timestamp, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockIEvmClient)(nil).GetConfig), ctx, timestamp, epoch)
}

// GetCurrentEpoch mocks base method.
func (m *MockIEvmClient) GetCurrentEpoch(ctx context.Context) (entity.Epoch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentEpoch", ctx)
	ret0, _ := ret[0].(entity.Epoch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentEpoch indicates an expected call of GetCurrentEpoch.
func (mr *MockIEvmClientMockRecorder) GetCurrentEpoch(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentEpoch", reflect.TypeOf((*MockIEvmClient)(nil).GetCurrentEpoch), ctx)
}

// GetCurrentEpochDuration mocks base method.
func (m *MockIEvmClient) GetCurrentEpochDuration(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentEpochDuration", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentEpochDuration indicates an expected call of GetCurrentEpochDuration.
func (mr *MockIEvmClientMockRecorder) GetCurrentEpochDuration(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentEpochDuration", reflect.TypeOf((*MockIEvmClient)(nil).GetCurrentEpochDuration), ctx)
}

// GetEip712Domain mocks base method.
func (m *MockIEvmClient) GetEip712Domain(ctx context.Context, addr entity.CrossChainAddress) (entity.Eip712Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEip712Domain", ctx, addr)
	ret0, _ := ret[0].(entity.Eip712Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEip712Domain indicates an expected call of GetEip712Domain.
func (mr *MockIEvmClientMockRecorder) GetEip712Domain(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEip712Domain", reflect.TypeOf((*MockIEvmClient)(nil).GetEip712Domain), ctx, addr)
}

// GetEpochDuration mocks base method.
func (m *MockIEvmClient) GetEpochDuration(ctx context.Context, epoch entity.Epoch) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpochDuration", ctx, epoch)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEpochDuration indicates an expected call of GetEpochDuration.
func (mr *MockIEvmClientMockRecorder) GetEpochDuration(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpochDuration", reflect.TypeOf((*MockIEvmClient)(nil).GetEpochDuration), ctx, epoch)
}

// GetEpochStart mocks base method.
func (m *MockIEvmClient) GetEpochStart(ctx context.Context, epoch entity.Epoch) (entity.Timestamp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpochStart", ctx, epoch)
	ret0, _ := ret[0].(entity.Timestamp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEpochStart indicates an expected call of GetEpochStart.
func (mr *MockIEvmClientMockRecorder) GetEpochStart(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpochStart", reflect.TypeOf((*MockIEvmClient)(nil).GetEpochStart), ctx, epoch)
}

// GetHeaderHash mocks base method.
func (m *MockIEvmClient) GetHeaderHash(ctx context.Context, addr entity.CrossChainAddress) (common.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeaderHash", ctx, addr)
	ret0, _ := ret[0].(common.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeaderHash indicates an expected call of GetHeaderHash.
func (mr *MockIEvmClientMockRecorder) GetHeaderHash(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeaderHash", reflect.TypeOf((*MockIEvmClient)(nil).GetHeaderHash), ctx, addr)
}

// GetHeaderHashAt mocks base method.
func (m *MockIEvmClient) GetHeaderHashAt(ctx context.Context, addr entity.CrossChainAddress, epoch entity.Epoch) (common.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeaderHashAt", ctx, addr, epoch)
	ret0, _ := ret[0].(common.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeaderHashAt indicates an expected call of GetHeaderHashAt.
func (mr *MockIEvmClientMockRecorder) GetHeaderHashAt(ctx, addr, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeaderHashAt", reflect.TypeOf((*MockIEvmClient)(nil).GetHeaderHashAt), ctx, addr, epoch)
}

// GetKeys mocks base method.
func (m *MockIEvmClient) GetKeys(ctx context.Context, address entity.CrossChainAddress, timestamp entity.Timestamp) ([]entity.OperatorWithKeys, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeys", ctx, address, timestamp)
	ret0, _ := ret[0].([]entity.OperatorWithKeys)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeys indicates an expected call of GetKeys.
func (mr *MockIEvmClientMockRecorder) GetKeys(ctx, address, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeys", reflect.TypeOf((*MockIEvmClient)(nil).GetKeys), ctx, address, timestamp)
}

// GetLastCommittedHeaderEpoch mocks base method.
func (m *MockIEvmClient) GetLastCommittedHeaderEpoch(ctx context.Context, addr entity.CrossChainAddress, evmOptions ...entity.EVMOption) (entity.Epoch, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, addr}
	for _, a := range evmOptions {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLastCommittedHeaderEpoch", varargs...)
	ret0, _ := ret[0].(entity.Epoch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastCommittedHeaderEpoch indicates an expected call of GetLastCommittedHeaderEpoch.
func (mr *MockIEvmClientMockRecorder) GetLastCommittedHeaderEpoch(ctx, addr any, evmOptions ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, addr}, evmOptions...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastCommittedHeaderEpoch", reflect.TypeOf((*MockIEvmClient)(nil).GetLastCommittedHeaderEpoch), varargs...)
}

// GetNetworkAddress mocks base method.
func (m *MockIEvmClient) GetNetworkAddress(ctx context.Context) (common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkAddress", ctx)
	ret0, _ := ret[0].(common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkAddress indicates an expected call of GetNetworkAddress.
func (mr *MockIEvmClientMockRecorder) GetNetworkAddress(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkAddress", reflect.TypeOf((*MockIEvmClient)(nil).GetNetworkAddress), ctx)
}

// GetOperatorNonce mocks base method.
func (m *MockIEvmClient) GetOperatorNonce(ctx context.Context, votingPowerProvider entity.CrossChainAddress, operator common.Address) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperatorNonce", ctx, votingPowerProvider, operator)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOperatorNonce indicates an expected call of GetOperatorNonce.
func (mr *MockIEvmClientMockRecorder) GetOperatorNonce(ctx, votingPowerProvider, operator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperatorNonce", reflect.TypeOf((*MockIEvmClient)(nil).GetOperatorNonce), ctx, votingPowerProvider, operator)
}

// GetSubnetwork mocks base method.
func (m *MockIEvmClient) GetSubnetwork(ctx context.Context) (common.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubnetwork", ctx)
	ret0, _ := ret[0].(common.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubnetwork indicates an expected call of GetSubnetwork.
func (mr *MockIEvmClientMockRecorder) GetSubnetwork(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubnetwork", reflect.TypeOf((*MockIEvmClient)(nil).GetSubnetwork), ctx)
}

// GetValSetHeader mocks base method.
func (m *MockIEvmClient) GetValSetHeader(ctx context.Context, addr entity.CrossChainAddress) (entity.ValidatorSetHeader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValSetHeader", ctx, addr)
	ret0, _ := ret[0].(entity.ValidatorSetHeader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValSetHeader indicates an expected call of GetValSetHeader.
func (mr *MockIEvmClientMockRecorder) GetValSetHeader(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValSetHeader", reflect.TypeOf((*MockIEvmClient)(nil).GetValSetHeader), ctx, addr)
}

// GetValSetHeaderAt mocks base method.
func (m *MockIEvmClient) GetValSetHeaderAt(ctx context.Context, addr entity.CrossChainAddress, epoch entity.Epoch) (entity.ValidatorSetHeader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValSetHeaderAt", ctx, addr, epoch)
	ret0, _ := ret[0].(entity.ValidatorSetHeader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValSetHeaderAt indicates an expected call of GetValSetHeaderAt.
func (mr *MockIEvmClientMockRecorder) GetValSetHeaderAt(ctx, addr, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValSetHeaderAt", reflect.TypeOf((*MockIEvmClient)(nil).GetValSetHeaderAt), ctx, addr, epoch)
}

// GetVotingPowerProviderEip712Domain mocks base method.
func (m *MockIEvmClient) GetVotingPowerProviderEip712Domain(ctx context.Context, addr entity.CrossChainAddress) (entity.Eip712Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVotingPowerProviderEip712Domain", ctx, addr)
	ret0, _ := ret[0].(entity.Eip712Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVotingPowerProviderEip712Domain indicates an expected call of GetVotingPowerProviderEip712Domain.
func (mr *MockIEvmClientMockRecorder) GetVotingPowerProviderEip712Domain(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVotingPowerProviderEip712Domain", reflect.TypeOf((*MockIEvmClient)(nil).GetVotingPowerProviderEip712Domain), ctx, addr)
}

// GetVotingPowers mocks base method.
func (m *MockIEvmClient) GetVotingPowers(ctx context.Context, address entity.CrossChainAddress, timestamp entity.Timestamp) ([]entity.OperatorVotingPower, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVotingPowers", ctx, address, timestamp)
	ret0, _ := ret[0].([]entity.OperatorVotingPower)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVotingPowers indicates an expected call of GetVotingPowers.
func (mr *MockIEvmClientMockRecorder) GetVotingPowers(ctx, address, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVotingPowers", reflect.TypeOf((*MockIEvmClient)(nil).GetVotingPowers), ctx, address, timestamp)
}

// InvalidateOldSignatures mocks base method.
func (m *MockIEvmClient) InvalidateOldSignatures(ctx context.Context, addr entity.CrossChainAddress) (entity.TxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateOldSignatures", ctx, addr)
	ret0, _ := ret[0].(entity.TxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InvalidateOldSignatures indicates an expected call of InvalidateOldSignatures.
func (mr *MockIEvmClientMockRecorder) InvalidateOldSignatures(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateOldSignatures", reflect.TypeOf((*MockIEvmClient)(nil).InvalidateOldSignatures), ctx, addr)
}

// IsValsetHeaderCommittedAt mocks base method.
func (m *MockIEvmClient) IsValsetHeaderCommittedAt(ctx context.Context, addr entity.CrossChainAddress, epoch entity.Epoch, opts ...entity.EVMOption) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, addr, epoch}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IsValsetHeaderCommittedAt", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsValsetHeaderCommittedAt indicates an expected call of IsValsetHeaderCommittedAt.
func (mr *MockIEvmClientMockRecorder) IsValsetHeaderCommittedAt(ctx, addr, epoch any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, addr, epoch}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValsetHeaderCommittedAt", reflect.TypeOf((*MockIEvmClient)(nil).IsValsetHeaderCommittedAt), varargs...)
}

// IsValsetHeaderCommittedAtEpochs mocks base method.
func (m *MockIEvmClient) IsValsetHeaderCommittedAtEpochs(ctx context.Context, addr entity.CrossChainAddress, epochs []entity.Epoch) ([]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValsetHeaderCommittedAtEpochs", ctx, addr, epochs)
	ret0, _ := ret[0].([]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsValsetHeaderCommittedAtEpochs indicates an expected call of IsValsetHeaderCommittedAtEpochs.
func (mr *MockIEvmClientMockRecorder) IsValsetHeaderCommittedAtEpochs(ctx, addr, epochs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValsetHeaderCommittedAtEpochs", reflect.TypeOf((*MockIEvmClient)(nil).IsValsetHeaderCommittedAtEpochs), ctx, addr, epochs)
}

// RegisterKey mocks base method.
func (m *MockIEvmClient) RegisterKey(ctx context.Context, addr entity.CrossChainAddress, keyTag entity.KeyTag, key entity.CompactPublicKey, signature entity.RawSignature, extraData []byte) (entity.TxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterKey", ctx, addr, keyTag, key, signature, extraData)
	ret0, _ := ret[0].(entity.TxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterKey indicates an expected call of RegisterKey.
func (mr *MockIEvmClientMockRecorder) RegisterKey(ctx, addr, keyTag, key, signature, extraData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterKey", reflect.TypeOf((*MockIEvmClient)(nil).RegisterKey), ctx, addr, keyTag, key, signature, extraData)
}

// RegisterOperator mocks base method.
func (m *MockIEvmClient) RegisterOperator(ctx context.Context, addr entity.CrossChainAddress) (entity.TxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterOperator", ctx, addr)
	ret0, _ := ret[0].(entity.TxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterOperator indicates an expected call of RegisterOperator.
func (mr *MockIEvmClientMockRecorder) RegisterOperator(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterOperator", reflect.TypeOf((*MockIEvmClient)(nil).RegisterOperator), ctx, addr)
}

// RegisterOperatorVotingPowerProvider mocks base method.
func (m *MockIEvmClient) RegisterOperatorVotingPowerProvider(ctx context.Context, addr entity.CrossChainAddress) (entity.TxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterOperatorVotingPowerProvider", ctx, addr)
	ret0, _ := ret[0].(entity.TxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterOperatorVotingPowerProvider indicates an expected call of RegisterOperatorVotingPowerProvider.
func (mr *MockIEvmClientMockRecorder) RegisterOperatorVotingPowerProvider(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterOperatorVotingPowerProvider", reflect.TypeOf((*MockIEvmClient)(nil).RegisterOperatorVotingPowerProvider), ctx, addr)
}

// SetGenesis mocks base method.
func (m *MockIEvmClient) SetGenesis(ctx context.Context, addr entity.CrossChainAddress, header entity.ValidatorSetHeader, extraData []entity.ExtraData) (entity.TxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGenesis", ctx, addr, header, extraData)
	ret0, _ := ret[0].(entity.TxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetGenesis indicates an expected call of SetGenesis.
func (mr *MockIEvmClientMockRecorder) SetGenesis(ctx, addr, header, extraData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGenesis", reflect.TypeOf((*MockIEvmClient)(nil).SetGenesis), ctx, addr, header, extraData)
}

// UnregisterOperatorVotingPowerProvider mocks base method.
func (m *MockIEvmClient) UnregisterOperatorVotingPowerProvider(ctx context.Context, addr entity.CrossChainAddress) (entity.TxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnregisterOperatorVotingPowerProvider", ctx, addr)
	ret0, _ := ret[0].(entity.TxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnregisterOperatorVotingPowerProvider indicates an expected call of UnregisterOperatorVotingPowerProvider.
func (mr *MockIEvmClientMockRecorder) UnregisterOperatorVotingPowerProvider(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterOperatorVotingPowerProvider", reflect.TypeOf((*MockIEvmClient)(nil).UnregisterOperatorVotingPowerProvider), ctx, addr)
}

// VerifyQuorumSig mocks base method.
func (m *MockIEvmClient) VerifyQuorumSig(ctx context.Context, addr entity.CrossChainAddress, epoch entity.Epoch, message []byte, keyTag entity.KeyTag, threshold *big.Int, proof []byte) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyQuorumSig", ctx, addr, epoch, message, keyTag, threshold, proof)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyQuorumSig indicates an expected call of VerifyQuorumSig.
func (mr *MockIEvmClientMockRecorder) VerifyQuorumSig(ctx, addr, epoch, message, keyTag, threshold, proof any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyQuorumSig", reflect.TypeOf((*MockIEvmClient)(nil).VerifyQuorumSig), ctx, addr, epoch, message, keyTag, threshold, proof)
}

// Mockconn is a mock of conn interface.
type Mockconn struct {
	ctrl     *gomock.Controller
	recorder *MockconnMockRecorder
	isgomock struct{}
}

// MockconnMockRecorder is the mock recorder for Mockconn.
type MockconnMockRecorder struct {
	mock *Mockconn
}

// NewMockconn creates a new mock instance.
func NewMockconn(ctrl *gomock.Controller) *Mockconn {
	mock := &Mockconn{ctrl: ctrl}
	mock.recorder = &MockconnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockconn) EXPECT() *MockconnMockRecorder {
	return m.recorder
}

// CallContract mocks base method.
func (m *Mockconn) CallContract(ctx context.Context, call ethereum.CallMsg, blockNumber *big.Int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallContract", ctx, call, blockNumber)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CallContract indicates an expected call of CallContract.
func (mr *MockconnMockRecorder) CallContract(ctx, call, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallContract", reflect.TypeOf((*Mockconn)(nil).CallContract), ctx, call, blockNumber)
}

// CodeAt mocks base method.
func (m *Mockconn) CodeAt(ctx context.Context, contract common.Address, blockNumber *big.Int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CodeAt", ctx, contract, blockNumber)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CodeAt indicates an expected call of CodeAt.
func (mr *MockconnMockRecorder) CodeAt(ctx, contract, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CodeAt", reflect.TypeOf((*Mockconn)(nil).CodeAt), ctx, contract, blockNumber)
}

// EstimateGas mocks base method.
func (m *Mockconn) EstimateGas(ctx context.Context, call ethereum.CallMsg) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateGas", ctx, call)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateGas indicates an expected call of EstimateGas.
func (mr *MockconnMockRecorder) EstimateGas(ctx, call any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateGas", reflect.TypeOf((*Mockconn)(nil).EstimateGas), ctx, call)
}

// FilterLogs mocks base method.
func (m *Mockconn) FilterLogs(ctx context.Context, q ethereum.FilterQuery) ([]types.Log, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterLogs", ctx, q)
	ret0, _ := ret[0].([]types.Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterLogs indicates an expected call of FilterLogs.
func (mr *MockconnMockRecorder) FilterLogs(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterLogs", reflect.TypeOf((*Mockconn)(nil).FilterLogs), ctx, q)
}

// HeaderByNumber mocks base method.
func (m *Mockconn) HeaderByNumber(ctx context.Context, number *big.Int) (*types.Header, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeaderByNumber", ctx, number)
	ret0, _ := ret[0].(*types.Header)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeaderByNumber indicates an expected call of HeaderByNumber.
func (mr *MockconnMockRecorder) HeaderByNumber(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeaderByNumber", reflect.TypeOf((*Mockconn)(nil).HeaderByNumber), ctx, number)
}

// PendingCodeAt mocks base method.
func (m *Mockconn) PendingCodeAt(ctx context.Context, account common.Address) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingCodeAt", ctx, account)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PendingCodeAt indicates an expected call of PendingCodeAt.
func (mr *MockconnMockRecorder) PendingCodeAt(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingCodeAt", reflect.TypeOf((*Mockconn)(nil).PendingCodeAt), ctx, account)
}

// PendingNonceAt mocks base method.
func (m *Mockconn) PendingNonceAt(ctx context.Context, account common.Address) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingNonceAt", ctx, account)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PendingNonceAt indicates an expected call of PendingNonceAt.
func (mr *MockconnMockRecorder) PendingNonceAt(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingNonceAt", reflect.TypeOf((*Mockconn)(nil).PendingNonceAt), ctx, account)
}

// SendTransaction mocks base method.
func (m *Mockconn) SendTransaction(ctx context.Context, tx *types.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTransaction", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendTransaction indicates an expected call of SendTransaction.
func (mr *MockconnMockRecorder) SendTransaction(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTransaction", reflect.TypeOf((*Mockconn)(nil).SendTransaction), ctx, tx)
}

// SubscribeFilterLogs mocks base method.
func (m *Mockconn) SubscribeFilterLogs(ctx context.Context, q ethereum.FilterQuery, ch chan<- types.Log) (ethereum.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeFilterLogs", ctx, q, ch)
	ret0, _ := ret[0].(ethereum.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeFilterLogs indicates an expected call of SubscribeFilterLogs.
func (mr *MockconnMockRecorder) SubscribeFilterLogs(ctx, q, ch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeFilterLogs", reflect.TypeOf((*Mockconn)(nil).SubscribeFilterLogs), ctx, q, ch)
}

// SuggestGasPrice mocks base method.
func (m *Mockconn) SuggestGasPrice(ctx context.Context) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SuggestGasPrice", ctx)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SuggestGasPrice indicates an expected call of SuggestGasPrice.
func (mr *MockconnMockRecorder) SuggestGasPrice(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuggestGasPrice", reflect.TypeOf((*Mockconn)(nil).SuggestGasPrice), ctx)
}

// SuggestGasTipCap mocks base method.
func (m *Mockconn) SuggestGasTipCap(ctx context.Context) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SuggestGasTipCap", ctx)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SuggestGasTipCap indicates an expected call of SuggestGasTipCap.
func (mr *MockconnMockRecorder) SuggestGasTipCap(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuggestGasTipCap", reflect.TypeOf((*Mockconn)(nil).SuggestGasTipCap), ctx)
}

// TransactionReceipt mocks base method.
func (m *Mockconn) TransactionReceipt(ctx context.Context, txHash common.Hash) (*types.Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionReceipt", ctx, txHash)
	ret0, _ := ret[0].(*types.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransactionReceipt indicates an expected call of TransactionReceipt.
func (mr *MockconnMockRecorder) TransactionReceipt(ctx, txHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionReceipt", reflect.TypeOf((*Mockconn)(nil).TransactionReceipt), ctx, txHash)
}

// Mockmetrics is a mock of metrics interface.
type Mockmetrics struct {
	ctrl     *gomock.Controller
	recorder *MockmetricsMockRecorder
	isgomock struct{}
}

// MockmetricsMockRecorder is the mock recorder for Mockmetrics.
type MockmetricsMockRecorder struct {
	mock *Mockmetrics
}

// NewMockmetrics creates a new mock instance.
func NewMockmetrics(ctrl *gomock.Controller) *Mockmetrics {
	mock := &Mockmetrics{ctrl: ctrl}
	mock.recorder = &MockmetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockmetrics) EXPECT() *MockmetricsMockRecorder {
	return m.recorder
}

// ObserveCommitValsetHeaderParams mocks base method.
func (m *Mockmetrics) ObserveCommitValsetHeaderParams(chainID, gasUsed uint64, effectiveGasPrice *big.Int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveCommitValsetHeaderParams", chainID, gasUsed, effectiveGasPrice)
}

// ObserveCommitValsetHeaderParams indicates an expected call of ObserveCommitValsetHeaderParams.
func (mr *MockmetricsMockRecorder) ObserveCommitValsetHeaderParams(chainID, gasUsed, effectiveGasPrice any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveCommitValsetHeaderParams", reflect.TypeOf((*Mockmetrics)(nil).ObserveCommitValsetHeaderParams), chainID, gasUsed, effectiveGasPrice)
}

// ObserveEVMMethodCall mocks base method.
func (m *Mockmetrics) ObserveEVMMethodCall(method string, chainID uint64, status string, d time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveEVMMethodCall", method, chainID, status, d)
}

// ObserveEVMMethodCall indicates an expected call of ObserveEVMMethodCall.
func (mr *MockmetricsMockRecorder) ObserveEVMMethodCall(method, chainID, status, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveEVMMethodCall", reflect.TypeOf((*Mockmetrics)(nil).ObserveEVMMethodCall), method, chainID, status, d)
}

// MockkeyProvider is a mock of keyProvider interface.
type MockkeyProvider struct {
	ctrl     *gomock.Controller
	recorder *MockkeyProviderMockRecorder
	isgomock struct{}
}

// MockkeyProviderMockRecorder is the mock recorder for MockkeyProvider.
type MockkeyProviderMockRecorder struct {
	mock *MockkeyProvider
}

// NewMockkeyProvider creates a new mock instance.
func NewMockkeyProvider(ctrl *gomock.Controller) *MockkeyProvider {
	mock := &MockkeyProvider{ctrl: ctrl}
	mock.recorder = &MockkeyProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockkeyProvider) EXPECT() *MockkeyProviderMockRecorder {
	return m.recorder
}

// GetPrivateKeyByNamespaceTypeId mocks base method.
func (m *MockkeyProvider) GetPrivateKeyByNamespaceTypeId(namespace string, keyType entity.KeyType, id int) (crypto.PrivateKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivateKeyByNamespaceTypeId", namespace, keyType, id)
	ret0, _ := ret[0].(crypto.PrivateKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrivateKeyByNamespaceTypeId indicates an expected call of GetPrivateKeyByNamespaceTypeId.
func (mr *MockkeyProviderMockRecorder) GetPrivateKeyByNamespaceTypeId(namespace, keyType, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrivateKeyByNamespaceTypeId", reflect.TypeOf((*MockkeyProvider)(nil).GetPrivateKeyByNamespaceTypeId), namespace, keyType, id)
}

// MockdriverContract is a mock of driverContract interface.
type MockdriverContract struct {
	ctrl     *gomock.Controller
	recorder *MockdriverContractMockRecorder
	isgomock struct{}
}

// MockdriverContractMockRecorder is the mock recorder for MockdriverContract.
type MockdriverContractMockRecorder struct {
	mock *MockdriverContract
}

// NewMockdriverContract creates a new mock instance.
func NewMockdriverContract(ctrl *gomock.Controller) *MockdriverContract {
	mock := &MockdriverContract{ctrl: ctrl}
	mock.recorder = &MockdriverContractMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdriverContract) EXPECT() *MockdriverContractMockRecorder {
	return m.recorder
}

// AddSettlement mocks base method.
func (m *MockdriverContract) AddSettlement(opts *bind.TransactOpts, settlement gen.IValSetDriverCrossChainAddress) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSettlement", opts, settlement)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddSettlement indicates an expected call of AddSettlement.
func (mr *MockdriverContractMockRecorder) AddSettlement(opts, settlement any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSettlement", reflect.TypeOf((*MockdriverContract)(nil).AddSettlement), opts, settlement)
}

// GetConfigAt mocks base method.
func (m *MockdriverContract) GetConfigAt(opts *bind.CallOpts, timestamp *big.Int) (gen.IValSetDriverConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigAt", opts, timestamp)
	ret0, _ := ret[0].(gen.IValSetDriverConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigAt indicates an expected call of GetConfigAt.
func (mr *MockdriverContractMockRecorder) GetConfigAt(opts, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigAt", reflect.TypeOf((*MockdriverContract)(nil).GetConfigAt), opts, timestamp)
}

// GetCurrentEpoch mocks base method.
func (m *MockdriverContract) GetCurrentEpoch(opts *bind.CallOpts) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentEpoch", opts)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentEpoch indicates an expected call of GetCurrentEpoch.
func (mr *MockdriverContractMockRecorder) GetCurrentEpoch(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentEpoch", reflect.TypeOf((*MockdriverContract)(nil).GetCurrentEpoch), opts)
}

// GetCurrentEpochDuration mocks base method.
func (m *MockdriverContract) GetCurrentEpochDuration(opts *bind.CallOpts) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentEpochDuration", opts)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentEpochDuration indicates an expected call of GetCurrentEpochDuration.
func (mr *MockdriverContractMockRecorder) GetCurrentEpochDuration(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentEpochDuration", reflect.TypeOf((*MockdriverContract)(nil).GetCurrentEpochDuration), opts)
}

// GetEpochDuration mocks base method.
func (m *MockdriverContract) GetEpochDuration(opts *bind.CallOpts, epoch *big.Int) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpochDuration", opts, epoch)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEpochDuration indicates an expected call of GetEpochDuration.
func (mr *MockdriverContractMockRecorder) GetEpochDuration(opts, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpochDuration", reflect.TypeOf((*MockdriverContract)(nil).GetEpochDuration), opts, epoch)
}

// GetEpochStart mocks base method.
func (m *MockdriverContract) GetEpochStart(opts *bind.CallOpts, epoch *big.Int) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpochStart", opts, epoch)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEpochStart indicates an expected call of GetEpochStart.
func (mr *MockdriverContractMockRecorder) GetEpochStart(opts, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpochStart", reflect.TypeOf((*MockdriverContract)(nil).GetEpochStart), opts, epoch)
}

// NETWORK mocks base method.
func (m *MockdriverContract) NETWORK(opts *bind.CallOpts) (common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NETWORK", opts)
	ret0, _ := ret[0].(common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NETWORK indicates an expected call of NETWORK.
func (mr *MockdriverContractMockRecorder) NETWORK(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NETWORK", reflect.TypeOf((*MockdriverContract)(nil).NETWORK), opts)
}

// RemoveSettlement mocks base method.
func (m *MockdriverContract) RemoveSettlement(opts *bind.TransactOpts, settlement gen.IValSetDriverCrossChainAddress) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSettlement", opts, settlement)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveSettlement indicates an expected call of RemoveSettlement.
func (mr *MockdriverContractMockRecorder) RemoveSettlement(opts, settlement any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSettlement", reflect.TypeOf((*MockdriverContract)(nil).RemoveSettlement), opts, settlement)
}

// SUBNETWORK mocks base method.
func (m *MockdriverContract) SUBNETWORK(opts *bind.CallOpts) ([32]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SUBNETWORK", opts)
	ret0, _ := ret[0].([32]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SUBNETWORK indicates an expected call of SUBNETWORK.
func (mr *MockdriverContractMockRecorder) SUBNETWORK(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SUBNETWORK", reflect.TypeOf((*MockdriverContract)(nil).SUBNETWORK), opts)
}

// MocksettlementContract is a mock of settlementContract interface.
type MocksettlementContract struct {
	ctrl     *gomock.Controller
	recorder *MocksettlementContractMockRecorder
	isgomock struct{}
}

// MocksettlementContractMockRecorder is the mock recorder for MocksettlementContract.
type MocksettlementContractMockRecorder struct {
	mock *MocksettlementContract
}

// NewMocksettlementContract creates a new mock instance.
func NewMocksettlementContract(ctrl *gomock.Controller) *MocksettlementContract {
	mock := &MocksettlementContract{ctrl: ctrl}
	mock.recorder = &MocksettlementContractMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksettlementContract) EXPECT() *MocksettlementContractMockRecorder {
	return m.recorder
}

// CommitValSetHeader mocks base method.
func (m *MocksettlementContract) CommitValSetHeader(opts *bind.TransactOpts, header gen.ISettlementValSetHeader, extraData []gen.ISettlementExtraData, proof []byte) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitValSetHeader", opts, header, extraData, proof)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitValSetHeader indicates an expected call of CommitValSetHeader.
func (mr *MocksettlementContractMockRecorder) CommitValSetHeader(opts, header, extraData, proof any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitValSetHeader", reflect.TypeOf((*MocksettlementContract)(nil).CommitValSetHeader), opts, header, extraData, proof)
}

// Eip712Domain mocks base method.
func (m *MocksettlementContract) Eip712Domain(opts *bind.CallOpts) (entity.Eip712Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Eip712Domain", opts)
	ret0, _ := ret[0].(entity.Eip712Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Eip712Domain indicates an expected call of Eip712Domain.
func (mr *MocksettlementContractMockRecorder) Eip712Domain(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Eip712Domain", reflect.TypeOf((*MocksettlementContract)(nil).Eip712Domain), opts)
}

// GetCaptureTimestampFromValSetHeaderAt mocks base method.
func (m *MocksettlementContract) GetCaptureTimestampFromValSetHeaderAt(opts *bind.CallOpts, epoch *big.Int) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCaptureTimestampFromValSetHeaderAt", opts, epoch)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCaptureTimestampFromValSetHeaderAt indicates an expected call of GetCaptureTimestampFromValSetHeaderAt.
func (mr *MocksettlementContractMockRecorder) GetCaptureTimestampFromValSetHeaderAt(opts, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCaptureTimestampFromValSetHeaderAt", reflect.TypeOf((*MocksettlementContract)(nil).GetCaptureTimestampFromValSetHeaderAt), opts, epoch)
}

// GetLastCommittedHeaderEpoch mocks base method.
func (m *MocksettlementContract) GetLastCommittedHeaderEpoch(opts *bind.CallOpts) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastCommittedHeaderEpoch", opts)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastCommittedHeaderEpoch indicates an expected call of GetLastCommittedHeaderEpoch.
func (mr *MocksettlementContractMockRecorder) GetLastCommittedHeaderEpoch(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastCommittedHeaderEpoch", reflect.TypeOf((*MocksettlementContract)(nil).GetLastCommittedHeaderEpoch), opts)
}

// GetValSetHeader mocks base method.
func (m *MocksettlementContract) GetValSetHeader(opts *bind.CallOpts) (gen.ISettlementValSetHeader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValSetHeader", opts)
	ret0, _ := ret[0].(gen.ISettlementValSetHeader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValSetHeader indicates an expected call of GetValSetHeader.
func (mr *MocksettlementContractMockRecorder) GetValSetHeader(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValSetHeader", reflect.TypeOf((*MocksettlementContract)(nil).GetValSetHeader), opts)
}

// GetValSetHeaderAt mocks base method.
func (m *MocksettlementContract) GetValSetHeaderAt(opts *bind.CallOpts, epoch *big.Int) (gen.ISettlementValSetHeader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValSetHeaderAt", opts, epoch)
	ret0, _ := ret[0].(gen.ISettlementValSetHeader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValSetHeaderAt indicates an expected call of GetValSetHeaderAt.
func (mr *MocksettlementContractMockRecorder) GetValSetHeaderAt(opts, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValSetHeaderAt", reflect.TypeOf((*MocksettlementContract)(nil).GetValSetHeaderAt), opts, epoch)
}

// GetValSetHeaderHash mocks base method.
func (m *MocksettlementContract) GetValSetHeaderHash(opts *bind.CallOpts) ([32]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValSetHeaderHash", opts)
	ret0, _ := ret[0].([32]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValSetHeaderHash indicates an expected call of GetValSetHeaderHash.
func (mr *MocksettlementContractMockRecorder) GetValSetHeaderHash(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValSetHeaderHash", reflect.TypeOf((*MocksettlementContract)(nil).GetValSetHeaderHash), opts)
}

// GetValSetHeaderHashAt mocks base method.
func (m *MocksettlementContract) GetValSetHeaderHashAt(opts *bind.CallOpts, epoch *big.Int) ([32]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValSetHeaderHashAt", opts, epoch)
	ret0, _ := ret[0].([32]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValSetHeaderHashAt indicates an expected call of GetValSetHeaderHashAt.
func (mr *MocksettlementContractMockRecorder) GetValSetHeaderHashAt(opts, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValSetHeaderHashAt", reflect.TypeOf((*MocksettlementContract)(nil).GetValSetHeaderHashAt), opts, epoch)
}

// IsValSetHeaderCommittedAt mocks base method.
func (m *MocksettlementContract) IsValSetHeaderCommittedAt(opts *bind.CallOpts, epoch *big.Int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValSetHeaderCommittedAt", opts, epoch)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsValSetHeaderCommittedAt indicates an expected call of IsValSetHeaderCommittedAt.
func (mr *MocksettlementContractMockRecorder) IsValSetHeaderCommittedAt(opts, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValSetHeaderCommittedAt", reflect.TypeOf((*MocksettlementContract)(nil).IsValSetHeaderCommittedAt), opts, epoch)
}

// SetGenesis mocks base method.
func (m *MocksettlementContract) SetGenesis(opts *bind.TransactOpts, valSetHeader gen.ISettlementValSetHeader, extraData []gen.ISettlementExtraData) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGenesis", opts, valSetHeader, extraData)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetGenesis indicates an expected call of SetGenesis.
func (mr *MocksettlementContractMockRecorder) SetGenesis(opts, valSetHeader, extraData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGenesis", reflect.TypeOf((*MocksettlementContract)(nil).SetGenesis), opts, valSetHeader, extraData)
}

// VerifyQuorumSigAt mocks base method.
func (m *MocksettlementContract) VerifyQuorumSigAt(opts *bind.CallOpts, message []byte, keyTag uint8, quorumThreshold *big.Int, proof []byte, epoch *big.Int, hint []byte) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyQuorumSigAt", opts, message, keyTag, quorumThreshold, proof, epoch, hint)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyQuorumSigAt indicates an expected call of VerifyQuorumSigAt.
func (mr *MocksettlementContractMockRecorder) VerifyQuorumSigAt(opts, message, keyTag, quorumThreshold, proof, epoch, hint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyQuorumSigAt", reflect.TypeOf((*MocksettlementContract)(nil).VerifyQuorumSigAt), opts, message, keyTag, quorumThreshold, proof, epoch, hint)
}

// MockvotingPowerProviderContract is a mock of votingPowerProviderContract interface.
type MockvotingPowerProviderContract struct {
	ctrl     *gomock.Controller
	recorder *MockvotingPowerProviderContractMockRecorder
	isgomock struct{}
}

// MockvotingPowerProviderContractMockRecorder is the mock recorder for MockvotingPowerProviderContract.
type MockvotingPowerProviderContractMockRecorder struct {
	mock *MockvotingPowerProviderContract
}

// NewMockvotingPowerProviderContract creates a new mock instance.
func NewMockvotingPowerProviderContract(ctrl *gomock.Controller) *MockvotingPowerProviderContract {
	mock := &MockvotingPowerProviderContract{ctrl: ctrl}
	mock.recorder = &MockvotingPowerProviderContractMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvotingPowerProviderContract) EXPECT() *MockvotingPowerProviderContractMockRecorder {
	return m.recorder
}

// Eip712Domain mocks base method.
func (m *MockvotingPowerProviderContract) Eip712Domain(opts *bind.CallOpts) (entity.Eip712Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Eip712Domain", opts)
	ret0, _ := ret[0].(entity.Eip712Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Eip712Domain indicates an expected call of Eip712Domain.
func (mr *MockvotingPowerProviderContractMockRecorder) Eip712Domain(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Eip712Domain", reflect.TypeOf((*MockvotingPowerProviderContract)(nil).Eip712Domain), opts)
}

// GetOperatorsAt mocks base method.
func (m *MockvotingPowerProviderContract) GetOperatorsAt(opts *bind.CallOpts, timestamp *big.Int) ([]common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperatorsAt", opts, timestamp)
	ret0, _ := ret[0].([]common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOperatorsAt indicates an expected call of GetOperatorsAt.
func (mr *MockvotingPowerProviderContractMockRecorder) GetOperatorsAt(opts, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperatorsAt", reflect.TypeOf((*MockvotingPowerProviderContract)(nil).GetOperatorsAt), opts, timestamp)
}

// GetVotingPowersAt mocks base method.
func (m *MockvotingPowerProviderContract) GetVotingPowersAt(opts *bind.CallOpts, extraData [][]byte, timestamp *big.Int) ([]gen.IVotingPowerProviderOperatorVotingPower, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVotingPowersAt", opts, extraData, timestamp)
	ret0, _ := ret[0].([]gen.IVotingPowerProviderOperatorVotingPower)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVotingPowersAt indicates an expected call of GetVotingPowersAt.
func (mr *MockvotingPowerProviderContractMockRecorder) GetVotingPowersAt(opts, extraData, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVotingPowersAt", reflect.TypeOf((*MockvotingPowerProviderContract)(nil).GetVotingPowersAt), opts, extraData, timestamp)
}

// Nonces mocks base method.
func (m *MockvotingPowerProviderContract) Nonces(opts *bind.CallOpts, owner common.Address) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Nonces", opts, owner)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Nonces indicates an expected call of Nonces.
func (mr *MockvotingPowerProviderContractMockRecorder) Nonces(opts, owner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Nonces", reflect.TypeOf((*MockvotingPowerProviderContract)(nil).Nonces), opts, owner)
}

// MockvotingPowerProviderTransactor is a mock of votingPowerProviderTransactor interface.
type MockvotingPowerProviderTransactor struct {
	ctrl     *gomock.Controller
	recorder *MockvotingPowerProviderTransactorMockRecorder
	isgomock struct{}
}

// MockvotingPowerProviderTransactorMockRecorder is the mock recorder for MockvotingPowerProviderTransactor.
type MockvotingPowerProviderTransactorMockRecorder struct {
	mock *MockvotingPowerProviderTransactor
}

// NewMockvotingPowerProviderTransactor creates a new mock instance.
func NewMockvotingPowerProviderTransactor(ctrl *gomock.Controller) *MockvotingPowerProviderTransactor {
	mock := &MockvotingPowerProviderTransactor{ctrl: ctrl}
	mock.recorder = &MockvotingPowerProviderTransactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvotingPowerProviderTransactor) EXPECT() *MockvotingPowerProviderTransactorMockRecorder {
	return m.recorder
}

// InvalidateOldSignatures mocks base method.
func (m *MockvotingPowerProviderTransactor) InvalidateOldSignatures(opts *bind.TransactOpts) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateOldSignatures", opts)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InvalidateOldSignatures indicates an expected call of InvalidateOldSignatures.
func (mr *MockvotingPowerProviderTransactorMockRecorder) InvalidateOldSignatures(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateOldSignatures", reflect.TypeOf((*MockvotingPowerProviderTransactor)(nil).InvalidateOldSignatures), opts)
}

// RegisterOperator mocks base method.
func (m *MockvotingPowerProviderTransactor) RegisterOperator(opts *bind.TransactOpts) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterOperator", opts)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterOperator indicates an expected call of RegisterOperator.
func (mr *MockvotingPowerProviderTransactorMockRecorder) RegisterOperator(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterOperator", reflect.TypeOf((*MockvotingPowerProviderTransactor)(nil).RegisterOperator), opts)
}

// UnregisterOperator mocks base method.
func (m *MockvotingPowerProviderTransactor) UnregisterOperator(opts *bind.TransactOpts) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnregisterOperator", opts)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnregisterOperator indicates an expected call of UnregisterOperator.
func (mr *MockvotingPowerProviderTransactorMockRecorder) UnregisterOperator(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterOperator", reflect.TypeOf((*MockvotingPowerProviderTransactor)(nil).UnregisterOperator), opts)
}

// MockkeyRegistryContract is a mock of keyRegistryContract interface.
type MockkeyRegistryContract struct {
	ctrl     *gomock.Controller
	recorder *MockkeyRegistryContractMockRecorder
	isgomock struct{}
}

// MockkeyRegistryContractMockRecorder is the mock recorder for MockkeyRegistryContract.
type MockkeyRegistryContractMockRecorder struct {
	mock *MockkeyRegistryContract
}

// NewMockkeyRegistryContract creates a new mock instance.
func NewMockkeyRegistryContract(ctrl *gomock.Controller) *MockkeyRegistryContract {
	mock := &MockkeyRegistryContract{ctrl: ctrl}
	mock.recorder = &MockkeyRegistryContractMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockkeyRegistryContract) EXPECT() *MockkeyRegistryContractMockRecorder {
	return m.recorder
}

// GetKeysAt mocks base method.
func (m *MockkeyRegistryContract) GetKeysAt(opts *bind.CallOpts, timestamp *big.Int) ([]gen.IKeyRegistryOperatorWithKeys, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeysAt", opts, timestamp)
	ret0, _ := ret[0].([]gen.IKeyRegistryOperatorWithKeys)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeysAt indicates an expected call of GetKeysAt.
func (mr *MockkeyRegistryContractMockRecorder) GetKeysAt(opts, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeysAt", reflect.TypeOf((*MockkeyRegistryContract)(nil).GetKeysAt), opts, timestamp)
}

// GetKeysOperatorsAt mocks base method.
func (m *MockkeyRegistryContract) GetKeysOperatorsAt(opts *bind.CallOpts, timestamp *big.Int) ([]common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeysOperatorsAt", opts, timestamp)
	ret0, _ := ret[0].([]common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeysOperatorsAt indicates an expected call of GetKeysOperatorsAt.
func (mr *MockkeyRegistryContractMockRecorder) GetKeysOperatorsAt(opts, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeysOperatorsAt", reflect.TypeOf((*MockkeyRegistryContract)(nil).GetKeysOperatorsAt), opts, timestamp)
}

// SetKey mocks base method.
func (m *MockkeyRegistryContract) SetKey(opts *bind.TransactOpts, tag uint8, key, signature, extraData []byte) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetKey", opts, tag, key, signature, extraData)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetKey indicates an expected call of SetKey.
func (mr *MockkeyRegistryContractMockRecorder) SetKey(opts, tag, key, signature, extraData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKey", reflect.TypeOf((*MockkeyRegistryContract)(nil).SetKey), opts, tag, key, signature, extraData)
}

// MockoperatorRegistryContract is a mock of operatorRegistryContract interface.
type MockoperatorRegistryContract struct {
	ctrl     *gomock.Controller
	recorder *MockoperatorRegistryContractMockRecorder
	isgomock struct{}
}

// MockoperatorRegistryContractMockRecorder is the mock recorder for MockoperatorRegistryContract.
type MockoperatorRegistryContractMockRecorder struct {
	mock *MockoperatorRegistryContract
}

// NewMockoperatorRegistryContract creates a new mock instance.
func NewMockoperatorRegistryContract(ctrl *gomock.Controller) *MockoperatorRegistryContract {
	mock := &MockoperatorRegistryContract{ctrl: ctrl}
	mock.recorder = &MockoperatorRegistryContractMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoperatorRegistryContract) EXPECT() *MockoperatorRegistryContractMockRecorder {
	return m.recorder
}

// RegisterOperator mocks base method.
func (m *MockoperatorRegistryContract) RegisterOperator(opts *bind.TransactOpts) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterOperator", opts)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterOperator indicates an expected call of RegisterOperator.
func (mr *MockoperatorRegistryContractMockRecorder) RegisterOperator(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterOperator", reflect.TypeOf((*MockoperatorRegistryContract)(nil).RegisterOperator), opts)
}
