// Code generated by generate-votingpower-server-types. DO NOT EDIT.
package v1

import (
	votingpowerv1 "github.com/symbioticfi/relay/internal/gen/votingpower/v1"
)

// Exported types for server usage

// Request types
type GetVotingPowersAtRequest = votingpowerv1.GetVotingPowersAtRequest

// Response types
type GetVotingPowersAtResponse = votingpowerv1.GetVotingPowersAtResponse

// Data types
type OperatorVotingPower = votingpowerv1.OperatorVotingPower
