// Code generated by MockGen. DO NOT EDIT.
// Source: deriver.go
//
// Generated by this command:
//
//	mockgen -source=deriver.go -destination=mocks/deriver.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	big "math/big"
	entity "middleware-offchain/internal/entity"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockethClient is a mock of ethClient interface.
type MockethClient struct {
	ctrl     *gomock.Controller
	recorder *MockethClientMockRecorder
	isgomock struct{}
}

// MockethClientMockRecorder is the mock recorder for MockethClient.
type MockethClientMockRecorder struct {
	mock *MockethClient
}

// NewMockethClient creates a new mock instance.
func NewMockethClient(ctrl *gomock.Controller) *MockethClient {
	mock := &MockethClient{ctrl: ctrl}
	mock.recorder = &MockethClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockethClient) EXPECT() *MockethClientMockRecorder {
	return m.recorder
}

// GetCaptureTimestamp mocks base method.
func (m *MockethClient) GetCaptureTimestamp(ctx context.Context) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCaptureTimestamp", ctx)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCaptureTimestamp indicates an expected call of GetCaptureTimestamp.
func (mr *MockethClientMockRecorder) GetCaptureTimestamp(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCaptureTimestamp", reflect.TypeOf((*MockethClient)(nil).GetCaptureTimestamp), ctx)
}

// GetCurrentEpoch mocks base method.
func (m *MockethClient) GetCurrentEpoch(ctx context.Context) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentEpoch", ctx)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentEpoch indicates an expected call of GetCurrentEpoch.
func (mr *MockethClientMockRecorder) GetCurrentEpoch(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentEpoch", reflect.TypeOf((*MockethClient)(nil).GetCurrentEpoch), ctx)
}

// GetCurrentValsetTimestamp mocks base method.
func (m *MockethClient) GetCurrentValsetTimestamp(ctx context.Context) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentValsetTimestamp", ctx)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentValsetTimestamp indicates an expected call of GetCurrentValsetTimestamp.
func (mr *MockethClientMockRecorder) GetCurrentValsetTimestamp(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentValsetTimestamp", reflect.TypeOf((*MockethClient)(nil).GetCurrentValsetTimestamp), ctx)
}

// GetEip712Domain mocks base method.
func (m *MockethClient) GetEip712Domain(ctx context.Context) (entity.Eip712Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEip712Domain", ctx)
	ret0, _ := ret[0].(entity.Eip712Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEip712Domain indicates an expected call of GetEip712Domain.
func (mr *MockethClientMockRecorder) GetEip712Domain(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEip712Domain", reflect.TypeOf((*MockethClient)(nil).GetEip712Domain), ctx)
}

// GetKeys mocks base method.
func (m *MockethClient) GetKeys(ctx context.Context, address common.Address, timestamp *big.Int) ([]entity.OperatorWithKeys, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeys", ctx, address, timestamp)
	ret0, _ := ret[0].([]entity.OperatorWithKeys)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeys indicates an expected call of GetKeys.
func (mr *MockethClientMockRecorder) GetKeys(ctx, address, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeys", reflect.TypeOf((*MockethClient)(nil).GetKeys), ctx, address, timestamp)
}

// GetMasterConfig mocks base method.
func (m *MockethClient) GetMasterConfig(ctx context.Context, timestamp *big.Int) (entity.MasterConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMasterConfig", ctx, timestamp)
	ret0, _ := ret[0].(entity.MasterConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMasterConfig indicates an expected call of GetMasterConfig.
func (mr *MockethClientMockRecorder) GetMasterConfig(ctx, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMasterConfig", reflect.TypeOf((*MockethClient)(nil).GetMasterConfig), ctx, timestamp)
}

// GetRequiredKeyTag mocks base method.
func (m *MockethClient) GetRequiredKeyTag(ctx context.Context, timestamp *big.Int) (uint8, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequiredKeyTag", ctx, timestamp)
	ret0, _ := ret[0].(uint8)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRequiredKeyTag indicates an expected call of GetRequiredKeyTag.
func (mr *MockethClientMockRecorder) GetRequiredKeyTag(ctx, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequiredKeyTag", reflect.TypeOf((*MockethClient)(nil).GetRequiredKeyTag), ctx, timestamp)
}

// GetSubnetwork mocks base method.
func (m *MockethClient) GetSubnetwork(ctx context.Context) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubnetwork", ctx)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubnetwork indicates an expected call of GetSubnetwork.
func (mr *MockethClientMockRecorder) GetSubnetwork(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubnetwork", reflect.TypeOf((*MockethClient)(nil).GetSubnetwork), ctx)
}

// GetValSetConfig mocks base method.
func (m *MockethClient) GetValSetConfig(ctx context.Context, timestamp *big.Int) (entity.ValSetConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValSetConfig", ctx, timestamp)
	ret0, _ := ret[0].(entity.ValSetConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValSetConfig indicates an expected call of GetValSetConfig.
func (mr *MockethClientMockRecorder) GetValSetConfig(ctx, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValSetConfig", reflect.TypeOf((*MockethClient)(nil).GetValSetConfig), ctx, timestamp)
}

// GetVotingPowers mocks base method.
func (m *MockethClient) GetVotingPowers(ctx context.Context, address common.Address, timestamp *big.Int) ([]entity.OperatorVotingPower, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVotingPowers", ctx, address, timestamp)
	ret0, _ := ret[0].([]entity.OperatorVotingPower)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVotingPowers indicates an expected call of GetVotingPowers.
func (mr *MockethClientMockRecorder) GetVotingPowers(ctx, address, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVotingPowers", reflect.TypeOf((*MockethClient)(nil).GetVotingPowers), ctx, address, timestamp)
}
