// Code generated by MockGen. DO NOT EDIT.
// Source: signer_app.go
//
// Generated by this command:
//
//	mockgen -source=signer_app.go -destination=mocks/signer_app.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	common "github.com/ethereum/go-ethereum/common"
	entity "github.com/symbioticfi/relay/symbiotic/entity"
	crypto "github.com/symbioticfi/relay/symbiotic/usecase/crypto"
	gomock "go.uber.org/mock/gomock"
)

// Mockrepo is a mock of repo interface.
type Mockrepo struct {
	ctrl     *gomock.Controller
	recorder *MockrepoMockRecorder
	isgomock struct{}
}

// MockrepoMockRecorder is the mock recorder for Mockrepo.
type MockrepoMockRecorder struct {
	mock *Mockrepo
}

// NewMockrepo creates a new mock instance.
func NewMockrepo(ctrl *gomock.Controller) *Mockrepo {
	mock := &Mockrepo{ctrl: ctrl}
	mock.recorder = &MockrepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepo) EXPECT() *MockrepoMockRecorder {
	return m.recorder
}

// GetSignaturePending mocks base method.
func (m *Mockrepo) GetSignaturePending(ctx context.Context, limit int) ([]common.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSignaturePending", ctx, limit)
	ret0, _ := ret[0].([]common.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSignaturePending indicates an expected call of GetSignaturePending.
func (mr *MockrepoMockRecorder) GetSignaturePending(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSignaturePending", reflect.TypeOf((*Mockrepo)(nil).GetSignaturePending), ctx, limit)
}

// GetSignatureRequest mocks base method.
func (m *Mockrepo) GetSignatureRequest(ctx context.Context, requestID common.Hash) (entity.SignatureRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSignatureRequest", ctx, requestID)
	ret0, _ := ret[0].(entity.SignatureRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSignatureRequest indicates an expected call of GetSignatureRequest.
func (mr *MockrepoMockRecorder) GetSignatureRequest(ctx, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSignatureRequest", reflect.TypeOf((*Mockrepo)(nil).GetSignatureRequest), ctx, requestID)
}

// GetValidatorSetByEpoch mocks base method.
func (m *Mockrepo) GetValidatorSetByEpoch(ctx context.Context, epoch entity.Epoch) (entity.ValidatorSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidatorSetByEpoch", ctx, epoch)
	ret0, _ := ret[0].(entity.ValidatorSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidatorSetByEpoch indicates an expected call of GetValidatorSetByEpoch.
func (mr *MockrepoMockRecorder) GetValidatorSetByEpoch(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidatorSetByEpoch", reflect.TypeOf((*Mockrepo)(nil).GetValidatorSetByEpoch), ctx, epoch)
}

// RemoveSignaturePending mocks base method.
func (m *Mockrepo) RemoveSignaturePending(ctx context.Context, epoch entity.Epoch, requestID common.Hash) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSignaturePending", ctx, epoch, requestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveSignaturePending indicates an expected call of RemoveSignaturePending.
func (mr *MockrepoMockRecorder) RemoveSignaturePending(ctx, epoch, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSignaturePending", reflect.TypeOf((*Mockrepo)(nil).RemoveSignaturePending), ctx, epoch, requestID)
}

// SaveSignatureRequest mocks base method.
func (m *Mockrepo) SaveSignatureRequest(ctx context.Context, requestID common.Hash, req entity.SignatureRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSignatureRequest", ctx, requestID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSignatureRequest indicates an expected call of SaveSignatureRequest.
func (mr *MockrepoMockRecorder) SaveSignatureRequest(ctx, requestID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSignatureRequest", reflect.TypeOf((*Mockrepo)(nil).SaveSignatureRequest), ctx, requestID, req)
}

// Mockp2pService is a mock of p2pService interface.
type Mockp2pService struct {
	ctrl     *gomock.Controller
	recorder *Mockp2pServiceMockRecorder
	isgomock struct{}
}

// Mockp2pServiceMockRecorder is the mock recorder for Mockp2pService.
type Mockp2pServiceMockRecorder struct {
	mock *Mockp2pService
}

// NewMockp2pService creates a new mock instance.
func NewMockp2pService(ctrl *gomock.Controller) *Mockp2pService {
	mock := &Mockp2pService{ctrl: ctrl}
	mock.recorder = &Mockp2pServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockp2pService) EXPECT() *Mockp2pServiceMockRecorder {
	return m.recorder
}

// BroadcastSignatureGeneratedMessage mocks base method.
func (m *Mockp2pService) BroadcastSignatureGeneratedMessage(ctx context.Context, msg entity.SignatureExtended) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BroadcastSignatureGeneratedMessage", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// BroadcastSignatureGeneratedMessage indicates an expected call of BroadcastSignatureGeneratedMessage.
func (mr *Mockp2pServiceMockRecorder) BroadcastSignatureGeneratedMessage(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastSignatureGeneratedMessage", reflect.TypeOf((*Mockp2pService)(nil).BroadcastSignatureGeneratedMessage), ctx, msg)
}

// MockkeyProvider is a mock of keyProvider interface.
type MockkeyProvider struct {
	ctrl     *gomock.Controller
	recorder *MockkeyProviderMockRecorder
	isgomock struct{}
}

// MockkeyProviderMockRecorder is the mock recorder for MockkeyProvider.
type MockkeyProviderMockRecorder struct {
	mock *MockkeyProvider
}

// NewMockkeyProvider creates a new mock instance.
func NewMockkeyProvider(ctrl *gomock.Controller) *MockkeyProvider {
	mock := &MockkeyProvider{ctrl: ctrl}
	mock.recorder = &MockkeyProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockkeyProvider) EXPECT() *MockkeyProviderMockRecorder {
	return m.recorder
}

// GetPrivateKey mocks base method.
func (m *MockkeyProvider) GetPrivateKey(keyTag entity.KeyTag) (crypto.PrivateKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivateKey", keyTag)
	ret0, _ := ret[0].(crypto.PrivateKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrivateKey indicates an expected call of GetPrivateKey.
func (mr *MockkeyProviderMockRecorder) GetPrivateKey(keyTag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrivateKey", reflect.TypeOf((*MockkeyProvider)(nil).GetPrivateKey), keyTag)
}

// Mockmetrics is a mock of metrics interface.
type Mockmetrics struct {
	ctrl     *gomock.Controller
	recorder *MockmetricsMockRecorder
	isgomock struct{}
}

// MockmetricsMockRecorder is the mock recorder for Mockmetrics.
type MockmetricsMockRecorder struct {
	mock *Mockmetrics
}

// NewMockmetrics creates a new mock instance.
func NewMockmetrics(ctrl *gomock.Controller) *Mockmetrics {
	mock := &Mockmetrics{ctrl: ctrl}
	mock.recorder = &MockmetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockmetrics) EXPECT() *MockmetricsMockRecorder {
	return m.recorder
}

// ObserveAppSignDuration mocks base method.
func (m *Mockmetrics) ObserveAppSignDuration(d time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveAppSignDuration", d)
}

// ObserveAppSignDuration indicates an expected call of ObserveAppSignDuration.
func (mr *MockmetricsMockRecorder) ObserveAppSignDuration(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveAppSignDuration", reflect.TypeOf((*Mockmetrics)(nil).ObserveAppSignDuration), d)
}

// ObservePKSignDuration mocks base method.
func (m *Mockmetrics) ObservePKSignDuration(d time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObservePKSignDuration", d)
}

// ObservePKSignDuration indicates an expected call of ObservePKSignDuration.
func (mr *MockmetricsMockRecorder) ObservePKSignDuration(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObservePKSignDuration", reflect.TypeOf((*Mockmetrics)(nil).ObservePKSignDuration), d)
}

// MockentityProcessor is a mock of entityProcessor interface.
type MockentityProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockentityProcessorMockRecorder
	isgomock struct{}
}

// MockentityProcessorMockRecorder is the mock recorder for MockentityProcessor.
type MockentityProcessorMockRecorder struct {
	mock *MockentityProcessor
}

// NewMockentityProcessor creates a new mock instance.
func NewMockentityProcessor(ctrl *gomock.Controller) *MockentityProcessor {
	mock := &MockentityProcessor{ctrl: ctrl}
	mock.recorder = &MockentityProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockentityProcessor) EXPECT() *MockentityProcessorMockRecorder {
	return m.recorder
}

// ProcessAggregationProof mocks base method.
func (m *MockentityProcessor) ProcessAggregationProof(ctx context.Context, proof entity.AggregationProof) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessAggregationProof", ctx, proof)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessAggregationProof indicates an expected call of ProcessAggregationProof.
func (mr *MockentityProcessorMockRecorder) ProcessAggregationProof(ctx, proof any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessAggregationProof", reflect.TypeOf((*MockentityProcessor)(nil).ProcessAggregationProof), ctx, proof)
}

// ProcessSignature mocks base method.
func (m *MockentityProcessor) ProcessSignature(ctx context.Context, signature entity.SignatureExtended) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessSignature", ctx, signature)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessSignature indicates an expected call of ProcessSignature.
func (mr *MockentityProcessorMockRecorder) ProcessSignature(ctx, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessSignature", reflect.TypeOf((*MockentityProcessor)(nil).ProcessSignature), ctx, signature)
}
