// Code generated by MockGen. DO NOT EDIT.
// Source: signer_app.go
//
// Generated by this command:
//
//	mockgen -source=signer_app.go -destination=mocks/signer_app.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	common "github.com/ethereum/go-ethereum/common"
	entity "github.com/symbioticfi/relay/core/entity"
	crypto "github.com/symbioticfi/relay/core/usecase/crypto"
	gomock "go.uber.org/mock/gomock"
)

// Mockrepo is a mock of repo interface.
type Mockrepo struct {
	ctrl     *gomock.Controller
	recorder *MockrepoMockRecorder
	isgomock struct{}
}

// MockrepoMockRecorder is the mock recorder for Mockrepo.
type MockrepoMockRecorder struct {
	mock *Mockrepo
}

// NewMockrepo creates a new mock instance.
func NewMockrepo(ctrl *gomock.Controller) *Mockrepo {
	mock := &Mockrepo{ctrl: ctrl}
	mock.recorder = &MockrepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepo) EXPECT() *MockrepoMockRecorder {
	return m.recorder
}

// SaveSignatureRequest mocks base method.
func (m *Mockrepo) SaveSignatureRequest(ctx context.Context, requestID common.Hash, req entity.SignatureRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSignatureRequest", ctx, requestID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSignatureRequest indicates an expected call of SaveSignatureRequest.
func (mr *MockrepoMockRecorder) SaveSignatureRequest(ctx, requestID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSignatureRequest", reflect.TypeOf((*Mockrepo)(nil).SaveSignatureRequest), ctx, requestID, req)
}

// Mockp2pService is a mock of p2pService interface.
type Mockp2pService struct {
	ctrl     *gomock.Controller
	recorder *Mockp2pServiceMockRecorder
	isgomock struct{}
}

// Mockp2pServiceMockRecorder is the mock recorder for Mockp2pService.
type Mockp2pServiceMockRecorder struct {
	mock *Mockp2pService
}

// NewMockp2pService creates a new mock instance.
func NewMockp2pService(ctrl *gomock.Controller) *Mockp2pService {
	mock := &Mockp2pService{ctrl: ctrl}
	mock.recorder = &Mockp2pServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockp2pService) EXPECT() *Mockp2pServiceMockRecorder {
	return m.recorder
}

// BroadcastSignatureGeneratedMessage mocks base method.
func (m *Mockp2pService) BroadcastSignatureGeneratedMessage(ctx context.Context, msg entity.SignatureExtended) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BroadcastSignatureGeneratedMessage", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// BroadcastSignatureGeneratedMessage indicates an expected call of BroadcastSignatureGeneratedMessage.
func (mr *Mockp2pServiceMockRecorder) BroadcastSignatureGeneratedMessage(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastSignatureGeneratedMessage", reflect.TypeOf((*Mockp2pService)(nil).BroadcastSignatureGeneratedMessage), ctx, msg)
}

// MockkeyProvider is a mock of keyProvider interface.
type MockkeyProvider struct {
	ctrl     *gomock.Controller
	recorder *MockkeyProviderMockRecorder
	isgomock struct{}
}

// MockkeyProviderMockRecorder is the mock recorder for MockkeyProvider.
type MockkeyProviderMockRecorder struct {
	mock *MockkeyProvider
}

// NewMockkeyProvider creates a new mock instance.
func NewMockkeyProvider(ctrl *gomock.Controller) *MockkeyProvider {
	mock := &MockkeyProvider{ctrl: ctrl}
	mock.recorder = &MockkeyProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockkeyProvider) EXPECT() *MockkeyProviderMockRecorder {
	return m.recorder
}

// GetPrivateKey mocks base method.
func (m *MockkeyProvider) GetPrivateKey(keyTag entity.KeyTag) (crypto.PrivateKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivateKey", keyTag)
	ret0, _ := ret[0].(crypto.PrivateKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrivateKey indicates an expected call of GetPrivateKey.
func (mr *MockkeyProviderMockRecorder) GetPrivateKey(keyTag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrivateKey", reflect.TypeOf((*MockkeyProvider)(nil).GetPrivateKey), keyTag)
}

// MockaggProofSignal is a mock of aggProofSignal interface.
type MockaggProofSignal struct {
	ctrl     *gomock.Controller
	recorder *MockaggProofSignalMockRecorder
	isgomock struct{}
}

// MockaggProofSignalMockRecorder is the mock recorder for MockaggProofSignal.
type MockaggProofSignalMockRecorder struct {
	mock *MockaggProofSignal
}

// NewMockaggProofSignal creates a new mock instance.
func NewMockaggProofSignal(ctrl *gomock.Controller) *MockaggProofSignal {
	mock := &MockaggProofSignal{ctrl: ctrl}
	mock.recorder = &MockaggProofSignalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaggProofSignal) EXPECT() *MockaggProofSignalMockRecorder {
	return m.recorder
}

// Emit mocks base method.
func (m *MockaggProofSignal) Emit(payload entity.AggregationProof) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Emit", payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Emit indicates an expected call of Emit.
func (mr *MockaggProofSignalMockRecorder) Emit(payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Emit", reflect.TypeOf((*MockaggProofSignal)(nil).Emit), payload)
}

// Mockaggregator is a mock of aggregator interface.
type Mockaggregator struct {
	ctrl     *gomock.Controller
	recorder *MockaggregatorMockRecorder
	isgomock struct{}
}

// MockaggregatorMockRecorder is the mock recorder for Mockaggregator.
type MockaggregatorMockRecorder struct {
	mock *Mockaggregator
}

// NewMockaggregator creates a new mock instance.
func NewMockaggregator(ctrl *gomock.Controller) *Mockaggregator {
	mock := &Mockaggregator{ctrl: ctrl}
	mock.recorder = &MockaggregatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockaggregator) EXPECT() *MockaggregatorMockRecorder {
	return m.recorder
}

// Verify mocks base method.
func (m *Mockaggregator) Verify(valset entity.ValidatorSet, keyTag entity.KeyTag, aggregationProof entity.AggregationProof) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", valset, keyTag, aggregationProof)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockaggregatorMockRecorder) Verify(valset, keyTag, aggregationProof any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*Mockaggregator)(nil).Verify), valset, keyTag, aggregationProof)
}

// Mockmetrics is a mock of metrics interface.
type Mockmetrics struct {
	ctrl     *gomock.Controller
	recorder *MockmetricsMockRecorder
	isgomock struct{}
}

// MockmetricsMockRecorder is the mock recorder for Mockmetrics.
type MockmetricsMockRecorder struct {
	mock *Mockmetrics
}

// NewMockmetrics creates a new mock instance.
func NewMockmetrics(ctrl *gomock.Controller) *Mockmetrics {
	mock := &Mockmetrics{ctrl: ctrl}
	mock.recorder = &MockmetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockmetrics) EXPECT() *MockmetricsMockRecorder {
	return m.recorder
}

// ObserveAppSignDuration mocks base method.
func (m *Mockmetrics) ObserveAppSignDuration(d time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveAppSignDuration", d)
}

// ObserveAppSignDuration indicates an expected call of ObserveAppSignDuration.
func (mr *MockmetricsMockRecorder) ObserveAppSignDuration(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveAppSignDuration", reflect.TypeOf((*Mockmetrics)(nil).ObserveAppSignDuration), d)
}

// ObservePKSignDuration mocks base method.
func (m *Mockmetrics) ObservePKSignDuration(d time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObservePKSignDuration", d)
}

// ObservePKSignDuration indicates an expected call of ObservePKSignDuration.
func (mr *MockmetricsMockRecorder) ObservePKSignDuration(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObservePKSignDuration", reflect.TypeOf((*Mockmetrics)(nil).ObservePKSignDuration), d)
}

// MockentityProcessor is a mock of entityProcessor interface.
type MockentityProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockentityProcessorMockRecorder
	isgomock struct{}
}

// MockentityProcessorMockRecorder is the mock recorder for MockentityProcessor.
type MockentityProcessorMockRecorder struct {
	mock *MockentityProcessor
}

// NewMockentityProcessor creates a new mock instance.
func NewMockentityProcessor(ctrl *gomock.Controller) *MockentityProcessor {
	mock := &MockentityProcessor{ctrl: ctrl}
	mock.recorder = &MockentityProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockentityProcessor) EXPECT() *MockentityProcessorMockRecorder {
	return m.recorder
}

// ProcessAggregationProof mocks base method.
func (m *MockentityProcessor) ProcessAggregationProof(ctx context.Context, proof entity.AggregationProof) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessAggregationProof", ctx, proof)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessAggregationProof indicates an expected call of ProcessAggregationProof.
func (mr *MockentityProcessorMockRecorder) ProcessAggregationProof(ctx, proof any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessAggregationProof", reflect.TypeOf((*MockentityProcessor)(nil).ProcessAggregationProof), ctx, proof)
}

// ProcessSignature mocks base method.
func (m *MockentityProcessor) ProcessSignature(ctx context.Context, signature entity.SignatureExtended) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessSignature", ctx, signature)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessSignature indicates an expected call of ProcessSignature.
func (mr *MockentityProcessorMockRecorder) ProcessSignature(ctx, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessSignature", reflect.TypeOf((*MockentityProcessor)(nil).ProcessSignature), ctx, signature)
}
