// Code generated by MockGen. DO NOT EDIT.
// Source: valset_deriver.go
//
// Generated by this command:
//
//	mockgen -source=valset_deriver.go -destination=mocks/deriver.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entity "middleware-offchain/core/entity"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockethClient is a mock of ethClient interface.
type MockethClient struct {
	ctrl     *gomock.Controller
	recorder *MockethClientMockRecorder
	isgomock struct{}
}

// MockethClientMockRecorder is the mock recorder for MockethClient.
type MockethClientMockRecorder struct {
	mock *MockethClient
}

// NewMockethClient creates a new mock instance.
func NewMockethClient(ctrl *gomock.Controller) *MockethClient {
	mock := &MockethClient{ctrl: ctrl}
	mock.recorder = &MockethClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockethClient) EXPECT() *MockethClientMockRecorder {
	return m.recorder
}

// GetCaptureTimestamp mocks base method.
func (m *MockethClient) GetCaptureTimestamp(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCaptureTimestamp", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCaptureTimestamp indicates an expected call of GetCaptureTimestamp.
func (mr *MockethClientMockRecorder) GetCaptureTimestamp(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCaptureTimestamp", reflect.TypeOf((*MockethClient)(nil).GetCaptureTimestamp), ctx)
}

// GetConfig mocks base method.
func (m *MockethClient) GetConfig(ctx context.Context, timestamp uint64) (entity.NetworkConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", ctx, timestamp)
	ret0, _ := ret[0].(entity.NetworkConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockethClientMockRecorder) GetConfig(ctx, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockethClient)(nil).GetConfig), ctx, timestamp)
}

// GetCurrentEpoch mocks base method.
func (m *MockethClient) GetCurrentEpoch(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentEpoch", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentEpoch indicates an expected call of GetCurrentEpoch.
func (mr *MockethClientMockRecorder) GetCurrentEpoch(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentEpoch", reflect.TypeOf((*MockethClient)(nil).GetCurrentEpoch), ctx)
}

// GetCurrentValsetTimestamp mocks base method.
func (m *MockethClient) GetCurrentValsetTimestamp(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentValsetTimestamp", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentValsetTimestamp indicates an expected call of GetCurrentValsetTimestamp.
func (mr *MockethClientMockRecorder) GetCurrentValsetTimestamp(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentValsetTimestamp", reflect.TypeOf((*MockethClient)(nil).GetCurrentValsetTimestamp), ctx)
}

// GetEip712Domain mocks base method.
func (m *MockethClient) GetEip712Domain(ctx context.Context) (entity.Eip712Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEip712Domain", ctx)
	ret0, _ := ret[0].(entity.Eip712Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEip712Domain indicates an expected call of GetEip712Domain.
func (mr *MockethClientMockRecorder) GetEip712Domain(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEip712Domain", reflect.TypeOf((*MockethClient)(nil).GetEip712Domain), ctx)
}

// GetEpochStart mocks base method.
func (m *MockethClient) GetEpochStart(ctx context.Context, epoch uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpochStart", ctx, epoch)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEpochStart indicates an expected call of GetEpochStart.
func (mr *MockethClientMockRecorder) GetEpochStart(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpochStart", reflect.TypeOf((*MockethClient)(nil).GetEpochStart), ctx, epoch)
}

// GetHeaderHashAt mocks base method.
func (m *MockethClient) GetHeaderHashAt(ctx context.Context, epoch uint64) (common.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeaderHashAt", ctx, epoch)
	ret0, _ := ret[0].(common.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeaderHashAt indicates an expected call of GetHeaderHashAt.
func (mr *MockethClientMockRecorder) GetHeaderHashAt(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeaderHashAt", reflect.TypeOf((*MockethClient)(nil).GetHeaderHashAt), ctx, epoch)
}

// GetKeys mocks base method.
func (m *MockethClient) GetKeys(ctx context.Context, address entity.CrossChainAddress, timestamp uint64) ([]entity.OperatorWithKeys, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeys", ctx, address, timestamp)
	ret0, _ := ret[0].([]entity.OperatorWithKeys)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeys indicates an expected call of GetKeys.
func (mr *MockethClientMockRecorder) GetKeys(ctx, address, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeys", reflect.TypeOf((*MockethClient)(nil).GetKeys), ctx, address, timestamp)
}

// GetLastCommittedHeaderEpoch mocks base method.
func (m *MockethClient) GetLastCommittedHeaderEpoch(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastCommittedHeaderEpoch", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastCommittedHeaderEpoch indicates an expected call of GetLastCommittedHeaderEpoch.
func (mr *MockethClientMockRecorder) GetLastCommittedHeaderEpoch(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastCommittedHeaderEpoch", reflect.TypeOf((*MockethClient)(nil).GetLastCommittedHeaderEpoch), ctx)
}

// GetLatestHeaderHash mocks base method.
func (m *MockethClient) GetLatestHeaderHash(ctx context.Context) (common.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestHeaderHash", ctx)
	ret0, _ := ret[0].(common.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestHeaderHash indicates an expected call of GetLatestHeaderHash.
func (mr *MockethClientMockRecorder) GetLatestHeaderHash(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestHeaderHash", reflect.TypeOf((*MockethClient)(nil).GetLatestHeaderHash), ctx)
}

// GetNetworkAddress mocks base method.
func (m *MockethClient) GetNetworkAddress(ctx context.Context) (*common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkAddress", ctx)
	ret0, _ := ret[0].(*common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkAddress indicates an expected call of GetNetworkAddress.
func (mr *MockethClientMockRecorder) GetNetworkAddress(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkAddress", reflect.TypeOf((*MockethClient)(nil).GetNetworkAddress), ctx)
}

// GetPreviousHeaderHashAt mocks base method.
func (m *MockethClient) GetPreviousHeaderHashAt(ctx context.Context, epoch uint64) (common.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreviousHeaderHashAt", ctx, epoch)
	ret0, _ := ret[0].(common.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPreviousHeaderHashAt indicates an expected call of GetPreviousHeaderHashAt.
func (mr *MockethClientMockRecorder) GetPreviousHeaderHashAt(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreviousHeaderHashAt", reflect.TypeOf((*MockethClient)(nil).GetPreviousHeaderHashAt), ctx, epoch)
}

// GetRequiredKeyTag mocks base method.
func (m *MockethClient) GetRequiredKeyTag(ctx context.Context, timestamp uint64) (entity.KeyTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequiredKeyTag", ctx, timestamp)
	ret0, _ := ret[0].(entity.KeyTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRequiredKeyTag indicates an expected call of GetRequiredKeyTag.
func (mr *MockethClientMockRecorder) GetRequiredKeyTag(ctx, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequiredKeyTag", reflect.TypeOf((*MockethClient)(nil).GetRequiredKeyTag), ctx, timestamp)
}

// GetSubnetwork mocks base method.
func (m *MockethClient) GetSubnetwork(ctx context.Context) (common.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubnetwork", ctx)
	ret0, _ := ret[0].(common.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubnetwork indicates an expected call of GetSubnetwork.
func (mr *MockethClientMockRecorder) GetSubnetwork(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubnetwork", reflect.TypeOf((*MockethClient)(nil).GetSubnetwork), ctx)
}

// GetVotingPowers mocks base method.
func (m *MockethClient) GetVotingPowers(ctx context.Context, address entity.CrossChainAddress, timestamp uint64) ([]entity.OperatorVotingPower, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVotingPowers", ctx, address, timestamp)
	ret0, _ := ret[0].([]entity.OperatorVotingPower)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVotingPowers indicates an expected call of GetVotingPowers.
func (mr *MockethClientMockRecorder) GetVotingPowers(ctx, address, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVotingPowers", reflect.TypeOf((*MockethClient)(nil).GetVotingPowers), ctx, address, timestamp)
}

// IsValsetHeaderCommittedAt mocks base method.
func (m *MockethClient) IsValsetHeaderCommittedAt(ctx context.Context, epoch uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValsetHeaderCommittedAt", ctx, epoch)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsValsetHeaderCommittedAt indicates an expected call of IsValsetHeaderCommittedAt.
func (mr *MockethClientMockRecorder) IsValsetHeaderCommittedAt(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValsetHeaderCommittedAt", reflect.TypeOf((*MockethClient)(nil).IsValsetHeaderCommittedAt), ctx, epoch)
}
