// Code generated by MockGen. DO NOT EDIT.
// Source: generator.go
//
// Generated by this command:
//
//	mockgen -source=generator.go -destination=mocks/generator.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	big "math/big"
	entity "middleware-offchain/core/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockderiver is a mock of deriver interface.
type Mockderiver struct {
	ctrl     *gomock.Controller
	recorder *MockderiverMockRecorder
	isgomock struct{}
}

// MockderiverMockRecorder is the mock recorder for Mockderiver.
type MockderiverMockRecorder struct {
	mock *Mockderiver
}

// NewMockderiver creates a new mock instance.
func NewMockderiver(ctrl *gomock.Controller) *Mockderiver {
	mock := &Mockderiver{ctrl: ctrl}
	mock.recorder = &MockderiverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockderiver) EXPECT() *MockderiverMockRecorder {
	return m.recorder
}

// GetValidatorSet mocks base method.
func (m *Mockderiver) GetValidatorSet(ctx context.Context, timestamp *big.Int) (entity.ValidatorSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidatorSet", ctx, timestamp)
	ret0, _ := ret[0].(entity.ValidatorSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidatorSet indicates an expected call of GetValidatorSet.
func (mr *MockderiverMockRecorder) GetValidatorSet(ctx, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidatorSet", reflect.TypeOf((*Mockderiver)(nil).GetValidatorSet), ctx, timestamp)
}
