// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/message.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SignaturesAggregated represents the aggregated signatures message
type AggregationProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyTag        uint32                 `protobuf:"varint,2,opt,name=key_tag,json=keyTag,proto3" json:"key_tag,omitempty"`
	Epoch         uint64                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	MessageHash   []byte                 `protobuf:"bytes,4,opt,name=message_hash,json=messageHash,proto3" json:"message_hash,omitempty"`
	Proof         []byte                 `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregationProof) Reset() {
	*x = AggregationProof{}
	mi := &file_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregationProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregationProof) ProtoMessage() {}

func (x *AggregationProof) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregationProof.ProtoReflect.Descriptor instead.
func (*AggregationProof) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *AggregationProof) GetKeyTag() uint32 {
	if x != nil {
		return x.KeyTag
	}
	return 0
}

func (x *AggregationProof) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *AggregationProof) GetMessageHash() []byte {
	if x != nil {
		return x.MessageHash
	}
	return nil
}

func (x *AggregationProof) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

// P2PMessage represents a peer-to-peer message wrapper
type P2PMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P2PMessage) Reset() {
	*x = P2PMessage{}
	mi := &file_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PMessage) ProtoMessage() {}

func (x *P2PMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PMessage.ProtoReflect.Descriptor instead.
func (*P2PMessage) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *P2PMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *P2PMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *P2PMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WantSignaturesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of request id to bitmap of wanted validator indices
	WantSignatures map[string][]byte `protobuf:"bytes,1,rep,name=want_signatures,json=wantSignatures,proto3" json:"want_signatures,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key: hex string of common.Hash, value: roaring bitmap bytes
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WantSignaturesRequest) Reset() {
	*x = WantSignaturesRequest{}
	mi := &file_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WantSignaturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WantSignaturesRequest) ProtoMessage() {}

func (x *WantSignaturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WantSignaturesRequest.ProtoReflect.Descriptor instead.
func (*WantSignaturesRequest) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *WantSignaturesRequest) GetWantSignatures() map[string][]byte {
	if x != nil {
		return x.WantSignatures
	}
	return nil
}

type WantSignaturesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of request id to list of validator signatures
	Signatures    map[string]*ValidatorSignatureList `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key: hex string of common.Hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WantSignaturesResponse) Reset() {
	*x = WantSignaturesResponse{}
	mi := &file_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WantSignaturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WantSignaturesResponse) ProtoMessage() {}

func (x *WantSignaturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WantSignaturesResponse.ProtoReflect.Descriptor instead.
func (*WantSignaturesResponse) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *WantSignaturesResponse) GetSignatures() map[string]*ValidatorSignatureList {
	if x != nil {
		return x.Signatures
	}
	return nil
}

// ValidatorSignatureList contains a list of validator signatures for a specific request
type ValidatorSignatureList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signatures    []*ValidatorSignature  `protobuf:"bytes,1,rep,name=signatures,proto3" json:"signatures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatorSignatureList) Reset() {
	*x = ValidatorSignatureList{}
	mi := &file_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorSignatureList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorSignatureList) ProtoMessage() {}

func (x *ValidatorSignatureList) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorSignatureList.ProtoReflect.Descriptor instead.
func (*ValidatorSignatureList) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *ValidatorSignatureList) GetSignatures() []*ValidatorSignature {
	if x != nil {
		return x.Signatures
	}
	return nil
}

// ValidatorSignature pairs a signature with its validator index
type ValidatorSignature struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ValidatorIndex uint32                 `protobuf:"varint,1,opt,name=validator_index,json=validatorIndex,proto3" json:"validator_index,omitempty"`
	Signature      *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidatorSignature) Reset() {
	*x = ValidatorSignature{}
	mi := &file_v1_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorSignature) ProtoMessage() {}

func (x *ValidatorSignature) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorSignature.ProtoReflect.Descriptor instead.
func (*ValidatorSignature) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{5}
}

func (x *ValidatorSignature) GetValidatorIndex() uint32 {
	if x != nil {
		return x.ValidatorIndex
	}
	return 0
}

func (x *ValidatorSignature) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Signature represents extended signature data
type Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageHash   []byte                 `protobuf:"bytes,1,opt,name=message_hash,json=messageHash,proto3" json:"message_hash,omitempty"`
	KeyTag        uint32                 `protobuf:"varint,2,opt,name=key_tag,json=keyTag,proto3" json:"key_tag,omitempty"`
	Epoch         uint64                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_v1_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{6}
}

func (x *Signature) GetMessageHash() []byte {
	if x != nil {
		return x.MessageHash
	}
	return nil
}

func (x *Signature) GetKeyTag() uint32 {
	if x != nil {
		return x.KeyTag
	}
	return 0
}

func (x *Signature) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Signature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Signature) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type WantAggregationProofsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of request ids for which aggregation proofs are needed
	RequestIds    []string `protobuf:"bytes,1,rep,name=request_ids,json=requestIds,proto3" json:"request_ids,omitempty"` // hex strings of common.Hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WantAggregationProofsRequest) Reset() {
	*x = WantAggregationProofsRequest{}
	mi := &file_v1_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WantAggregationProofsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WantAggregationProofsRequest) ProtoMessage() {}

func (x *WantAggregationProofsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WantAggregationProofsRequest.ProtoReflect.Descriptor instead.
func (*WantAggregationProofsRequest) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{7}
}

func (x *WantAggregationProofsRequest) GetRequestIds() []string {
	if x != nil {
		return x.RequestIds
	}
	return nil
}

type WantAggregationProofsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of request ids to aggregation proof
	Proofs        map[string]*AggregationProof `protobuf:"bytes,1,rep,name=proofs,proto3" json:"proofs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key: hex string of common.Hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WantAggregationProofsResponse) Reset() {
	*x = WantAggregationProofsResponse{}
	mi := &file_v1_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WantAggregationProofsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WantAggregationProofsResponse) ProtoMessage() {}

func (x *WantAggregationProofsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WantAggregationProofsResponse.ProtoReflect.Descriptor instead.
func (*WantAggregationProofsResponse) Descriptor() ([]byte, []int) {
	return file_v1_message_proto_rawDescGZIP(), []int{8}
}

func (x *WantAggregationProofsResponse) GetProofs() map[string]*AggregationProof {
	if x != nil {
		return x.Proofs
	}
	return nil
}

var File_v1_message_proto protoreflect.FileDescriptor

const file_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x10v1/message.proto\x12\x1cinternal.client.p2p.proto.v1\"z\n" +
	"\x10AggregationProof\x12\x17\n" +
	"\akey_tag\x18\x02 \x01(\rR\x06keyTag\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x04R\x05epoch\x12!\n" +
	"\fmessage_hash\x18\x04 \x01(\fR\vmessageHash\x12\x14\n" +
	"\x05proof\x18\x05 \x01(\fR\x05proof\"V\n" +
	"\n" +
	"P2PMessage\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\xcc\x01\n" +
	"\x15WantSignaturesRequest\x12p\n" +
	"\x0fwant_signatures\x18\x01 \x03(\v2G.internal.client.p2p.proto.v1.WantSignaturesRequest.WantSignaturesEntryR\x0ewantSignatures\x1aA\n" +
	"\x13WantSignaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xf3\x01\n" +
	"\x16WantSignaturesResponse\x12d\n" +
	"\n" +
	"signatures\x18\x02 \x03(\v2D.internal.client.p2p.proto.v1.WantSignaturesResponse.SignaturesEntryR\n" +
	"signatures\x1as\n" +
	"\x0fSignaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12J\n" +
	"\x05value\x18\x02 \x01(\v24.internal.client.p2p.proto.v1.ValidatorSignatureListR\x05value:\x028\x01\"j\n" +
	"\x16ValidatorSignatureList\x12P\n" +
	"\n" +
	"signatures\x18\x01 \x03(\v20.internal.client.p2p.proto.v1.ValidatorSignatureR\n" +
	"signatures\"\x84\x01\n" +
	"\x12ValidatorSignature\x12'\n" +
	"\x0fvalidator_index\x18\x01 \x01(\rR\x0evalidatorIndex\x12E\n" +
	"\tsignature\x18\x02 \x01(\v2'.internal.client.p2p.proto.v1.SignatureR\tsignature\"\x9a\x01\n" +
	"\tSignature\x12!\n" +
	"\fmessage_hash\x18\x01 \x01(\fR\vmessageHash\x12\x17\n" +
	"\akey_tag\x18\x02 \x01(\rR\x06keyTag\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x04R\x05epoch\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x05 \x01(\fR\tpublicKey\"?\n" +
	"\x1cWantAggregationProofsRequest\x12\x1f\n" +
	"\vrequest_ids\x18\x01 \x03(\tR\n" +
	"requestIds\"\xeb\x01\n" +
	"\x1dWantAggregationProofsResponse\x12_\n" +
	"\x06proofs\x18\x01 \x03(\v2G.internal.client.p2p.proto.v1.WantAggregationProofsResponse.ProofsEntryR\x06proofs\x1ai\n" +
	"\vProofsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12D\n" +
	"\x05value\x18\x02 \x01(\v2..internal.client.p2p.proto.v1.AggregationProofR\x05value:\x028\x012\xa5\x02\n" +
	"\x13SymbioticP2PService\x12{\n" +
	"\x0eWantSignatures\x123.internal.client.p2p.proto.v1.WantSignaturesRequest\x1a4.internal.client.p2p.proto.v1.WantSignaturesResponse\x12\x90\x01\n" +
	"\x15WantAggregationProofs\x12:.internal.client.p2p.proto.v1.WantAggregationProofsRequest\x1a;.internal.client.p2p.proto.v1.WantAggregationProofsResponseB\x80\x02\n" +
	" com.internal.client.p2p.proto.v1B\fMessageProtoP\x01Z9github.com/symbioticfi/relay/internal/client/p2p/proto/v1\xa2\x02\x04ICPP\xaa\x02\x1cInternal.Client.P2p.Proto.V1\xca\x02\x1cInternal\\Client\\P2p\\Proto\\V1\xe2\x02(Internal\\Client\\P2p\\Proto\\V1\\GPBMetadata\xea\x02 Internal::Client::P2p::Proto::V1b\x06proto3"

var (
	file_v1_message_proto_rawDescOnce sync.Once
	file_v1_message_proto_rawDescData []byte
)

func file_v1_message_proto_rawDescGZIP() []byte {
	file_v1_message_proto_rawDescOnce.Do(func() {
		file_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_message_proto_rawDesc), len(file_v1_message_proto_rawDesc)))
	})
	return file_v1_message_proto_rawDescData
}

var file_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_v1_message_proto_goTypes = []any{
	(*AggregationProof)(nil),              // 0: internal.client.p2p.proto.v1.AggregationProof
	(*P2PMessage)(nil),                    // 1: internal.client.p2p.proto.v1.P2PMessage
	(*WantSignaturesRequest)(nil),         // 2: internal.client.p2p.proto.v1.WantSignaturesRequest
	(*WantSignaturesResponse)(nil),        // 3: internal.client.p2p.proto.v1.WantSignaturesResponse
	(*ValidatorSignatureList)(nil),        // 4: internal.client.p2p.proto.v1.ValidatorSignatureList
	(*ValidatorSignature)(nil),            // 5: internal.client.p2p.proto.v1.ValidatorSignature
	(*Signature)(nil),                     // 6: internal.client.p2p.proto.v1.Signature
	(*WantAggregationProofsRequest)(nil),  // 7: internal.client.p2p.proto.v1.WantAggregationProofsRequest
	(*WantAggregationProofsResponse)(nil), // 8: internal.client.p2p.proto.v1.WantAggregationProofsResponse
	nil,                                   // 9: internal.client.p2p.proto.v1.WantSignaturesRequest.WantSignaturesEntry
	nil,                                   // 10: internal.client.p2p.proto.v1.WantSignaturesResponse.SignaturesEntry
	nil,                                   // 11: internal.client.p2p.proto.v1.WantAggregationProofsResponse.ProofsEntry
}
var file_v1_message_proto_depIdxs = []int32{
	9,  // 0: internal.client.p2p.proto.v1.WantSignaturesRequest.want_signatures:type_name -> internal.client.p2p.proto.v1.WantSignaturesRequest.WantSignaturesEntry
	10, // 1: internal.client.p2p.proto.v1.WantSignaturesResponse.signatures:type_name -> internal.client.p2p.proto.v1.WantSignaturesResponse.SignaturesEntry
	5,  // 2: internal.client.p2p.proto.v1.ValidatorSignatureList.signatures:type_name -> internal.client.p2p.proto.v1.ValidatorSignature
	6,  // 3: internal.client.p2p.proto.v1.ValidatorSignature.signature:type_name -> internal.client.p2p.proto.v1.Signature
	11, // 4: internal.client.p2p.proto.v1.WantAggregationProofsResponse.proofs:type_name -> internal.client.p2p.proto.v1.WantAggregationProofsResponse.ProofsEntry
	4,  // 5: internal.client.p2p.proto.v1.WantSignaturesResponse.SignaturesEntry.value:type_name -> internal.client.p2p.proto.v1.ValidatorSignatureList
	0,  // 6: internal.client.p2p.proto.v1.WantAggregationProofsResponse.ProofsEntry.value:type_name -> internal.client.p2p.proto.v1.AggregationProof
	2,  // 7: internal.client.p2p.proto.v1.SymbioticP2PService.WantSignatures:input_type -> internal.client.p2p.proto.v1.WantSignaturesRequest
	7,  // 8: internal.client.p2p.proto.v1.SymbioticP2PService.WantAggregationProofs:input_type -> internal.client.p2p.proto.v1.WantAggregationProofsRequest
	3,  // 9: internal.client.p2p.proto.v1.SymbioticP2PService.WantSignatures:output_type -> internal.client.p2p.proto.v1.WantSignaturesResponse
	8,  // 10: internal.client.p2p.proto.v1.SymbioticP2PService.WantAggregationProofs:output_type -> internal.client.p2p.proto.v1.WantAggregationProofsResponse
	9,  // [9:11] is the sub-list for method output_type
	7,  // [7:9] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_v1_message_proto_init() }
func file_v1_message_proto_init() {
	if File_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_message_proto_rawDesc), len(file_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_message_proto_goTypes,
		DependencyIndexes: file_v1_message_proto_depIdxs,
		MessageInfos:      file_v1_message_proto_msgTypes,
	}.Build()
	File_v1_message_proto = out.File
	file_v1_message_proto_goTypes = nil
	file_v1_message_proto_depIdxs = nil
}
