// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/sync.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WantSignaturesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of request hash to bitmap of wanted validator indices
	WantSignatures map[string][]byte `protobuf:"bytes,1,rep,name=want_signatures,json=wantSignatures,proto3" json:"want_signatures,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key: hex string of common.Hash, value: roaring bitmap bytes
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WantSignaturesRequest) Reset() {
	*x = WantSignaturesRequest{}
	mi := &file_v1_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WantSignaturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WantSignaturesRequest) ProtoMessage() {}

func (x *WantSignaturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WantSignaturesRequest.ProtoReflect.Descriptor instead.
func (*WantSignaturesRequest) Descriptor() ([]byte, []int) {
	return file_v1_sync_proto_rawDescGZIP(), []int{0}
}

func (x *WantSignaturesRequest) GetWantSignatures() map[string][]byte {
	if x != nil {
		return x.WantSignatures
	}
	return nil
}

type WantSignaturesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of request hash to list of validator signatures
	Signatures    map[string]*ValidatorSignatureList `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key: hex string of common.Hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WantSignaturesResponse) Reset() {
	*x = WantSignaturesResponse{}
	mi := &file_v1_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WantSignaturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WantSignaturesResponse) ProtoMessage() {}

func (x *WantSignaturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WantSignaturesResponse.ProtoReflect.Descriptor instead.
func (*WantSignaturesResponse) Descriptor() ([]byte, []int) {
	return file_v1_sync_proto_rawDescGZIP(), []int{1}
}

func (x *WantSignaturesResponse) GetSignatures() map[string]*ValidatorSignatureList {
	if x != nil {
		return x.Signatures
	}
	return nil
}

// ValidatorSignatureList contains a list of validator signatures for a specific request
type ValidatorSignatureList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signatures    []*ValidatorSignature  `protobuf:"bytes,1,rep,name=signatures,proto3" json:"signatures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatorSignatureList) Reset() {
	*x = ValidatorSignatureList{}
	mi := &file_v1_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorSignatureList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorSignatureList) ProtoMessage() {}

func (x *ValidatorSignatureList) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorSignatureList.ProtoReflect.Descriptor instead.
func (*ValidatorSignatureList) Descriptor() ([]byte, []int) {
	return file_v1_sync_proto_rawDescGZIP(), []int{2}
}

func (x *ValidatorSignatureList) GetSignatures() []*ValidatorSignature {
	if x != nil {
		return x.Signatures
	}
	return nil
}

// ValidatorSignature pairs a signature with its validator index
type ValidatorSignature struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ValidatorIndex uint32                 `protobuf:"varint,1,opt,name=validator_index,json=validatorIndex,proto3" json:"validator_index,omitempty"`
	Signature      *SignatureExtended     `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidatorSignature) Reset() {
	*x = ValidatorSignature{}
	mi := &file_v1_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorSignature) ProtoMessage() {}

func (x *ValidatorSignature) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorSignature.ProtoReflect.Descriptor instead.
func (*ValidatorSignature) Descriptor() ([]byte, []int) {
	return file_v1_sync_proto_rawDescGZIP(), []int{3}
}

func (x *ValidatorSignature) GetValidatorIndex() uint32 {
	if x != nil {
		return x.ValidatorIndex
	}
	return 0
}

func (x *ValidatorSignature) GetSignature() *SignatureExtended {
	if x != nil {
		return x.Signature
	}
	return nil
}

// SignatureExtended represents extended signature data
type SignatureExtended struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageHash   []byte                 `protobuf:"bytes,1,opt,name=message_hash,json=messageHash,proto3" json:"message_hash,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignatureExtended) Reset() {
	*x = SignatureExtended{}
	mi := &file_v1_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureExtended) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureExtended) ProtoMessage() {}

func (x *SignatureExtended) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureExtended.ProtoReflect.Descriptor instead.
func (*SignatureExtended) Descriptor() ([]byte, []int) {
	return file_v1_sync_proto_rawDescGZIP(), []int{4}
}

func (x *SignatureExtended) GetMessageHash() []byte {
	if x != nil {
		return x.MessageHash
	}
	return nil
}

func (x *SignatureExtended) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignatureExtended) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

var File_v1_sync_proto protoreflect.FileDescriptor

const file_v1_sync_proto_rawDesc = "" +
	"\n" +
	"\rv1/sync.proto\x12\x1cinternal.client.p2p.proto.v1\"\xcc\x01\n" +
	"\x15WantSignaturesRequest\x12p\n" +
	"\x0fwant_signatures\x18\x01 \x03(\v2G.internal.client.p2p.proto.v1.WantSignaturesRequest.WantSignaturesEntryR\x0ewantSignatures\x1aA\n" +
	"\x13WantSignaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xf3\x01\n" +
	"\x16WantSignaturesResponse\x12d\n" +
	"\n" +
	"signatures\x18\x02 \x03(\v2D.internal.client.p2p.proto.v1.WantSignaturesResponse.SignaturesEntryR\n" +
	"signatures\x1as\n" +
	"\x0fSignaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12J\n" +
	"\x05value\x18\x02 \x01(\v24.internal.client.p2p.proto.v1.ValidatorSignatureListR\x05value:\x028\x01\"j\n" +
	"\x16ValidatorSignatureList\x12P\n" +
	"\n" +
	"signatures\x18\x01 \x03(\v20.internal.client.p2p.proto.v1.ValidatorSignatureR\n" +
	"signatures\"\x8c\x01\n" +
	"\x12ValidatorSignature\x12'\n" +
	"\x0fvalidator_index\x18\x01 \x01(\rR\x0evalidatorIndex\x12M\n" +
	"\tsignature\x18\x02 \x01(\v2/.internal.client.p2p.proto.v1.SignatureExtendedR\tsignature\"s\n" +
	"\x11SignatureExtended\x12!\n" +
	"\fmessage_hash\x18\x01 \x01(\fR\vmessageHash\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey2\x92\x01\n" +
	"\x13SymbioticP2PService\x12{\n" +
	"\x0eWantSignatures\x123.internal.client.p2p.proto.v1.WantSignaturesRequest\x1a4.internal.client.p2p.proto.v1.WantSignaturesResponseB\xfd\x01\n" +
	" com.internal.client.p2p.proto.v1B\tSyncProtoP\x01Z9github.com/symbioticfi/relay/internal/client/p2p/proto/v1\xa2\x02\x04ICPP\xaa\x02\x1cInternal.Client.P2p.Proto.V1\xca\x02\x1cInternal\\Client\\P2p\\Proto\\V1\xe2\x02(Internal\\Client\\P2p\\Proto\\V1\\GPBMetadata\xea\x02 Internal::Client::P2p::Proto::V1b\x06proto3"

var (
	file_v1_sync_proto_rawDescOnce sync.Once
	file_v1_sync_proto_rawDescData []byte
)

func file_v1_sync_proto_rawDescGZIP() []byte {
	file_v1_sync_proto_rawDescOnce.Do(func() {
		file_v1_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_sync_proto_rawDesc), len(file_v1_sync_proto_rawDesc)))
	})
	return file_v1_sync_proto_rawDescData
}

var file_v1_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_v1_sync_proto_goTypes = []any{
	(*WantSignaturesRequest)(nil),  // 0: internal.client.p2p.proto.v1.WantSignaturesRequest
	(*WantSignaturesResponse)(nil), // 1: internal.client.p2p.proto.v1.WantSignaturesResponse
	(*ValidatorSignatureList)(nil), // 2: internal.client.p2p.proto.v1.ValidatorSignatureList
	(*ValidatorSignature)(nil),     // 3: internal.client.p2p.proto.v1.ValidatorSignature
	(*SignatureExtended)(nil),      // 4: internal.client.p2p.proto.v1.SignatureExtended
	nil,                            // 5: internal.client.p2p.proto.v1.WantSignaturesRequest.WantSignaturesEntry
	nil,                            // 6: internal.client.p2p.proto.v1.WantSignaturesResponse.SignaturesEntry
}
var file_v1_sync_proto_depIdxs = []int32{
	5, // 0: internal.client.p2p.proto.v1.WantSignaturesRequest.want_signatures:type_name -> internal.client.p2p.proto.v1.WantSignaturesRequest.WantSignaturesEntry
	6, // 1: internal.client.p2p.proto.v1.WantSignaturesResponse.signatures:type_name -> internal.client.p2p.proto.v1.WantSignaturesResponse.SignaturesEntry
	3, // 2: internal.client.p2p.proto.v1.ValidatorSignatureList.signatures:type_name -> internal.client.p2p.proto.v1.ValidatorSignature
	4, // 3: internal.client.p2p.proto.v1.ValidatorSignature.signature:type_name -> internal.client.p2p.proto.v1.SignatureExtended
	2, // 4: internal.client.p2p.proto.v1.WantSignaturesResponse.SignaturesEntry.value:type_name -> internal.client.p2p.proto.v1.ValidatorSignatureList
	0, // 5: internal.client.p2p.proto.v1.SymbioticP2PService.WantSignatures:input_type -> internal.client.p2p.proto.v1.WantSignaturesRequest
	1, // 6: internal.client.p2p.proto.v1.SymbioticP2PService.WantSignatures:output_type -> internal.client.p2p.proto.v1.WantSignaturesResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_v1_sync_proto_init() }
func file_v1_sync_proto_init() {
	if File_v1_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_sync_proto_rawDesc), len(file_v1_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_sync_proto_goTypes,
		DependencyIndexes: file_v1_sync_proto_depIdxs,
		MessageInfos:      file_v1_sync_proto_msgTypes,
	}.Build()
	File_v1_sync_proto = out.File
	file_v1_sync_proto_goTypes = nil
	file_v1_sync_proto_depIdxs = nil
}
