// Code generated by MockGen. DO NOT EDIT.
// Source: pruner_uc.go
//
// Generated by this command:
//
//	mockgen -source=pruner_uc.go -destination=mocks/pruner_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/symbioticfi/relay/symbiotic/entity"
	gomock "go.uber.org/mock/gomock"
)

// Mockmetrics is a mock of metrics interface.
type Mockmetrics struct {
	ctrl     *gomock.Controller
	recorder *MockmetricsMockRecorder
	isgomock struct{}
}

// MockmetricsMockRecorder is the mock recorder for Mockmetrics.
type MockmetricsMockRecorder struct {
	mock *Mockmetrics
}

// NewMockmetrics creates a new mock instance.
func NewMockmetrics(ctrl *gomock.Controller) *Mockmetrics {
	mock := &Mockmetrics{ctrl: ctrl}
	mock.recorder = &MockmetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockmetrics) EXPECT() *MockmetricsMockRecorder {
	return m.recorder
}

// IncPrunedEpochsCount mocks base method.
func (m *Mockmetrics) IncPrunedEpochsCount(entityType string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncPrunedEpochsCount", entityType)
}

// IncPrunedEpochsCount indicates an expected call of IncPrunedEpochsCount.
func (mr *MockmetricsMockRecorder) IncPrunedEpochsCount(entityType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncPrunedEpochsCount", reflect.TypeOf((*Mockmetrics)(nil).IncPrunedEpochsCount), entityType)
}

// Mockrepo is a mock of repo interface.
type Mockrepo struct {
	ctrl     *gomock.Controller
	recorder *MockrepoMockRecorder
	isgomock struct{}
}

// MockrepoMockRecorder is the mock recorder for Mockrepo.
type MockrepoMockRecorder struct {
	mock *Mockrepo
}

// NewMockrepo creates a new mock instance.
func NewMockrepo(ctrl *gomock.Controller) *Mockrepo {
	mock := &Mockrepo{ctrl: ctrl}
	mock.recorder = &MockrepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepo) EXPECT() *MockrepoMockRecorder {
	return m.recorder
}

// GetLatestValidatorSetEpoch mocks base method.
func (m *Mockrepo) GetLatestValidatorSetEpoch(ctx context.Context) (entity.Epoch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestValidatorSetEpoch", ctx)
	ret0, _ := ret[0].(entity.Epoch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestValidatorSetEpoch indicates an expected call of GetLatestValidatorSetEpoch.
func (mr *MockrepoMockRecorder) GetLatestValidatorSetEpoch(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestValidatorSetEpoch", reflect.TypeOf((*Mockrepo)(nil).GetLatestValidatorSetEpoch), ctx)
}

// GetOldestValidatorSetEpoch mocks base method.
func (m *Mockrepo) GetOldestValidatorSetEpoch(ctx context.Context) (entity.Epoch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOldestValidatorSetEpoch", ctx)
	ret0, _ := ret[0].(entity.Epoch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOldestValidatorSetEpoch indicates an expected call of GetOldestValidatorSetEpoch.
func (mr *MockrepoMockRecorder) GetOldestValidatorSetEpoch(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOldestValidatorSetEpoch", reflect.TypeOf((*Mockrepo)(nil).GetOldestValidatorSetEpoch), ctx)
}

// PruneProofEntities mocks base method.
func (m *Mockrepo) PruneProofEntities(ctx context.Context, epoch entity.Epoch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PruneProofEntities", ctx, epoch)
	ret0, _ := ret[0].(error)
	return ret0
}

// PruneProofEntities indicates an expected call of PruneProofEntities.
func (mr *MockrepoMockRecorder) PruneProofEntities(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PruneProofEntities", reflect.TypeOf((*Mockrepo)(nil).PruneProofEntities), ctx, epoch)
}

// PruneSignatureEntitiesForEpoch mocks base method.
func (m *Mockrepo) PruneSignatureEntitiesForEpoch(ctx context.Context, epoch entity.Epoch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PruneSignatureEntitiesForEpoch", ctx, epoch)
	ret0, _ := ret[0].(error)
	return ret0
}

// PruneSignatureEntitiesForEpoch indicates an expected call of PruneSignatureEntitiesForEpoch.
func (mr *MockrepoMockRecorder) PruneSignatureEntitiesForEpoch(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PruneSignatureEntitiesForEpoch", reflect.TypeOf((*Mockrepo)(nil).PruneSignatureEntitiesForEpoch), ctx, epoch)
}

// PruneValsetEntities mocks base method.
func (m *Mockrepo) PruneValsetEntities(ctx context.Context, epoch entity.Epoch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PruneValsetEntities", ctx, epoch)
	ret0, _ := ret[0].(error)
	return ret0
}

// PruneValsetEntities indicates an expected call of PruneValsetEntities.
func (mr *MockrepoMockRecorder) PruneValsetEntities(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PruneValsetEntities", reflect.TypeOf((*Mockrepo)(nil).PruneValsetEntities), ctx, epoch)
}
