// Code generated by MockGen. DO NOT EDIT.
// Source: signature_listener_uc.go
//
// Generated by this command:
//
//	mockgen -source=signature_listener_uc.go -destination=mocks/signature_listener_uc.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	entity "github.com/symbioticfi/relay/core/entity"
	gomock "go.uber.org/mock/gomock"
)

// Mockrepo is a mock of repo interface.
type Mockrepo struct {
	ctrl     *gomock.Controller
	recorder *MockrepoMockRecorder
	isgomock struct{}
}

// MockrepoMockRecorder is the mock recorder for Mockrepo.
type MockrepoMockRecorder struct {
	mock *Mockrepo
}

// NewMockrepo creates a new mock instance.
func NewMockrepo(ctrl *gomock.Controller) *Mockrepo {
	mock := &Mockrepo{ctrl: ctrl}
	mock.recorder = &MockrepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepo) EXPECT() *MockrepoMockRecorder {
	return m.recorder
}

// DoUpdateInTx mocks base method.
func (m *Mockrepo) DoUpdateInTx(ctx context.Context, f func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoUpdateInTx", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// DoUpdateInTx indicates an expected call of DoUpdateInTx.
func (mr *MockrepoMockRecorder) DoUpdateInTx(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoUpdateInTx", reflect.TypeOf((*Mockrepo)(nil).DoUpdateInTx), ctx, f)
}

// GetValidatorByKey mocks base method.
func (m *Mockrepo) GetValidatorByKey(ctx context.Context, epoch uint64, keyTag entity.KeyTag, publicKey []byte) (entity.Validator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidatorByKey", ctx, epoch, keyTag, publicKey)
	ret0, _ := ret[0].(entity.Validator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidatorByKey indicates an expected call of GetValidatorByKey.
func (mr *MockrepoMockRecorder) GetValidatorByKey(ctx, epoch, keyTag, publicKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidatorByKey", reflect.TypeOf((*Mockrepo)(nil).GetValidatorByKey), ctx, epoch, keyTag, publicKey)
}

// GetValidatorMap mocks base method.
func (m *Mockrepo) GetValidatorMap(arg0 context.Context, reqHash common.Hash) (entity.ValidatorMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidatorMap", arg0, reqHash)
	ret0, _ := ret[0].(entity.ValidatorMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidatorMap indicates an expected call of GetValidatorMap.
func (mr *MockrepoMockRecorder) GetValidatorMap(arg0, reqHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidatorMap", reflect.TypeOf((*Mockrepo)(nil).GetValidatorMap), arg0, reqHash)
}

// GetValidatorSetByEpoch mocks base method.
func (m *Mockrepo) GetValidatorSetByEpoch(ctx context.Context, epoch uint64) (entity.ValidatorSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidatorSetByEpoch", ctx, epoch)
	ret0, _ := ret[0].(entity.ValidatorSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidatorSetByEpoch indicates an expected call of GetValidatorSetByEpoch.
func (mr *MockrepoMockRecorder) GetValidatorSetByEpoch(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidatorSetByEpoch", reflect.TypeOf((*Mockrepo)(nil).GetValidatorSetByEpoch), ctx, epoch)
}

// SaveSignature mocks base method.
func (m *Mockrepo) SaveSignature(ctx context.Context, reqHash common.Hash, key entity.RawPublicKey, sig entity.SignatureExtended) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSignature", ctx, reqHash, key, sig)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSignature indicates an expected call of SaveSignature.
func (mr *MockrepoMockRecorder) SaveSignature(ctx, reqHash, key, sig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSignature", reflect.TypeOf((*Mockrepo)(nil).SaveSignature), ctx, reqHash, key, sig)
}

// UpdateValidatorMap mocks base method.
func (m *Mockrepo) UpdateValidatorMap(arg0 context.Context, vm entity.ValidatorMap) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateValidatorMap", arg0, vm)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateValidatorMap indicates an expected call of UpdateValidatorMap.
func (mr *MockrepoMockRecorder) UpdateValidatorMap(arg0, vm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateValidatorMap", reflect.TypeOf((*Mockrepo)(nil).UpdateValidatorMap), arg0, vm)
}
