// Code generated by MockGen. DO NOT EDIT.
// Source: signature_listener_uc.go
//
// Generated by this command:
//
//	mockgen -source=signature_listener_uc.go -destination=mocks/signature_listener_uc.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/symbioticfi/relay/core/entity"
	gomock "go.uber.org/mock/gomock"
)

// Mockrepo is a mock of repo interface.
type Mockrepo struct {
	ctrl     *gomock.Controller
	recorder *MockrepoMockRecorder
	isgomock struct{}
}

// MockrepoMockRecorder is the mock recorder for Mockrepo.
type MockrepoMockRecorder struct {
	mock *Mockrepo
}

// NewMockrepo creates a new mock instance.
func NewMockrepo(ctrl *gomock.Controller) *Mockrepo {
	mock := &Mockrepo{ctrl: ctrl}
	mock.recorder = &MockrepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepo) EXPECT() *MockrepoMockRecorder {
	return m.recorder
}

// GetValidatorByKey mocks base method.
func (m *Mockrepo) GetValidatorByKey(ctx context.Context, epoch uint64, keyTag entity.KeyTag, publicKey []byte) (entity.Validator, uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidatorByKey", ctx, epoch, keyTag, publicKey)
	ret0, _ := ret[0].(entity.Validator)
	ret1, _ := ret[1].(uint32)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetValidatorByKey indicates an expected call of GetValidatorByKey.
func (mr *MockrepoMockRecorder) GetValidatorByKey(ctx, epoch, keyTag, publicKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidatorByKey", reflect.TypeOf((*Mockrepo)(nil).GetValidatorByKey), ctx, epoch, keyTag, publicKey)
}

// GetValidatorSetByEpoch mocks base method.
func (m *Mockrepo) GetValidatorSetByEpoch(ctx context.Context, epoch uint64) (entity.ValidatorSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidatorSetByEpoch", ctx, epoch)
	ret0, _ := ret[0].(entity.ValidatorSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidatorSetByEpoch indicates an expected call of GetValidatorSetByEpoch.
func (mr *MockrepoMockRecorder) GetValidatorSetByEpoch(ctx, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidatorSetByEpoch", reflect.TypeOf((*Mockrepo)(nil).GetValidatorSetByEpoch), ctx, epoch)
}

// MocksignatureProcessor is a mock of signatureProcessor interface.
type MocksignatureProcessor struct {
	ctrl     *gomock.Controller
	recorder *MocksignatureProcessorMockRecorder
	isgomock struct{}
}

// MocksignatureProcessorMockRecorder is the mock recorder for MocksignatureProcessor.
type MocksignatureProcessorMockRecorder struct {
	mock *MocksignatureProcessor
}

// NewMocksignatureProcessor creates a new mock instance.
func NewMocksignatureProcessor(ctrl *gomock.Controller) *MocksignatureProcessor {
	mock := &MocksignatureProcessor{ctrl: ctrl}
	mock.recorder = &MocksignatureProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksignatureProcessor) EXPECT() *MocksignatureProcessorMockRecorder {
	return m.recorder
}

// ProcessSignature mocks base method.
func (m *MocksignatureProcessor) ProcessSignature(ctx context.Context, param entity.SaveSignatureParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessSignature", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessSignature indicates an expected call of ProcessSignature.
func (mr *MocksignatureProcessorMockRecorder) ProcessSignature(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessSignature", reflect.TypeOf((*MocksignatureProcessor)(nil).ProcessSignature), ctx, param)
}
