// Code generated by generate-client-types. DO NOT EDIT.
package v1

import (
	apiv1 "github.com/symbioticfi/relay/internal/gen/api/v1"
)

// Exported types for client usage

// Enums
type ErrorCode = apiv1.ErrorCode
type SigningStatus = apiv1.SigningStatus
type ValidatorSetStatus = apiv1.ValidatorSetStatus

// Enum constants
const (
	// ErrorCode values
	ErrorCode_ERROR_CODE_UNSPECIFIED = apiv1.ErrorCode_ERROR_CODE_UNSPECIFIED
	ErrorCode_ERROR_CODE_NO_DATA = apiv1.ErrorCode_ERROR_CODE_NO_DATA
	ErrorCode_ERROR_CODE_INTERNAL = apiv1.ErrorCode_ERROR_CODE_INTERNAL
	ErrorCode_ERROR_CODE_NOT_AGGREGATOR = apiv1.ErrorCode_ERROR_CODE_NOT_AGGREGATOR

	// SigningStatus values
	SigningStatus_SIGNING_STATUS_UNSPECIFIED = apiv1.SigningStatus_SIGNING_STATUS_UNSPECIFIED
	SigningStatus_SIGNING_STATUS_PENDING = apiv1.SigningStatus_SIGNING_STATUS_PENDING
	SigningStatus_SIGNING_STATUS_COMPLETED = apiv1.SigningStatus_SIGNING_STATUS_COMPLETED
	SigningStatus_SIGNING_STATUS_FAILED = apiv1.SigningStatus_SIGNING_STATUS_FAILED
	SigningStatus_SIGNING_STATUS_TIMEOUT = apiv1.SigningStatus_SIGNING_STATUS_TIMEOUT

	// ValidatorSetStatus values
	ValidatorSetStatus_VALIDATOR_SET_STATUS_UNSPECIFIED = apiv1.ValidatorSetStatus_VALIDATOR_SET_STATUS_UNSPECIFIED
	ValidatorSetStatus_VALIDATOR_SET_STATUS_INACTIVE = apiv1.ValidatorSetStatus_VALIDATOR_SET_STATUS_INACTIVE
	ValidatorSetStatus_VALIDATOR_SET_STATUS_ACTIVE = apiv1.ValidatorSetStatus_VALIDATOR_SET_STATUS_ACTIVE
)

// Request types
type GetAggregationProofRequest = apiv1.GetAggregationProofRequest
type GetAggregationStatusRequest = apiv1.GetAggregationStatusRequest
type GetCurrentEpochRequest = apiv1.GetCurrentEpochRequest
type GetSignatureRequestRequest = apiv1.GetSignatureRequestRequest
type GetSignaturesRequest = apiv1.GetSignaturesRequest
type GetSuggestedEpochRequest = apiv1.GetSuggestedEpochRequest
type GetValidatorByAddressRequest = apiv1.GetValidatorByAddressRequest
type GetValidatorSetHeaderRequest = apiv1.GetValidatorSetHeaderRequest
type GetValidatorSetRequest = apiv1.GetValidatorSetRequest
type SignMessageRequest = apiv1.SignMessageRequest
type SignMessageWaitRequest = apiv1.SignMessageWaitRequest

// Response types
type GetAggregationProofResponse = apiv1.GetAggregationProofResponse
type GetAggregationStatusResponse = apiv1.GetAggregationStatusResponse
type GetCurrentEpochResponse = apiv1.GetCurrentEpochResponse
type GetSignatureRequestResponse = apiv1.GetSignatureRequestResponse
type GetSignaturesResponse = apiv1.GetSignaturesResponse
type GetSuggestedEpochResponse = apiv1.GetSuggestedEpochResponse
type GetValidatorByAddressResponse = apiv1.GetValidatorByAddressResponse
type GetValidatorSetHeaderResponse = apiv1.GetValidatorSetHeaderResponse
type GetValidatorSetResponse = apiv1.GetValidatorSetResponse
type SignMessageResponse = apiv1.SignMessageResponse
type SignMessageWaitResponse = apiv1.SignMessageWaitResponse

// Data types
type AggregationProof = apiv1.AggregationProof
type Key = apiv1.Key
type Signature = apiv1.Signature
type Validator = apiv1.Validator
type ValidatorVault = apiv1.ValidatorVault
