// Code generated by generate-client-types. DO NOT EDIT.
package v1

import (
	apiv1 "github.com/symbioticfi/relay/internal/gen/api/v1"
)

// Exported types for client usage

// Enums
type ErrorCode = apiv1.ErrorCode
type SigningStatus = apiv1.SigningStatus
type ValidatorSetStatus = apiv1.ValidatorSetStatus

// Enum constants
const (
	// ErrorCode values
	ErrorCode_ERROR_CODE_UNSPECIFIED    = apiv1.ErrorCode_ERROR_CODE_UNSPECIFIED
	ErrorCode_ERROR_CODE_NO_DATA        = apiv1.ErrorCode_ERROR_CODE_NO_DATA
	ErrorCode_ERROR_CODE_INTERNAL       = apiv1.ErrorCode_ERROR_CODE_INTERNAL
	ErrorCode_ERROR_CODE_NOT_AGGREGATOR = apiv1.ErrorCode_ERROR_CODE_NOT_AGGREGATOR

	// SigningStatus values
	SigningStatus_SIGNING_STATUS_UNSPECIFIED = apiv1.SigningStatus_SIGNING_STATUS_UNSPECIFIED
	SigningStatus_SIGNING_STATUS_PENDING     = apiv1.SigningStatus_SIGNING_STATUS_PENDING
	SigningStatus_SIGNING_STATUS_COMPLETED   = apiv1.SigningStatus_SIGNING_STATUS_COMPLETED
	SigningStatus_SIGNING_STATUS_FAILED      = apiv1.SigningStatus_SIGNING_STATUS_FAILED
	SigningStatus_SIGNING_STATUS_TIMEOUT     = apiv1.SigningStatus_SIGNING_STATUS_TIMEOUT

	// ValidatorSetStatus values
	ValidatorSetStatus_VALIDATOR_SET_STATUS_UNSPECIFIED = apiv1.ValidatorSetStatus_VALIDATOR_SET_STATUS_UNSPECIFIED
	ValidatorSetStatus_VALIDATOR_SET_STATUS_DERIVED     = apiv1.ValidatorSetStatus_VALIDATOR_SET_STATUS_DERIVED
	ValidatorSetStatus_VALIDATOR_SET_STATUS_AGGREGATED  = apiv1.ValidatorSetStatus_VALIDATOR_SET_STATUS_AGGREGATED
	ValidatorSetStatus_VALIDATOR_SET_STATUS_COMMITTED   = apiv1.ValidatorSetStatus_VALIDATOR_SET_STATUS_COMMITTED
	ValidatorSetStatus_VALIDATOR_SET_STATUS_MISSED      = apiv1.ValidatorSetStatus_VALIDATOR_SET_STATUS_MISSED
)

// Request types
type GetAggregationProofRequest = apiv1.GetAggregationProofRequest
type GetAggregationStatusRequest = apiv1.GetAggregationStatusRequest
type GetCurrentEpochRequest = apiv1.GetCurrentEpochRequest
type GetLastAllCommittedRequest = apiv1.GetLastAllCommittedRequest
type GetLastCommittedRequest = apiv1.GetLastCommittedRequest
type GetSignatureRequestRequest = apiv1.GetSignatureRequestRequest
type GetSignaturesRequest = apiv1.GetSignaturesRequest
type GetValidatorByAddressRequest = apiv1.GetValidatorByAddressRequest
type GetValidatorSetHeaderRequest = apiv1.GetValidatorSetHeaderRequest
type GetValidatorSetMetadataRequest = apiv1.GetValidatorSetMetadataRequest
type GetValidatorSetRequest = apiv1.GetValidatorSetRequest
type ListenProofsRequest = apiv1.ListenProofsRequest
type ListenSignaturesRequest = apiv1.ListenSignaturesRequest
type ListenValidatorSetRequest = apiv1.ListenValidatorSetRequest
type SignMessageRequest = apiv1.SignMessageRequest

// Response types
type GetAggregationProofResponse = apiv1.GetAggregationProofResponse
type GetAggregationStatusResponse = apiv1.GetAggregationStatusResponse
type GetCurrentEpochResponse = apiv1.GetCurrentEpochResponse
type GetLastAllCommittedResponse = apiv1.GetLastAllCommittedResponse
type GetLastCommittedResponse = apiv1.GetLastCommittedResponse
type GetSignatureRequestResponse = apiv1.GetSignatureRequestResponse
type GetSignaturesResponse = apiv1.GetSignaturesResponse
type GetValidatorByAddressResponse = apiv1.GetValidatorByAddressResponse
type GetValidatorSetHeaderResponse = apiv1.GetValidatorSetHeaderResponse
type GetValidatorSetMetadataResponse = apiv1.GetValidatorSetMetadataResponse
type GetValidatorSetResponse = apiv1.GetValidatorSetResponse
type ListenProofsResponse = apiv1.ListenProofsResponse
type ListenSignaturesResponse = apiv1.ListenSignaturesResponse
type ListenValidatorSetResponse = apiv1.ListenValidatorSetResponse
type SignMessageResponse = apiv1.SignMessageResponse

// Data types
type AggregationProof = apiv1.AggregationProof
type ChainEpochInfo = apiv1.ChainEpochInfo
type ExtraData = apiv1.ExtraData
type Key = apiv1.Key
type Signature = apiv1.Signature
type Validator = apiv1.Validator
type ValidatorSet = apiv1.ValidatorSet
type ValidatorVault = apiv1.ValidatorVault
